### ISSUE TITLE
jnius is not working with webview bootstrap

### ISSUE THREAD

**Issue by OBKF** [kivy/python-for-android#1003]
Hey, 
I have compiled the test app from [python-for-android testapps](https://github.com/kivy/python-for-android/tree/master/testapps/testapp_flask), but i can't manage to use Pyjnius, i know that it depends on [SDL ](https://blog.kivy.org/2016/05/android-apps-with-python-flask-and-a-webview/#technical-details) and it's a little bit hacky to make it work.
can someone show me a way to do it?

**Comment by FeralBytes** [comment]
@OBKF what is the exact error and what have you tried to do?

**Comment by OBKF** [comment]
Nothing much really, I just want to push the notifications using player or jnuis.
the problem is jnuis need SDL to get the JNIEnv, and i don't want to pack all the SDL library into my app.
I am using this commands to compile the apk
 `p4a apk --private . --package com.example.app \
--name "App" \
--version 0.1 \
--sdk_dir /someplace/android-sdk-21/ \
--android_api 16 \
--ndk_dir /someplace/android-ndk-r12b/ \
--ndk_ver r12b \
--whitelist whitelist.txt \
--bootstrap webview \
--requirements genericndkbuild,flask,jnius,python2,plyer \
--port 5000 \
--arch=armeabi-v7a \
--permission VIBRATE \
--permission INTERNET \`
now the only thing i need is to make jnius work. [more explanation from kivy blog](https://blog.kivy.org/2016/05/android-apps-with-python-flask-and-a-webview/#technical-details)

**Comment by inclement** [comment]
You shouldn't need to include SDL for pyjnius to work, as the pyjnius recipe [specifically patches pyjnius](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/pyjnius/__init__.py#L16) to modify this dependency.

Could you paste the full log of a new build (after first cleaning everything with `p4a clean-dists` and `p4a clean-builds`? The log should indicate if this patch is aplied, and why it fails.

**Comment by FeralBytes** [comment]
You may also need to update P4A to ensure you get the recipe that patches pyjnius.

**Comment by OBKF** [comment]
@inclement [here](http://pasteall.org/248246) the full log after cleaning everything.
@FeralBytes I did that too.
and finally part of the [p4a logcat](http://pasteall.org/248257)

**Comment by FeralBytes** [comment]
@OBKF The first log is unfortunately; super vague; can you add some print statements to say what you are about to do; so we can tell where you are in your script? Also the source code after you add those prints will help us all follow along.
The P4A build log shows multiple errors the most important being that you failed to download hotspython2; thus the build should have failed. I am not sure why it succeeded; but your build is most likely missing crucial portions of Python; which is obviously important.
Relevant error below:
```
[INFO]:    -> running rm -f .mark-Python-2.7.2.tar.bz2                        
[INFO]:    Downloading hostpython2 from http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 900, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/build.py", line 542, in build_recipes
    recipe.download_if_necessary()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/recipe.py", line 344, in download_if_necessary
    self.download()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/recipe.py", line 384, in download
    self.download_file(url, filename)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/recipe.py", line 150, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python2.7/urllib.py", line 289, in retrieve
    "of %i bytes" % (read, size), result)
urllib.ContentTooShortError: retrieval incomplete: got only 2710203 out of 11754834 bytes
```

**Comment by OBKF** [comment]
Hello,
I have cleaned p4a another time and rebuild my app with a ton of prints and it seams that it cant import jnius.
code:
```
print('main.py was successfully called')
print('this is the new main.py')

import os
print('imported os')

try:
    print('contents of ./lib/python2.7/site-packages/ etc.')
    print(os.listdir('./lib'))
    print(os.listdir('./lib/python2.7'))
    print(os.listdir('./lib/python2.7/site-packages'))
except OSError:
    print('could not look in dirs')
    print('this is expected on desktop')

import flask
print('flask1???')

print('contents of this dir', os.listdir('./'))

import flask
print('flask???')

import sys
print('pythonpath is\n\n\n', sys.path)


from flask import Flask
app = Flask(__name__)

from flask import (Flask, url_for, render_template, request, redirect,
                   flash)

print('imported flask etc--------------------------------------------------------------')
print('importing pyjnius-------------------------------------------------------------')


print "\n\n\n\n\n\n\n\n\n\n\n\n\n----------------------------------------------------------"

try:
    from jnius import autoclass
    try:    
        Context = autoclass('android.content.Context')
        PythonActivity = autoclass('org.kivy.android.PythonActivity')
        activity = PythonActivity.mActivity
        vibrator = activity.getSystemService(Context.VIBRATOR_SERVICE)
        ActivityInfo = autoclass('android.content.pm.ActivityInfo')
        print "everything works fine----------------------------------------------"
    except:
        print "not on android or there is something wrong"
except:
    print "can't import jnius (typo jnuis)--------------------------------------------------"


@app.route('/')
def page1():
    return render_template('index.html')

@app.route('/page2/')
def page2():
    return render_template('page2.html')

@app.route('/vibrate/')
def vibrate():
    args = request.args
    if 'time' not in args:
        print('ERROR: asked to vibrate but without time argument')
    print('asked to vibrate', args['time'])

    try:
        vibrator.vibrate(float(args['time']) * 1000)
        print('vibrated')
    except:
        print "not Vibrating -------------------------------------------------------------"

@app.route('/loadUrl/')
def loadUrl():
    args = request.args
    if 'url' not in args:
        print('ERROR: asked to open an url but without url argument')
    print('asked to open url', args['url'])
    try:
        activity.loadUrl(args['url'])
    except:
        print "no loading url ----------------------------------------------------------------"

@app.route('/orientation/')
def orientation():
    args = request.args
    if 'dir' not in args:
        print('ERROR: asked to orient but no dir specified')
    direction = args['dir']
    if direction not in ('horizontal', 'vertical'):
        print('ERROR: asked to orient to neither horizontal nor vertical')

    if direction == 'horizontal':
        activity.setRequestedOrientation(
            ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE)
    else:
        activity.setRequestedOrientation(
            ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)


from os import curdir
from os.path import realpath
print('curdir', realpath(curdir))
if realpath(curdir).startswith('/data'):
    app.run(debug=False)
else:
    app.run(debug=True)

```

[Build log](http://pasteall.org/251666)
adb logcat is too long.

**PS:**
when i build an app with SDL and access `http://127.0.0.1:5000/ `on chrome (on **android**) it works fine.

**Comment by inclement** [comment]
Using catchall try/except blocks is not a good idea here, as you've made it so that that any error in the jnius import gives the same error message. Remove the try/except and post the logcat output during the failing run.

**Comment by OBKF** [comment]
Now after removing the try/except i got this error:
```
I/python  ( 4527): imported flask etc--------------------------------------------------------------
I/python  ( 4527): importing pyjnius-------------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/python  ( 4527): ----------------------------------------------------------
I/System.out( 4527): [socket][19:43397] exception
I/System.out( 4527): [CDS]close[43397]
I/System.out( 4527): close [socket][/0.0.0.0:43397]
V/WebViewLoader( 4527): Could not ping localhost:5000
I/python  ( 4527): Traceback (most recent call last):
I/python  ( 4527):   File "main.py", line 52, in <module>
I/python  ( 4527):     from jnius import autoclass
I/python  ( 4527):   File "/data/data/com.sudo_dev.Jiddly/files/lib/python2.7/site-packages/jnius/__init__.py", line 12, in <module>
I/python  ( 4527):     from .jnius import *
I/python  ( 4527): ImportError: dlopen failed: "/data/data/com.sudo_dev.Jiddly/files/lib/python2.7/site-packages/jnius/jnius.so" not 32-bit: 2
D/AwContents( 4527): setContentsSize 320, 508
D/AwContents( 4527): setPageScaleFactor 1.0
D/AwContents( 4527): setContentsSize 320, 508
D/AwContents( 4527): setPageScaleFactor 1.0
D/AwContents( 4527): setContentsSize 320, 508
D/AwContents( 4527): setPageScaleFactor 1.0
I/python  ( 4527): Python for android ended.
```
![error](http://pasteall.org/pic/show.php?id=112663)
[error in the console](http://pasteall.org/pic/index.php?id=112663)

**Comment by OBKF** [comment]
any news about this by any chance?!

**Comment by inclement** [comment]
I'm afraid I don't know what is wrong here.

**Comment by OBKF** [comment]
Thank you anyway,
I am about to finish my app using Qt5.8, i will be back to this later.

**Comment by OBKF** [comment]
Is this working now?

**Comment by inclement** [comment]
I think yes, please open a new issue if you find it isn't.

**Comment by OBKF** [comment]
I will, thank you.
