### ISSUE TITLE
dlopen failed: python2.7/site-packages/grpc/_cython/cygrpc.so not 32-bit: 2

### ISSUE THREAD

**Issue by tito** [kivy/python-for-android#1052]
@gbdantoni commented on [Mon Mar 13 2017](https://github.com/kivy/buildozer/issues/479)

I'm trying to build a python app for Android that uses grpc. I'm using Buildozer 0.32 with the new toolchain on Ubuntu 16.04.2.  The build succeeds and it produces an APK but when I try to launch it on an Android tablet I'm getting the following output from logcat.  My requirements statement includes kivy, grpcio, hostpython2, enum

```I/python  (29857): Run user program, change dir and execute entrypoint
I/python  (29857): Traceback (most recent call last):
I/python  (29857):   File "/media/newDrive/gaitan/PythonProjects/hwclient/.buildozer/android/app/main.py", line 34, in <module>
I/python  (29857):   File "/media/newDrive/gaitan/PythonProjects/hwclient/.buildozer/android/platform/build/dists/hwclient/private/lib/python2.7/site-packages/grpc/__init__.py", line 37, in <module>
I/python  (29857): ImportError: dlopen failed: "/data/data/ddw_gd.com.hwclient/files/app/lib/python2.7/site-packages/grpc/_cython/cygrpc.so" not 32-bit: 2
I/python  (29857): Python for android ended.
```

---

@tito commented on [Sun May 14 2017](https://github.com/kivy/buildozer/issues/479#issuecomment-301342643)

Hi, this is not related to buildozer itself, but python-for-android at least. I'm moving the issue.

**Comment by NeonSky** [comment]
@inclement why was this issue closed? I am currently facing a very similar issue when using Firestore.
```
05-16 11:15:52.027 19979 20220 I python  :  Traceback (most recent call last):
05-16 11:15:52.028 19979 20220 I python  :    File "/buildozer/app/.buildozer/android/app/main.py", line 7, in <module>
05-16 11:15:52.028 19979 20220 I python  :    File "/buildozer/app/.buildozer/android/app/presenter/delivery_request_form.py", line 7, in <module>
05-16 11:15:52.028 19979 20220 I python  :    File "/buildozer/app/.buildozer/android/app/model/delivery_request_uploader.py", line 2, in <module>
05-16 11:15:52.029 19979 20220 I python  :    File "/buildozer/app/.buildozer/android/app/model/firebase/firestore.py", line 5, in <module>
05-16 11:15:52.029 19979 20220 I python  :    File "/buildozer/app/.buildozer/android/platform/build/build/python-installs/carrepsa/google/cloud/firestore_v1/__init__.py", line 22, in <module>
05-16 11:15:52.029 19979 20220 I python  :    File "/buildozer/app/.buildozer/android/platform/build/build/python-installs/carrepsa/google/cloud/firestore_v1/_helpers.py", line 21, in <module>
05-16 11:15:52.030 19979 20220 I python  :    File "/buildozer/app/.buildozer/android/platform/build/build/python-installs/carrepsa/grpc/__init__.py", line 23, in <module>
05-16 11:15:52.030 19979 20220 I python  :  ImportError: dlopen failed: "/data/data/org.jigglypuff.carrepsa/files/app/_python_bundle/site-packages/grpc/_cython/cygrpc.so" is 64-bit instead of 32-bit
```

**Comment by inclement** [comment]
@NeonSky Because it was old and had no followup.

The issue is that grpc needs a [python-for-android](https://python-for-android.readthedocs.io/en/latest/recipes/) recipe to build correctly. Right now it's been built for your desktop, not your phone, that's why the architecture is wrong.

We should be able to log a better message when this happens, feel free to open an issue about this if there isn't one already.

**Comment by JuditNugroho** [comment]
@NeonSky can u solve the problem? because i got this error too

**Comment by callumpurcell1** [comment]
Also had the same problem, any solution?

**Comment by Kulothungan16** [comment]
I am also facing this error when using google-cloud-firestore module

Is making a recipe for this would fix this issue?
P.S. I tried but its a bit confusing

**Comment by Splato** [comment]
I tried to fork the existing recipe, https://github.com/hpsaturn/p4a_grpc_recipe/blob/master/__init__.py. The recipe there was built inside the docker container, and all the dependencies were also installed separately.
In my fork https://github.com/Splato/p4a_grpc_recipe/edit/master/__init__.py I install all dependencies as 'modules' (code lines 129-133) except for the openssl package (grpc installs BoringSSL that fails in p4a). However, I get the following error after compiling 60% of the recipe:
```
[ 60%] Linking CXX shared library libgrpc_plugin_support.so
CMakeFiles/grpc_plugin_support.dir/src/compiler/python_generator.cc.o: In function `PythonGrpcGenerator':
~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/src/compiler/python_generator.cc:829: undefined reference to `google::protobuf::compiler::CodeGenerator::~CodeGenerator()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/grpc_plugin_support.dir/build.make:175: libgrpc_plugin_support.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:894: CMakeFiles/grpc_plugin_support.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Then I also tried to include protobuf as dependencies in the grpc recipe (the recipe protobuf_cpp https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/protobuf_cpp/__init__.py). Then I changed the protobuf to 'package' (129) and the path to libraries and executables in cmake (lines 112-115). However, then I got another error:
```
-- Looking for __system_property_get - found
CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:469 (file):
  file STRINGS file "/opt/install/include/google/protobuf/stubs/common.h"
  cannot be read.
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:475 (math):
  math cannot parse the expression: " / 1000000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:476 (math):
  math cannot parse the expression: " / 1000 % 1000": syntax error,
  unexpected exp_DIVIDE (2).
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:477 (math):
  math cannot parse the expression: " % 1000": syntax error, unexpected
  exp_MOD (2).
Call Stack (most recent call first):
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:261 (include)


-- Found Protobuf: /opt/install/lib/libprotobuf.a (found version "ERROR.ERROR.ERROR") 
-- Found OpenSSL: ~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/openssl/arm64-v8a__ndk_target_21/openssl1.1/libcrypto.so (found version "1.1.1k")  
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Renaming
--     ~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/third_party/zlib/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- Configuring incomplete, errors occurred!
See also "~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/build/CMakeFiles/CMakeOutput.log".
See also "~/.buildozer/android/platform/build-arm64-v8a/build/other_builds/grpcio/arm64-v8a__ndk_target_21/grpcio/grpc/build/CMakeFiles/CMakeError.log".
```
So I guess at this point, I need some help with configuring the protobuf installation. Thanks.

**Comment by ALooRD8** [comment]
I have the same issue any solution

**Comment by TLQB** [comment]
I have the same issue.
