### ISSUE TITLE
running p4a from git fails

### ISSUE THREAD

**Issue by hemna** [kivy/python-for-android#1058]
1. mkdir ~/devel/android/.venv
2. virtualenv ~/devel/android/.venv
3. git clone python-for-android
4. source ~/devel/android/.venv/bin/activate
5. cd python-for-android
6. pip install .
7. p4a

Traceback (most recent call last):
  File "/home/waboring/devel/android/.venv/bin/p4a", line 11, in <module>
    load_entry_point('python-for-android', 'console_scripts', 'p4a')()
  File "/home/waboring/devel/android/python-for-android/pythonforandroid/toolchain.py", line 902, in main
    ToolchainCL()
  File "/home/waboring/devel/android/python-for-android/pythonforandroid/toolchain.py", line 470, in __init__
    setup_color(args.color)
AttributeError: 'Namespace' object has no attribute 'color'

**Comment by inclement** [comment]
Thanks for the report. I think I understand the problem and will try to push a fix soon, but I think this will only happen if you run `p4a` without any command argument, which wouldn't do anything anyway. It shouldn't prevent running any of the commands.
