### ISSUE TITLE
Error after update of SDK

### ISSUE THREAD

**Issue by konbernu** [kivy/python-for-android#1070]
I updated my SDK and since then I have the following Error:

[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 754, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 343, in __init__
    getattr(self, command_method_name)(unknown)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 87, in wrapper_func
    user_ndk_ver=self.ndk_version)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 227, in prepare_build_environment
    targets = android('list').stdout.decode('utf-8').split('\n')
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1223, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 628, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 646, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 667, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /home/developer/Android/Sdk/tools/android list

  STDOUT:
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "list"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk

  STDERR:

**Comment by misl6** [comment]
See : kivy/buildozer#519

**Comment by inclement** [comment]
This should be fixed by https://github.com/kivy/python-for-android/pull/1042 , but it isn't yet ready to merge.

(This android issue is actually easier to deal with and doesn't need such a big PR, I might merge a fix for it separately).

**Comment by inclement** [comment]
It looks like this should be fixed in the master branch. If you still have problems, let me know and I'll reopen the issue.

**Comment by ZhangKuixun** [comment]
How to repair it? Why don't I understand? @konbernu
