### ISSUE TITLE
Building with Crystax NDK : "Android NDK : Could not find application project directory"

### ISSUE THREAD

**Issue by ariard** [kivy/python-for-android#1084]
Hi,

I'm trying to build an app under Python3 with Crystax NDK but it seems that it doesn't found the app project directory. NDK_PROJECT_PATH is set as "/media/sf_electrum/" any idea what is wrong ?

The log 

`kivy@kivyvm:/media/sf_electrum/gui/kivy$ p4a create -dist_name=Electrum --bootstrap=sdl2 --requirements=python3crystax,android,openssl,pycrypto,pil,plyer,kivy==master --arch armeabi-v7a --copy-libs --color=always --storage-dir=/media/sf_electrum/.buildozer/android/platform/build --ndk-dir=/home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/ --android_api=19 --ndk_ver=crystax-ndk-10.3.2
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
[INFO]:    Recipe kivy: version "master" requested
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found possible SDK dirs in buildozer dir: android-sdk-20
[INFO]:    Will attempt to use SDK at /home/kivy/.buildozer/android/platform/android-sdk-20
[WARNING]: This SDK lookup is intended for debug only, if you use python-for-android much you should probably maintain your own SDK download.
[INFO]:    Getting Android API version from user argument
[INFO]:    Available Android APIs are (14, 19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Getting NDK dir from from user argument
[INFO]:    Got NDK version from from user argument
[WARNING]: NDK version was set as crystax-ndk-10.3.2, but checking the NDK dir claims it is 10.3.2.
[WARNING]: The build will try to continue, but it may fail and you should check that your setting is correct.
[WARNING]: If the NDK dir result is correct, you don't need to manually set the NDK ver.
[INFO]:    Using Crystax NDK crystax-ndk-10.3.2
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[WARNING]: Missing executable: autoconf is not installed
[WARNING]: Missing executable: automake is not installed
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Bootstrap requires recipes ['sdl2', ('python2', 'python3crystax')]
[INFO]:    No recipe named plyer; will attempt to install with pip
[INFO]:    Loaded recipe pil (depends on [('python2', 'python3crystax'), 'png', 'jpeg'])
[INFO]:    Loaded recipe pycrypto (depends on ['openssl', 'python3crystax'])
[INFO]:    Loaded recipe kivy (depends on ['pyjnius', ('sdl2', 'pygame'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe android (depends on [('python2', 'python3crystax'), ('pygame', 'sdl2', 'genericndkbuild')])
[INFO]:    Loaded recipe sdl2 (depends on [('python2', 'python3crystax'), 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf'], conflicts ['sdl', 'pygame', 'pygame_bootstrap_components'])
[INFO]:    Loaded recipe openssl (depends on [])
[INFO]:    Loaded recipe python3crystax (depends on ['hostpython3crystax'], conflicts ['python2', 'python3'])
[INFO]:    Loaded recipe png (depends on [])
[INFO]:    Loaded recipe jpeg (depends on [])
[INFO]:    Loaded recipe pyjnius (depends on ['six', ('sdl2', 'sdl', 'genericndkbuild'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe sdl2_image (depends on [])
[INFO]:    Loaded recipe sdl2_mixer (depends on [])
[INFO]:    Loaded recipe sdl2_ttf (depends on [])
[INFO]:    Loaded recipe hostpython3crystax (depends on [], conflicts ['hostpython2'])
[INFO]:    Loaded recipe six (depends on [('python2', 'python3crystax')])
[INFO]:    Found a single valid recipe set (this is good)
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name unnamed_dist_7 and recipes (python3crystax, android, openssl, pycrypto, pil, plyer, kivy)
[INFO]:    -> running cp -r /usr/local/lib/python2.7/dist-packages/pythonforandroid/bootstraps/sdl2/build /media/sf_electrum/.buildozer/android/platform/build/build/bootstrap_...(and 26 more)
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Recipe build order is ['hostpython3crystax', 'jpeg', 'openssl', 'png', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', u'pil', u'pycrypto', 'sdl2', 'six', u'android', 'pyjnius', u'kivy']
[INFO]:    The requirements (plyer) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3crystax
[INFO]:    Skipping hostpython3crystax download as no URL is set
[INFO]:    Downloading jpeg
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/jpeg
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/jpeg
[INFO]:    -> running basename git://git.linaro.org/people/tomgall/libjpeg-turbo/libjpeg-turbo.git
[WARNING]: Should check headers here! Skipping for now.                                                                                                                                                   
Downloading jpeg from git://git.linaro.org/people/tomgall/libjpeg-turbo/libjpeg-turbo.git
[INFO]:    -> running rm -f .mark-libjpeg-turbo.git
[INFO]:    Downloading jpeg from git://git.linaro.org/people/tomgall/libjpeg-turbo/libjpeg-turbo.git
[INFO]:    -> directory context libjpeg-turbo.git
[INFO]:    -> running git fetch --tags
[INFO]:    -> running git checkout linaro-android
[INFO]:    -> running git pull                                                                                                                                                                            
[INFO]:    -> running git pull --recurse-submodules                                                                                                                                                       
[INFO]:    -> running git submodule update --recursive                                                                                                                                                    
[INFO]:    <- directory context /media/sf_electrum/.buildozer/android/platform/build/packages/jpeg
[INFO]:    -> running touch .mark-libjpeg-turbo.git
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/openssl
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/openssl
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.0.2g.tar.gz
[INFO]:    openssl download already cached, skipping                                                                                                                                                      
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading png
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/png
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/png
[INFO]:    -> running basename https://github.com/julienr/libpng-android/archive/1.6.15.zip
[INFO]:    png download already cached, skipping                                                                                                                                                          
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    sdl2_image download already cached, skipping                                                                                                                                                   
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping                                                                                                                                                   
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping                                                                                                                                                     
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading python3crystax
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/python3crystax
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/python3crystax
[INFO]:    -> running basename 
[WARNING]: Should check headers here! Skipping for now.
Downloading python3crystax from 
[INFO]:    -> running rm -f .mark-
[INFO]:    -> running touch .mark-
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading pil
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/pil
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/pil
[INFO]:    -> running basename http://effbot.org/downloads/Imaging-1.1.7.tar.gz
[INFO]:    pil download already cached, skipping                                                                                                                                                          
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading pycrypto
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/pycrypto
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/pycrypto
[INFO]:    -> running basename https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz
[INFO]:    pycrypto download already cached, skipping                                                                                                                                                     
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    sdl2 download already cached, skipping                                                                                                                                                         
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/six
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    six download already cached, skipping                                                                                                                                                          
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    pyjnius download already cached, skipping                                                                                                                                                      
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /media/sf_electrum/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    kivy download already cached, skipping                                                                                                                                                         
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3crystax for armeabi-v7a
[INFO]:    Skipping hostpython3crystax unpack as no URL is set
[INFO]:    Unpacking jpeg for armeabi-v7a
[INFO]:    -> running basename git://git.linaro.org/people/tomgall/libjpeg-turbo/libjpeg-turbo.git
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/jpeg/armeabi-v7a                                                                                  
[INFO]:    jpeg is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.0.2g.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a                                                                               
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking png for armeabi-v7a
[INFO]:    -> running basename https://github.com/julienr/libpng-android/archive/1.6.15.zip
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/png/armeabi-v7a                                                                                   
[INFO]:    png is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni                                                                       
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni                                                                       
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni                                                                       
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking python3crystax for armeabi-v7a
[INFO]:    -> running basename 
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a
[INFO]:    python3crystax is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking pil for armeabi-v7a
[INFO]:    -> running basename http://effbot.org/downloads/Imaging-1.1.7.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/pil-python3crystax/armeabi-v7a                                                                    
[INFO]:    pil is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking pycrypto for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/pycrypto/armeabi-v7a                                                                              
[INFO]:    pycrypto is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni                                                                       
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a                                                                    
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    -> running rm -rf /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/android-python3crystax-sdl2/armeabi-v7a/android
[INFO]:    -> running cp -a /usr/local/lib/python2.7/dist-packages/pythonforandroid/recipes/android/src /media/sf_electrum/.buildozer/android/platform/build/build/other_builds...(and 48 more)
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a                                                           
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/kivy-python3crystax-sdl2/armeabi-v7a                                                              
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3crystax for armeabi-v7a
[INFO]:    hostpython3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding jpeg for armeabi-v7a
[INFO]:    jpeg has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for jpeg[armeabi-v7a]
[INFO]:    jpeg already patched, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding png for armeabi-v7a
[INFO]:    png has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3crystax for armeabi-v7a
[INFO]:    python3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pil for armeabi-v7a
[INFO]:    pil has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pil[armeabi-v7a]
[INFO]:    pil already patched, skipping
[INFO]:    Prebuilding pycrypto for armeabi-v7a
[INFO]:    pycrypto has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pycrypto[armeabi-v7a]
[INFO]:    pycrypto already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/android-python3crystax-sdl2/armeabi-v7a/android
[INFO]:    <- directory context /media/sf_electrum/gui/kivy
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3crystax for armeabi-v7a
[INFO]:    Building jpeg for armeabi-v7a
('path is', '/home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/toolchains/arm-linux-androideabi-5/prebuilt/linux-x86/bin/:/home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/toolchains/arm-linux-androideabi-5/prebuilt/linux-x86_64/bin/:/home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2:/home/kivy/.buildozer/android/platform/android-sdk-20/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin')
[INFO]:    -> directory context /media/sf_electrum/.buildozer/android/platform/build/build/other_builds/jpeg/armeabi-v7a/jpeg
[INFO]:    -> running ndk-build V=1 APP_ABI=armeabi-v7a
           working: /home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.                                                        Exception in thread background thread for pid 6289:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_2: 

  RAN: /home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/ndk-build V=1 APP_ABI=armeabi-v7a

  STDOUT:
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.

  STDERR:

Traceback (most recent call last):                                                                                                                                                                        
  File "/usr/local/bin/p4a", line 11, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 754, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 343, in __init__
    getattr(self, command_method_name)(unknown)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 561, in build_recipes
    recipe.build_arch(arch)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipes/jpeg/__init__.py", line 29, in build_arch
    super(JpegRecipe, self).build_arch(arch)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipe.py", line 698, in build_arch
    shprint(sh.ndk_build, 'V=1', 'APP_ABI=' + arch.arch, *extra_args, _env=env)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/logger.py", line 173, in shprint
    for line in output:
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 863, in next
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/ndk-build V=1 APP_ABI=armeabi-v7a

  STDOUT:
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/home/kivy/.buildozer/android/platform/crystax-ndk-10.3.2/build/core/build-local.mk:143: *** Android NDK: Aborting    .  Stop.

  STDERR:`

**Comment by ariard** [comment]
Solved, build_dir was missing in buildozer.specs
