### ISSUE TITLE
Error on building FFPYPLAYER for VideoPlayer Widget

### ISSUE THREAD

**Issue by mfaessel** [kivy/python-for-android#1130]
Hi,

Need help…
I’m trying to build an Android APK with Kivy VideoPlayer and Video Widgets
But get a ffplayer error

Here is my buildozer.spec file
https://pastebin.com/xeEJX9PB

I have tried on OSX Sierra and it's the same error appears on the Buildozer VM build.

Some comments :

- the videos work fine in Kivy Launcher
- if i build without ffmepg or ffpyplayer the app is build but VideoPlayer don't work
- I even try with different Cython version downgrade but no luck

Any idea?

****
```

[INFO]:    -> running configure --disable-everything --enable-parser=h264,aac --enab...(and 679 more)
           working: See ./configure --help for available options.                                              Exception in thread background thread for pid 51407:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/martial/Library/Python/2.7/lib/python/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/Users/martial/Library/Python/2.7/lib/python/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/martial/Library/Python/2.7/lib/python/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 

  RAN: ./configure --disable-everything --enable-parser=h264,aac --enable-decoder=h263,h264,aac --disable-dxva2 --disable-vdpau --disable-vaapi --disable-dct --disable-symver --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --enable-filter=aresample,resample,crop,adelay,volume --enable-protocol=file,http --enable-small --enable-hwaccels --enable-gpl --enable-pic --disable-static --enable-shared --target-os=android --cross-prefix=arm-linux-androideabi- --arch=arm --sysroot=/Users/martial/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm --enable-neon --prefix=/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg

  STDOUT:
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
./configure: line 3404: __disable_vdpau: command not found
Unknown option "--disable-dxva2".
See ./configure --help for available options.


  STDERR:


Traceback (most recent call last):                                                                             
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 916, in <module>
    main()
  File "/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 913, in main
    ToolchainCL()
  File "/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 514, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 192, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 572, in build_recipes
  File "/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/ffmpeg/__init__.py", line 132, in build_arch
    shprint(configure, *flags, _env=env)
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/Users/martial/Library/Python/2.7/lib/python/site-packages/sh.py", line 720, in next
    self.wait()
  File "/Users/martial/Library/Python/2.7/lib/python/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/martial/Library/Python/2.7/lib/python/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: ./configure --disable-everything --enable-parser=h264,aac --enable-decoder=h263,h264,aac --disable-dxva2 --disable-vdpau --disable-vaapi --disable-dct --disable-symver --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --enable-filter=aresample,resample,crop,adelay,volume --enable-protocol=file,http --enable-small --enable-hwaccels --enable-gpl --enable-pic --disable-static --enable-shared --target-os=android --cross-prefix=arm-linux-androideabi- --arch=arm --sysroot=/Users/martial/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm --enable-neon --prefix=/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/build/build/other_builds/ffmpeg/armeabi-v7a/ffmpeg

  STDOUT:
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
./configure: line 3404: __disable_vdpau: command not found
Unknown option "--disable-dxva2".
See ./configure --help for available options.


  STDERR:

# Command failed: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pythonforandroid.toolchain create --dist_name=cip --bootstrap=sdl2 --requirements=kivy,python2,hostpython2,ffpyplayer --arch armeabi-v7a --copy-libs --color=always --storage-dir=/Users/martial/Documents/BuildozerProjects/CIP/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2


```

***

When tweaking the FFMPEG recipe by removing those flags

                    '--disable-dxva2 --disable-vdpau --disable-vaapi',
                    '--disable-dct',

 I get this error
 https://pastebin.com/MbkMCdXb

Thanks
Regards,

**Comment by germn** [comment]
> I get this error
> https://pastebin.com/MbkMCdXb

Not sure why it happens yet, but it looks like due to old android NDK version. Can you try to use newer version, for example, r15c and see if error still exists?

You'll need to download NDK from [here](https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip), change your buildozer.spec file this way:

```
android.ndk = 15b
android.ndk_path = /home/p4a/android-ndk-r15b  # path to your ndk here
```

**Comment by hakanb78** [comment]
Having this same issue with kivy 1.11.1 and python 3.7 running on ubuntu VM, Anyone got any ideas?
