### ISSUE TITLE
Can't build numpy with current master, python 2, NDK 15

### ISSUE THREAD

**Issue by germn** [kivy/python-for-android#1141]
Output:
https://pastebin.com/2sH9aKgx

Related part:

```
compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/p4a/test_kivy/.buildozer/android/platform/build/build/python-installs/test_kivy/include/python2.7 -c'
ccache: _configtest.c
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=19 -isystem /home/p4a/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/p4a/android-ndk-r15c/sysroot -I/home/p4a/test_kivy/.buildozer/android/platform/build/build/python-installs/test_kivy/include/python2.7 _configtest.o -o _configtest
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
collect2: error: ld returned 1 exit status
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
/home/p4a/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
collect2: error: ld returned 1 exit status
failure.
removing: _configtest.c _configtest.o
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    setup_package()
  File "setup.py", line 243, in setup_package
    setup(**metadata)
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/other_builds/numpy/armeabi-v7a/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/python-installs/test_kivy/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/python-installs/test_kivy/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/python-installs/test_kivy/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/other_builds/numpy/armeabi-v7a/numpy/numpy/distutils/command/build_ext.py", line 59, in run
    self.run_command('build_src')
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/python-installs/test_kivy/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/python-installs/test_kivy/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/other_builds/numpy/armeabi-v7a/numpy/numpy/distutils/command/build_src.py", line 153, in run
    self.build_sources()
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/other_builds/numpy/armeabi-v7a/numpy/numpy/distutils/command/build_src.py", line 164, in build_sources
    self.build_library_sources(*libname_info)
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/other_builds/numpy/armeabi-v7a/numpy/numpy/distutils/command/build_src.py", line 299, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/home/p4a/test_kivy/.buildozer/android/platform/build/build/other_builds/numpy/armeabi-v7a/numpy/numpy/distutils/command/build_src.py", line 386, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 686, in get_mathlib_info
    raise RuntimeError("Broken toolchain: cannot link a simple C program")
RuntimeError: Broken toolchain: cannot link a simple C program


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=test_kivy --bootstrap=sdl2 --requirements=python2,android,kivy,opencv --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/p4a/test_kivy/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by inclement** [comment]
Thanks for the report, I'll look into it.

**Comment by mahomahomaho** [comment]
the same here

**Comment by rbdedu** [comment]
Same here on 3 different pcs

**Comment by hutauf** [comment]
same here. is there any kind of workaround?

**Comment by hutauf** [comment]
your fix works for me, thanks @mahomahomaho

**Comment by art049** [comment]
I still have the same problem even with @mahomahomaho fix. Which version of numpy is working for you ?

**Comment by AndreMiras** [comment]
numpy + python2 is working as demonstrated in continuous integration https://github.com/kivy/python-for-android/pull/1304
Feel free to reopen if you have an updated broken case.
