### ISSUE TITLE
Unable to write the config

### ISSUE THREAD

**Issue by dav01it** [kivy/python-for-android#1151]
In Desktop app config is correctly saved, 
in android logcat gives me errors:
```
10-24 21:39:00.764 19134 19165 I python  : [ERROR  ] Unable to write the config </sdcard/.android.ini>
10-24 21:39:00.765 19134 19165 I python  : Traceback (most recent call last):
10-24 21:39:00.765 19134 19165 I python  :   File "/home/kivy/myapp/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/kivy/config.py", line 530, in write
10-24 21:39:00.765 19134 19165 I python  : IOError: [Errno 2] No such file or directory: '/sdcard/.android.ini'
```
Buildozer. specs has these permissions enabled:
android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE

**Comment by inclement** [comment]
What is the device, is it newish? I wonder is /sdcard just no longer exists. If that's the issue, it's a Kivy bug.

**Comment by dav01it** [comment]
Honor 6 phone is the device, and also /sdcard exist :-(

**Comment by inclement** [comment]
I'm not sure what's happening here - if you look at Kivy's code, it is even trying to specifically catch IOErrors here.

**Comment by dav01it** [comment]
Sorry "Inclement", not sure to understand you. 
that's what I checked
if I do
```
adb shell
cd /sdcard
touch .android.ini
ls -la
```
I see .android.ini is correctly generated.
so I think python cannot have write permissions when it tries to create/modify the file.

perhaps I have to overload get_application_config with something smarter than:
```
def get_application_config(self):
        return super(BachecaApp, self).get_application_config(
            '~/.%(appname)s.ini')
```

**Comment by bit4bit** [comment]
hi, i have the same issue, with master **python-for-android**:

~~~
12-21 14:47:31.497 10021 10068 I python  : Traceback (most recent call last):
12-21 14:47:31.497 10021 10068 I python  :   File "/data/user/0/co.com.prueba.fleet/files/app/_python_bundle/site-packages/kivy/config.py", line 530, in write
12-21 14:47:31.497 10021 10068 I python  :     with open(self.filename, 'w') as fd:
12-21 14:47:31.497 10021 10068 I python  : PermissionError: [Errno 13] Permission denied: '/sdcard/prueba.ini'
~~~
i check with adb, and directory **sdcard** exists, and have permissions for create/remove files.

**Comment by bit4bit** [comment]
> hi, i have the same issue, with master **python-for-android**:
> 
> ```
> 12-21 14:47:31.497 10021 10068 I python  : Traceback (most recent call last):
> 12-21 14:47:31.497 10021 10068 I python  :   File "/data/user/0/co.com.prueba.fleet/files/app/_python_bundle/site-packages/kivy/config.py", line 530, in write
> 12-21 14:47:31.497 10021 10068 I python  :     with open(self.filename, 'w') as fd:
> 12-21 14:47:31.497 10021 10068 I python  : PermissionError: [Errno 13] Permission denied: '/sdcard/prueba.ini'
> ```
> 
> i check with adb, and directory **sdcard** exists, and have permissions for create/remove files.



hi, i have the same issue, with master python-for-android:

12-21 14:47:31.497 10021 10068 I python  : Traceback (most recent call last):
12-21 14:47:31.497 10021 10068 I python  :   File "/data/user/0/co.com.prueba.fleet/files/app/_python_bundle/site-packages/kivy/config.py", line 530, in write
12-21 14:47:31.497 10021 10068 I python  :     with open(self.filename, 'w') as fd:
12-21 14:47:31.497 10021 10068 I python  : PermissionError: [Errno 13] Permission denied: '/sdcard/prueba.ini'

oohh!, check https://developer.android.com/guide/topics/data/data-storage#AccessingExtFiles,
since android 4.4 we can't write directly.

**Comment by bit4bit** [comment]
I found the solution,

every activity started, export environments vars:

~~~
            SDLActivity.nativeSetEnv("ANDROID_PRIVATE", mFilesDirectory);
            SDLActivity.nativeSetEnv("ANDROID_UNPACK", app_root_dir);
            SDLActivity.nativeSetEnv("PYTHONHOME", app_root_dir);
            SDLActivity.nativeSetEnv("PYTHONPATH", app_root_dir + ":" + app_root_dir + "/lib");
~~~

just, overwrite the method *get_application_config*:

~~~
    def get_application_config(self):
        from kivy.utils import platform
        if platform == 'android':
            config_path = os.path.join(os.environ['ANDROID_PRIVATE'], "/prueba.ini")
            return config_path
        return super(MainApp. self).get_application_config()
~~~

**Comment by JonasT** [comment]
@bit4bit this is a known kivy issue/limitation: https://github.com/kivy/kivy/issues/4777 pretty sure it's unrelated to python-for-android

**Comment by allasca** [comment]
how about this?
```

05-13 22:38:33.325 24558 24558 D ActivityThread: add activity client record, r= ActivityRecord{a2ffce9 token=android.os.BinderProxy@659b86c {id.allasca.migbot/org.kivy.android.PythonActivity}} token= android.os.BinderProxy@659b86c
05-13 22:38:33.350 24558 24558 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/id.allasca.migbot-wZPj0l5RP1P1dEcyXLpQHQ==/base.apk"],nativeLibraryDirectories=[/data/app/id.allasca.migbot-wZPj0l5RP1P1dEcyXLpQHQ==/lib/arm, /data/app/id.allasca.migbot-wZPj0l5RP1P1dEcyXLpQHQ==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]] couldn't find "libpython3.6m.so"
05-13 22:38:33.350 24558 24558 V pythonutil: Loading library: python3.7m
05-13 22:38:33.351 24558 24558 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/id.allasca.migbot-wZPj0l5RP1P1dEcyXLpQHQ==/base.apk"],nativeLibraryDirectories=[/data/app/id.allasca.migbot-wZPj0l5RP1P1dEcyXLpQHQ==/lib/arm, /data/app/id.allasca.migbot-wZPj0l5RP1P1dEcyXLpQHQ==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]] couldn't find "libpython3.7m.so"
05-13 22:38:33.351 24558 24558 V pythonutil: Loading library: python3.8m
05-13 22:38:33.352 24558 24558 V pythonutil: Loading library: main
05-13 22:38:33.353 24558 24558 V pythonutil: Failed to load _io.so or unicodedata.so...but that's okay.
05-13 22:38:33.353 24558 24558 V pythonutil: Unsatisfied linker when loading ctypes
05-13 22:38:33.353 24558 24558 V pythonutil: Loaded everything!
05-13 22:38:33.353 24558 24558 V SDL     : nativeSetupJNI()
05-13 22:38:33.353 24558 24558 V SDL     : AUDIO nativeSetupJNI()
05-13 22:38:33.353 24558 24558 V SDL     : CONTROLLER nativeSetupJNI()
05-13 22:38:33.358 24558 24558 D hidapi  : Initializing Bluetooth
05-13 22:38:33.358 24558 24558 D hidapi  : Couldn't initialize Bluetooth, missing android.permission.BLUETOOTH
05-13 22:38:33.364 24558 24558 V PythonActivity: Setting env vars for start.c and Python to use
05-13 22:38:33.364 24558 24558 V PythonActivity: Access to our meta-data...
05-13 22:38:33.366 24558 24558 I PythonActivity: Surface will NOT be transparent
05-13 22:38:33.366 24558 24558 V PythonActivity: onResume()
05-13 22:38:33.366 24558 24558 V SDL     : onResume()
05-13 22:38:33.369 24558 24591 D HiTouch_PressGestureDetector: onAttached, package=id.allasca.migbot, windowType=1, mHiTouchRestricted=false
05-13 22:38:33.376 24558 24586 I iGraphics: [0020080c] pn: id.allasca.migbot, p: 24558
05-13 22:38:33.376 24558 24586 I iGraphics: [0030050c] PV 10
05-13 22:38:33.376 24558 24586 I iGraphics: [0030050c] no element 'igfx'
05-13 22:38:33.377 24558 24586 I iGraphics: [0030050c] LoadCloudParams lib file success.
05-13 22:38:33.377 24558 24586 E Parcel  : Reading a NULL string not supported here.
05-13 22:38:33.379 24558 24558 V SDL     : surfaceCreated()
05-13 22:38:33.379 24558 24558 V SDL     : surfaceChanged()
05-13 22:38:33.379 24558 24558 V SDL     : pixel format RGB_565
05-13 22:38:33.379 24558 24558 V SDL     : Window size: 1080x2147
05-13 22:38:33.379 24558 24558 V SDL     : Device size: 1080x2340
05-13 22:38:33.380 24558 24558 D SensorManager: 0xd9c66520 addFd fd=90
05-13 22:38:33.382 24558 24558 V SDL     : nativeResume()
05-13 22:38:33.382 24558 24605 V SDL     : Running main function SDL_main from library /data/app/id.allasca.migbot-wZPj0l5RP1P1dEcyXLpQHQ==/lib/arm/libmain.so
05-13 22:38:33.382 24558 24605 V PythonActivity: appConfirmedActive() -> preparing loading screen removal
05-13 22:38:33.382 24558 24605 V SDL     : nativeRunMain()
05-13 22:38:33.383 24558 24605 I python  : Initializing Python for Android
05-13 22:38:33.383 24558 24605 I python  : Setting additional env vars from p4a_env_vars.txt
05-13 22:38:33.383 24558 24605 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
05-13 22:38:33.383 24558 24605 I python  : /data/user/0/id.allasca.migbot/files/app
05-13 22:38:33.383 24558 24605 I python  : Preparing to initialize python
05-13 22:38:33.383 24558 24605 I python  : _python_bundle dir exists
05-13 22:38:33.383 24558 24605 I python  : calculated paths to be...
05-13 22:38:33.383 24558 24605 I python  : /data/user/0/id.allasca.migbot/files/app/_python_bundle/stdlib.zip:/data/user/0/id.allasca.migbot/files/app/_python_bundle/modules
05-13 22:38:33.383 24558 24605 I python  : set wchar paths...
05-13 22:38:33.387 24558 24586 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
05-13 22:38:33.391 24558 24586 W Gralloc3: mapper 3.x is not supported
05-13 22:38:33.408 24558 24605 I python  : Initialized python
05-13 22:38:33.408 24558 24605 I python  : AND: Init threads
05-13 22:38:33.409 24558 24605 I python  : testing python print redirection
05-13 22:38:33.409 24558 24605 I python  : Android path ['.', '/data/user/0/id.allasca.migbot/files/app/_python_bundle/stdlib.zip', '/data/user/0/id.allasca.migbot/files/app/_python_bundle/modules', '/data/user/0/id.allasca.migbot/files/app/_python_bundle/site-packages']
05-13 22:38:33.409 24558 24605 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'ANDROID_RUNTIME_ROOT': '/apex/com.android.runtime', 'ANDROID_TZDATA_ROOT': '/apex/com.android.tzdata', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/featurelayer-widget.jar:/system/framework/hwEmui.jar:/system/framework/hwPartBasicplatform.jar:/system/framework/hwTelephony-common.jar:/system/framework/hwPartTelephony.jar:/system/framework/hwPartTelephonyVSim.jar:/system/framework/hwPartTelephonyCust.jar:/system/framework/hwPartSecurity.jar:/system/framework/hwIms-common.jar:/system/framework/hwPartMedia.jar:/system/framework/hwPartConnectivity.jar:/system/framework/hwPartPowerOffice.jar:/system/framework/hwframework.jar:/system/framework/com.huawei.nfc.jar:/system/framework/org.ifaa.android.manager.jar:/system/framework/hwperf.jar:/system/framework/hwaps.jar:/system/framework/hwcustEmui.jar:/system/framework/hwcustframework.jar:/system/framework/servicehost.jar:/system/framework/hwcustIms-common.jar:/system/framework/hwcustTelephony-common.jar:/system/framework/hwIAwareAL.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar', 'DEX2OATBOOTCLASSPATH': '/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/featurelayer-widget.jar:/system/framework/hwEmui.jar:/system/framework/hwPartBasicplatform.jar:/system/framework/hwTelephony-common.jar:/system/framework/hwPartTelephony.jar:/system/framework/hwPartTelephonyVSim.jar:/system/framework/hwPartTelephonyCust.jar:/system/framework/hwPartSecurity.jar:/system/framework/hwIms-common.jar:/system/framework/hwPartMedia.jar:/system/framework/hwPartConnectivity.jar:/system/framework/hwPartPowerOffice.jar:/system/framework/hwframework.jar:/system/framework/com.huawei.nfc.jar:/system/framework/org.ifaa.android.manager.jar:/system/framework/hwperf.jar:/system/framework/hwaps.jar:/system/framework/hwcustEmui.jar:/system/framework/hwcustframework.jar:/system/framework/servicehost.jar:/system/framework/hwcustIms-common.jar:/system/framework/hwcustTelephony-common.jar:/system/framework/hwIAwareAL.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar:/system/framework/hwServices.jar:/system/framework/hwWifi-service.jar:/system/framework/hwcustServices.jar:/system/framework/hwcustwifi-service.jar', 'DOWNLOAD_CACHE': '/data/cache', 'OEM_ROOT': '/hw_product/hw_oem/VOG-L29', 'ODM_PRODUCT': '/odm/hw_odm/VOG-L29', 'CUST_POLICY_DIRS': '/system/emui/base:/system/emui/oversea:/vendor/etc:/odm/etc:/odm/hw_odm/VOG-L29:/hw_product/etc:/hw_product/region_comm/oversea:/preas/oversea:/hw_product/hw_oem/VOG-L29:/preload/VOG-L29/channel/id:/cust/global:/cust/hw/spcseas:/version/cust/channel/id:/hw_product/special_cust/VOG-L29/hw/spcseas:/hw_product/special_cust/VOG-L29/channel/id:/version/special_cust/VOG-L29
05-13 22:38:33.409 24558 24605 I python  : Android kivy bootstrap done. __name__ is __main__
05-13 22:38:33.409 24558 24605 I python  : AND: Ran string
05-13 22:38:33.409 24558 24605 I python  : Run user program, change dir and execute entrypoint
05-13 22:38:33.420 24558 24586 E         : APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils
05-13 22:38:33.420 24558 24586 D         : APS:importExternalFunctions OK
05-13 22:38:33.422 24558 24558 I HwViewRootImpl: removeInvalidNode jank list is null
05-13 22:38:33.434 24558 24558 V SDL     : onWindowFocusChanged(): true
05-13 22:38:33.465 24558 24605 I python  :  Traceback (most recent call last):
05-13 22:38:33.466 24558 24605 I python  :    File "/home/allasca/PycharmProjects/migbot/venv/.buildozer/android/app/main.py", line 1, in <module>
05-13 22:38:33.466 24558 24605 I python  :    File "/home/allasca/PycharmProjects/migbot/venv/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/migbot/kivy/__init__.py", line 351, in <module>
05-13 22:38:33.466 24558 24605 I python  :  PermissionError: [Errno 13] Permission denied: '/data/.kivy'
05-13 22:38:33.466 24558 24605 I python  : Python for android ended.
05-13 22:38:33.477 24558 24605 E libc++abi: terminating
05-13 22:38:33.477 24558 24605 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24605 (SDLThread), pid 24558 (.allasca.migbot)
05-13 22:38:33.509 24558 24582 I .allasca.migbo: QarthPatchMonintor::CheckNotifyEvent after read, length = -1
```

**Comment by Julian-O** [comment]
Closed as a solved by https://github.com/kivy/kivy/issues/4777
