### ISSUE TITLE
Build failed for Numpy

### ISSUE THREAD

**Issue by khertan** [kivy/python-for-android#1158]
```
[INFO]:    Unpacking numpy for armeabi-v7a
[INFO]:    -> running basename http://pypi.python.org/packages/source/n/numpy/...(and 18 more)
[INFO]:    -> directory context /home/khertan/Projects/ChronoMonitoring/.buildozer/android/platform/build/build/other_builds/numpy/armeabi-v7a
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/khertan/Projects/ChronoMonitoring/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 916, in <module>
    main()
  File "/home/khertan/Projects/ChronoMonitoring/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 913, in main
    ToolchainCL()
  File "/home/khertan/Projects/ChronoMonitoring/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 514, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/khertan/Projects/ChronoMonitoring/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/khertan/Projects/ChronoMonitoring/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 192, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 558, in build_recipes
  File "pythonforandroid/recipe.py", line 550, in prepare_build_dir
  File "pythonforandroid/recipe.py", line 452, in unpack
  File "/home/khertan/.local/lib/python2.7/site-packages/sh.py", line 1245, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/khertan/.local/lib/python2.7/site-packages/sh.py", line 633, in __init__
    self.wait()
  File "/home/khertan/.local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/khertan/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: <exception str() failed>
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=chronomonitoring --bootstrap=sdl2 --requirements=git+https://github.com/khertan/plyer.git,kivy,requests,openssl,numpy,certifi,log4mongo,slack_log_handler,dropbox,setuptools --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/khertan/Projects/ChronoMonitoring/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

The pypi python server return : error 403 : SSL is required. So build failed with an empty archive that can t be extracted.

**Comment by ZhangKuixun** [comment]
怎样修复的？
