### ISSUE TITLE
Error Pythonforandroid.toolchain -m

### ISSUE THREAD

**Issue by suyog24** [kivy/python-for-android#1196]
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10,<1.12.5" "jinja2" "six"'
# Cwd None
# Apache ANT found at /home/kivy/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/kivy/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/kivy/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=mySuapp --bootstrap=sdl2 --requirements=kivy,python --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/testingWindows/.buildozer/android/platform/build'
# Cwd /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found multiple valid dependency orders:
[INFO]:        ['hostpython2', u'python', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:        ['hostpython3crystax', u'python', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:        ['hostpython2', 'pygame_bootstrap_components', u'python', 'python2', 'sdl', 'six', 'pygame', 'pyjnius', u'kivy']
[INFO]:    Using the first of these: ['hostpython2', u'python', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name mySuapp and recipes (kivy, python)
[INFO]:    Dist will also contain modules (python) installed from pip
[INFO]:    -> running cp -r /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master/pythonforandroid/bootstraps/sdl2/build /home/kivy/testingWind...(and 80 more)
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    The requirements (python) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> running basename https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    hostpython2 download already cached, skipping
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    sdl2_image download already cached, skipping
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
            [INFO]:    sdl2_mixer download already cached, skipping                                                                                                                                 
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/python2
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/python2
[INFO]:    -> running basename https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    python2 download already cached, skipping
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
           working: SDL2-2.0[INFO]:    sdl2 download already cached, skipping                                                                                                                       
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/six
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    six download already cached, skipping
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
                                             [INFO]:    pyjnius download already cached, skipping                                                                                                   
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/kivy/testingWindows/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.10.0.zip
[INFO]:    kivy download already cached, skipping
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop
[INFO]:    hostpython2 is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
           working: SDL2_image-2.0.1.tar.gz                  [INFO]:    -> directory context /home/kivy/testingWindows/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/kivy/testingWindows/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 559, in build_recipes
  File "pythonforandroid/recipe.py", line 520, in prepare_build_dir
  File "pythonforandroid/recipe.py", line 422, in unpack
  File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 1245, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 633, in __init__
    self.wait()
  File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2
**# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=mySuapp --bootstrap=sdl2 --requirements=kivy,python --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/testingWindows/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2**

**Comment by suyog24** [comment]
Resolved. 
But application crashes when clicked to open on android phone Galaxy s5

**Comment by AndreMiras** [comment]
@suyog24 can you share the crash report from the adb shell?
