### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'/Users/gauravgupta/kivy/.buildozer/android/platform/build/dists/myellipse/build/outputs/apk/myellipse-debug.apk'

### ISSUE THREAD

**Issue by gauravgupta11** [kivy/python-for-android#1216]
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.33', 'console_scripts', 'buildozer')()
  File "/Library/Python/2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 91, in run_commands
    func(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 103, in cmd_debug
    self.buildozer.build()
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/Library/Python/2.7/site-packages/buildozer/targets/android.py", line 808, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/gauravgupta/kivy/.buildozer/android/platform/build/dists/myellipse/build/outputs/apk/myellipse-debug.apk'

**Comment by tito** [comment]
Why i closed it: you don't provide context, full logs, etc. Just copy paste of what bother you and what seems important to you. So obviously we can't help.

**Comment by AndreMiras** [comment]
Agreed we're missing some context, but I'll link it to https://github.com/kivy/buildozer/issues/312 nevertheless because it looks like closely related.
