### ISSUE TITLE
Android build issues: raise CommandNotFound(path)

### ISSUE THREAD

**Issue by Neustart** [kivy/python-for-android#1228]
I've tried to build some application on another PC and faced strange error. I didn't face it before on my other PCs
What it could be ?

```
sudo  /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=Electrum --bootstrap=sdl2 --requirements=python3crystax,android,openssl,plyer,kivy==master --ndk-dir=/home/kirill/crystax-ndk-10.3.2 --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kirill/Projects/electrum/.buildozer/android/platform/build
[INFO]:    Recipe kivy: version "master" requested
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found possible SDK dirs in buildozer dir: android-sdk-20
[INFO]:    Will attempt to use SDK at /home/kirill/.buildozer/android/platform/android-sdk-20
[WARNING]: This SDK lookup is intended for debug only, if you use python-for-android much you should probably maintain your own SDK download.
[INFO]:    Android API target was not set manually, using the default of 15
[INFO]:    Available Android APIs are (8, 14, 15, 19, 20)
[INFO]:    Requested API target 15 is available, continuing.
[INFO]:    Getting NDK dir from from user argument
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Got Android NDK version from the NDK dir: it is 10.3.2
[INFO]:    Using Crystax NDK 10.3.2
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3crystax', 'openssl', 'plyer', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'android', 'pyjnius', 'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name Electrum and recipes (python3crystax, android, openssl, plyer, kivy)
[INFO]:    Dist will also contain modules (plyer) installed from pip
[INFO]:    -> running cp -r /usr/local/lib/python3.6...(and 168 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Recipe build order is ['hostpython3crystax', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'android', 'pyjnius', 'kivy']
[INFO]:    The requirements (plyer) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3crystax
[INFO]:    Skipping hostpython3crystax download as no URL is set
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 60 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/openssl
[INFO]:    -> running basename https://www.openssl.or...(and 30 more)
[INFO]:    openssl download already cached, skipping                           
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 63 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping                        
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 63 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping                        
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 61 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping                          
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading python3crystax
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 67 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/python3crystax
[INFO]:    -> running basename 
[INFO]:    -> running rm -f .mark-
[INFO]:    -> running touch .mark-
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 57 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    sdl2 download already cached, skipping                              
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 56 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping                               
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 60 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    pyjnius download already cached, skipping                           
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/kirill/Projects...(and 57 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    kivy download already cached, skipping                              
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3crystax for armeabi-v7a
[INFO]:    Skipping hostpython3crystax unpack as no URL is set
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.or...(and 30 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Unpacking python3crystax for armeabi-v7a
[INFO]:    -> running basename 
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a
[INFO]:    python3crystax is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    -> running rm -rf /home/kirill/Projects/e...(and 108 more)
[INFO]:    -> running cp -a /usr/local/lib/python3.6...(and 183 more)
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/other_builds/kivy-python3crystax-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3crystax for armeabi-v7a
[INFO]:    hostpython3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3crystax for armeabi-v7a
[INFO]:    python3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/other_builds/android-python3crystax-sdl2/armeabi-v7a/android
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3crystax for armeabi-v7a
[INFO]:    Building openssl for armeabi-v7a
[INFO]:    openssl said it is already built, skipping
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building python3crystax for armeabi-v7a
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /home/kirill/Projects/electrum/gui/kivy        
[INFO]:    Building six for armeabi-v7a
[INFO]:    six apparently isn't already in site-packages
[INFO]:    Installing six into site-packages
[INFO]:    -> directory context /home/kirill/Projects/electrum/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a/six
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/build.py", line 573, in build_recipes
    recipe.build_arch(arch)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/recipe.py", line 775, in build_arch
    self.install_python_package(arch)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/recipe.py", line 789, in install_python_package
    hostpython = sh.Command(self.hostpython_location)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1028, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: python3.5

```
Thanks

**Comment by inclement** [comment]
python3crystax uses the local python for the build, but this has to be the same version. It looks like you only have python3.6, but python3crystax is defaulting to 3.5. It should work if you tell python3crystax to use python 3.6, by changing your requirements to read `python3crystax==3.6`.

**Comment by Neustart** [comment]
thank you, that's works
