### ISSUE TITLE
Failed to build application: 'WindowInfoX11' is not a type identifier

### ISSUE THREAD

**Issue by Neustart** [kivy/python-for-android#1230]
Hi, I am not able to build my application using lates Cython version (0.27.3)
Does somebody have any idea how to fix that ? 
thanks 
```

Cython check avoided.
Using this graphics system: OpenGL ES 2
WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

b"Package sdl2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `sdl2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'sdl2' found\nPackage SDL2_ttf was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_ttf.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_ttf' found\nPackage SDL2_image was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_image.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_image' found\nPackage SDL2_mixer was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_mixer.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_mixer' found\n"

SDL2: found SDL header at /home/kirill/Projects/SI-Crypto/Electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni/SDL/include/SDL.h
SDL2: found SDL_mixer header at /home/kirill/Projects/SI-Crypto/Electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni/SDL2_mixer/SDL_mixer.h
SDL2: found SDL_ttf header at /home/kirill/Projects/SI-Crypto/Electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni/SDL2_ttf/SDL_ttf.h
SDL2: found SDL_image header at /home/kirill/Projects/SI-Crypto/Electrum/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni/SDL2_image/SDL_image.h
 /usr/local/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
   warnings.warn(msg)
 /usr/local/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'
   warnings.warn(msg)
 /usr/local/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'dependency_links'
   warnings.warn(msg)
running build_ext
Build configuration is:
 * use_rpi = 0
 * use_mali = 0
 * use_egl = 0
 * use_opengl_es2 = 1
 * use_opengl_mock = 0
 * use_sdl2 = 1
 * use_ios = 0
 * use_mesagl = 0
 * use_x11 = 0
 * use_wayland = 0
 * use_gstreamer = 0
 * use_avfoundation = 0
 * use_osx_frameworks = 0
 * debug_gl = 0
 * debug = False
 error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.5/kivy/include/config.h'


  STDERR:


[INFO]:    kivy first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize kivy/_clock.pyx
[INFO]:    -> running cython ./kivy/_clock.pyx
[INFO]:    Cythonize kivy/properties.pyx
[INFO]:    -> running cython ./kivy/properties.pyx
[INFO]:    Cythonize kivy/weakproxy.pyx
[INFO]:    -> running cython ./kivy/weakproxy.pyx
[INFO]:    Cythonize kivy/_event.pyx
[INFO]:    -> running cython ./kivy/_event.pyx
[INFO]:    Cythonize kivy/lib/gstplayer/_gstplayer.pyx
[INFO]:    -> running cython ./kivy/lib/gstplayer/_gstplayer.pyx
[INFO]:    Cythonize kivy/lib/vidcore_lite/egl.pyx
[INFO]:    -> running cython ./kivy/lib/vidcore_lite/egl.pyx
[INFO]:    Cythonize kivy/lib/vidcore_lite/bcm.pyx
[INFO]:    -> running cython ./kivy/lib/vidcore_lite/bcm.pyx
[INFO]:    Cythonize kivy/graphics/texture.pyx
[INFO]:    -> running cython ./kivy/graphics/texture.pyx
[INFO]:    Cythonize kivy/graphics/gl_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/gl_instructions.pyx
[INFO]:    Cythonize kivy/graphics/context_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/context_instructions.pyx
[INFO]:    Cythonize kivy/graphics/svg.pyx
[INFO]:    -> running cython ./kivy/graphics/svg.pyx
[INFO]:    Cythonize kivy/graphics/vertex_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/vertex_instructions.pyx
[INFO]:    Cythonize kivy/graphics/stencil_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/stencil_instructions.pyx
[INFO]:    Cythonize kivy/graphics/cgl.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl.pyx
[INFO]:    Cythonize kivy/graphics/vbo.pyx
[INFO]:    -> running cython ./kivy/graphics/vbo.pyx
[INFO]:    Cythonize kivy/graphics/instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/instructions.pyx
[INFO]:    Cythonize kivy/graphics/shader.pyx
[INFO]:    -> running cython ./kivy/graphics/shader.pyx
[INFO]:    Cythonize kivy/graphics/context.pyx
[INFO]:    -> running cython ./kivy/graphics/context.pyx
[INFO]:    Cythonize kivy/graphics/opengl_utils.pyx
[INFO]:    -> running cython ./kivy/graphics/opengl_utils.pyx
[INFO]:    Cythonize kivy/graphics/scissor_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/scissor_instructions.pyx
[INFO]:    Cythonize kivy/graphics/vertex.pyx
[INFO]:    -> running cython ./kivy/graphics/vertex.pyx
[INFO]:    Cythonize kivy/graphics/buffer.pyx
[INFO]:    -> running cython ./kivy/graphics/buffer.pyx
[INFO]:    Cythonize kivy/graphics/fbo.pyx
[INFO]:    -> running cython ./kivy/graphics/fbo.pyx
[INFO]:    Cythonize kivy/graphics/opengl.pyx
[INFO]:    -> running cython ./kivy/graphics/opengl.pyx
[INFO]:    Cythonize kivy/graphics/compiler.pyx
[INFO]:    -> running cython ./kivy/graphics/compiler.pyx
[INFO]:    Cythonize kivy/graphics/transformation.pyx
[INFO]:    -> running cython ./kivy/graphics/transformation.pyx
[INFO]:    Cythonize kivy/graphics/tesselator.pyx
[INFO]:    -> running cython ./kivy/graphics/tesselator.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_debug.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_debug.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_sdl2.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_sdl2.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_glew.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_glew.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_gl.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_gl.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_mock.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_mock.pyx
[INFO]:    Cythonize kivy/core/text/_text_sdl2.pyx
[INFO]:    -> running cython ./kivy/core/text/_text_sdl2.pyx
[INFO]:    Cythonize kivy/core/text/text_layout.pyx
[INFO]:    -> running cython ./kivy/core/text/text_layout.pyx
[INFO]:    Cythonize kivy/core/clipboard/_clipboard_sdl2.pyx
[INFO]:    -> running cython ./kivy/core/clipboard/_clipboard_sdl2.pyx
[INFO]:    Cythonize kivy/core/audio/audio_sdl2.pyx
[INFO]:    -> running cython ./kivy/core/audio/audio_sdl2.pyx
[INFO]:    Cythonize kivy/core/image/img_imageio.pyx
[INFO]:    -> running cython ./kivy/core/image/img_imageio.pyx
[INFO]:    Cythonize kivy/core/image/_img_sdl2.pyx
[INFO]:    -> running cython ./kivy/core/image/_img_sdl2.pyx
[INFO]:    Cythonize kivy/core/camera/camera_avfoundation.pyx
[INFO]:    -> running cython ./kivy/core/camera/camera_avfoundation.pyx
[INFO]:    Cythonize kivy/core/window/window_x11.pyx
[INFO]:    -> running cython ./kivy/core/window/window_x11.pyx
Exception in thread background thread for pid 31858:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.5/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.5/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/cython ./kivy/core/window/window_x11.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.config import Config
from kivy.base import stopTouchApp, EventLoop, ExceptionManager
from kivy.utils import platform
from os import environ

from window_info cimport WindowInfoX11
^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:18:0: 'kivy/core/window/window_info/WindowInfoX11.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern int x11_create_window(int width, int height, int x, int y, \
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:69:12: 'Display' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
cdef extern Window x11_get_window()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:70:12: 'Window' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.system_size = size
        super(WindowX11, self).create_window()
        self._unbind_create_window()

    def get_window_info(self):
        cdef WindowInfoX11 window_info = WindowInfoX11()
            ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:221:13: 'WindowInfoX11' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.system_size = size
        super(WindowX11, self).create_window()
        self._unbind_create_window()

    def get_window_info(self):
        cdef WindowInfoX11 window_info = WindowInfoX11()
                                        ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:221:41: 'WindowInfoX11' is not a constant, variable or function identifier


  STDERR:


Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/opt/python-for-android/pythonforandroid/build.py", line 574, in build_recipes
    recipe.build_arch(arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 928, in build_arch
    self.build_cython_components(arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 963, in build_cython_components
    self.cythonize_build(env=env)
  File "/opt/python-for-android/pythonforandroid/recipes/kivy/__init__.py", line 18, in cythonize_build
    super(KivyRecipe, self).cythonize_build(env, build_dir=build_dir)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 1008, in cythonize_build
    self.cythonize_file(env, build_dir, join(root, filename))
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 999, in cythonize_file
    shprint(cython_command, filename, *self.cython_args, _env=cyenv)
  File "/opt/python-for-android/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/usr/local/lib/python3.5/site-packages/sh.py", line 720, in next
    self.wait()
  File "/usr/local/lib/python3.5/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.5/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/cython ./kivy/core/window/window_x11.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.config import Config
from kivy.base import stopTouchApp, EventLoop, ExceptionManager
from kivy.utils import platform
from os import environ

from window_info cimport WindowInfoX11
^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:18:0: 'kivy/core/window/window_info/WindowInfoX11.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern int x11_create_window(int width, int height, int x, int y, \
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:69:12: 'Display' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
cdef extern Window x11_get_window()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:70:12: 'Window' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.system_size = size
        super(WindowX11, self).create_window()
        self._unbind_create_window()

    def get_window_info(self):
        cdef WindowInfoX11 window_info = WindowInfoX11()
            ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:221:13: 'WindowInfoX11' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.system_size = size
        super(WindowX11, self).create_window()
        self._unbind_create_window()

    def get_window_info(self):
        cdef WindowInfoX11 window_info = WindowInfoX11()
                                        ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:221:41: 'WindowInfoX11' is not a constant, variable or function identifier


  STDERR:

b'\x1b[0m\r           working:  * use_rpi = 0                                                     \x1b[0m\r           working:  * use_mali = 0                                                    \x1b[0m\r           working:  * use_egl = 0                                                     \x1b[0m\r           working:  * use_opengl_es2 = 1                                              'b'\x1b[0m\r           working:  * use_opengl_mock = 0                                             'b'\x1b[0m\r           working:  * use_sdl2 = 1                                                    'b'\x1b[0m\r           working:  * use_ios = 0                                                     'b'\x1b[0m\r           working:  * use_mesagl = 0                                                  'b'\x1b[0m\r           working:  * use_x11 = 0                                                     'b'\x1b[0m\r           working:  * use_wayland = 0                                                 'b'\x1b[0m\r           working:  * use_gstreamer = 0                                               'b'\x1b[0m\r           working:  * use_avfoundation = 0                                            'b'\x1b[0m\r           working:  * use_osx_frameworks = 0                                          'b'\x1b[0m\r           working:  * debug_gl = 0                                                    'b'\x1b[0m\r           working:  * debug = False                                                   'b"\x1b[0m\r           working:  error: [Errno 2] No such file or directory: 'buil...(and 45 more) "b'\x1b[0m\r                                                                                       \r'b'\n\x1b[0m\r           working: Error compiling Cython file:                                       \x1b[0m\r           working: ------------------------------------------------------------       'b'\x1b[0m\r           working: ...                                                                'b'\x1b[0m\r           working: from kivy.config import Config                                     'b'\x1b[0m\r           working: from kivy.base import stopTouchApp, EventLoop, ExceptionManager    'b'\x1b[0m\r           working: from kivy.utils import platform                                    'b'\x1b[0m\r           working: from os import environ                                             'b'\x1b[0m\r           working: from window_info cimport WindowInfoX11                             'b'\x1b[0m\r           working: ^                                                                  'b'\x1b[0m\r           working: ------------------------------------------------------------       'b"\x1b[0m\r           working: kivy/core/window/window_x11.pyx:18:0: 'kivy/core/w...(and 46 more) "b'\x1b[0m\r           working: Error compiling Cython file:                                       'b'\x1b[0m\r           working: ------------------------------------------------------------       'b'\x1b[0m\r           working: ...                                                                'b'\x1b[0m\r           working: cdef extern int x11_create_window(int width, int h...(and 22 more) 'b'\x1b[0m\r           working:         int resizable, int fullscreen, int border,...(and 34 more) 'b'\x1b[0m\r           working: cdef extern void x11_gl_swap()                                     'b'\x1b[0m\r           working: cdef extern void x11_set_title(char *title)                        'b'\x1b[0m\r           working: cdef extern int x11_idle()                                         'b'\x1b[0m\r           working: cdef extern Display *x11_get_display()                             'b'\x1b[0m\r           working:            ^                                                       'b'\x1b[0m\r           working: ------------------------------------------------------------       'b"\x1b[0m\r           working: kivy/core/window/window_x11.pyx:69:12: 'Display' i...(and 23 more) "b'\x1b[0m\r           working: Error compiling Cython file:                                       'b'\x1b[0m\r           working: ------------------------------------------------------------       'b'\x1b[0m\r           working: ...                                                                'b'\x1b[0m\r           working:         int resizable, int fullscreen, int border,...(and 34 more) 'b'\x1b[0m\r           working: cdef extern void x11_gl_swap()                                     'b'\x1b[0m\r           working: cdef extern void x11_set_title(char *title)                        'b'\x1b[0m\r           working: cdef extern int x11_idle()                                         'b'\x1b[0m\r           working: cdef extern Display *x11_get_display()                             'b'\x1b[0m\r           working: cdef extern Window x11_get_window()                                'b'\x1b[0m\r           working:            ^                                                       'b'\x1b[0m\r           working: ------------------------------------------------------------       'b"\x1b[0m\r           working: kivy/core/window/window_x11.pyx:70:12: 'Window' is...(and 22 more) "b'\x1b[0m\r           working: Error compiling Cython file:                                       'b'\x1b[0m\r           working: ------------------------------------------------------------       'b'\x1b[0m\r           working: ...                                                                'b'\x1b[0m\r           working:         self.system_size = size                                    'b'\x1b[0m\r           working:         super(WindowX11, self).create_window()                     'b'\x1b[0m\r           working:         self._unbind_create_window()                               'b'\x1b[0m\r           working:     def get_window_info(self):                                     'b'\x1b[0m\r           working:         cdef WindowInfoX11 window_info = WindowInfoX11()           'b'\x1b[0m\r           working:             ^                                                      'b'\x1b[0m\r           working: ------------------------------------------------------------       'b"\x1b[0m\r           working: kivy/core/window/window_x11.pyx:221:13: 'WindowInf...(and 30 more) "b'\x1b[0m\r           working: Error compiling Cython file:                                       \x1b[0m\r           working: ------------------------------------------------------------       'b'\x1b[0m\r           working: ...                                                                'b'\x1b[0m\r           working:         self.system_size = size                                    'b'\x1b[0m\r           working:         super(WindowX11, self).create_window()                     'b'\x1b[0m\r           working:         self._unbind_create_window()                               'b'\x1b[0m\r           working:     def get_window_info(self):                                     'b'\x1b[0m\r           working:         cdef WindowInfoX11 window_info = WindowInfoX11()           'b'\x1b[0m\r           working:                                         ^                          'b'\x1b[0m\r           working: ------------------------------------------------------------       'b"\x1b[0m\r           working: kivy/core/window/window_x11.pyx:221:41: 'WindowIn...(and 57 more)  "b'\x1b[0m\r                                                                                       \r'# Command failed: /usr/local/bin/python3 -m pythonforandroid.toolchain create --dist_name=Electrum --bootstrap=sdl2 --requirements=python3crystax,android,openssl,plyer,kivy==master --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kirill/Projects/SI-Crypto/Electrum/.buildozer/android/platform/build

```

**Comment by Neustart** [comment]
seems like this is a bug: https://stackoverflow.com/questions/48477845/x11-importerror-no-module-named-kivy-core-window-window-x11
