### ISSUE TITLE
sh.CommandNotFound: ndk_build

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/python-for-android#1292]
I building the project in a virtual machine... Get an errro message:

```python
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3crystax for armeabi-v7a
[INFO]:    hostpython3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3crystax for armeabi-v7a
[INFO]:    python3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3crystax for armeabi-v7a
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building python3crystax for armeabi-v7a
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/bootstrap_builds/sdl2_gradle-python3crystax/jni

Traceback (most recent call last):
  File "setup.py", line 77, in <module>
    'quotessaints/libs/applibs/requests/packages/idna': ['*.py'],
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/bdistapk.py", line 83, in run
    main()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 573, in build_recipes
    recipe.build_arch(arch)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipes/sdl2/__init__.py", line 32, in build_arch
    shprint(sh.ndk_build, "V=1", _env=env)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 3054, in __getattr__
    return self.__env[name]
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2931, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: ndk_build```

Version sh module - 1.12.4

**Comment by omar-smile** [comment]
I got the same error, did u find a solution?

**Comment by AndreMiras** [comment]
Hi @omar-smile can you also share your entire build log with log level 2 please? Also share your `buildozer.spec` and any relevant info, Linux distribution...

**Comment by omar-smile** [comment]
now I can't remember in which trial I got that error as I tried on many OS and many tools, 

however now i'm able to deploy and run my code  I'm using a virtualbox downloaded from bulidozer site and the command: `buildozer android_old debug deploy` and my buildozer.spec attached
[buildozer copy.txt](https://github.com/kivy/python-for-android/files/2195715/buildozer.copy.txt)

**Comment by Zen-CODE** [comment]
For me, this turned out to be a permissions issue. After a lot of chmodding one file at a time, this solved it this way. From inside the "crystax-ndk-10.3.2" folder.
```
    $ chmod +x -R *
```
Would be interested to know if that worked for you?

**Comment by inclement** [comment]
Closing as stale, I haven't seen any issues like this recently and I think it's likely been fixed or mitigated.
