### ISSUE TITLE
buildozer error: no module named kivy

### ISSUE THREAD

**Issue by thegameguy** [kivy/python-for-android#1354]
Hi, I'm using p4a master, cython==0.25, kivy==1.10.1 and python 2.7, I keep getting an error while debugging an apk, 'no module named kivy'.  

Details of error are in the log below. thanks! 
log: https://pastebin.com/U2UvzsKE 
buildozer.spec: https://pastebin.com/Qi2JGVDG

**Comment by AndreMiras** [comment]
Relevant part of the logs:
```
[INFO]:    Installing kivent_core into site-packages
[INFO]:    -> directory context /home/vapo/test5/.buildozer/android/platform/build/build/other_builds/kivent_core-python2/armeabi-v7a/kivent_core/modules/core
[INFO]:    -> running hostpython setup.py install -...(and 131 more)
Exception in thread background thread for pid 3847:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vapo/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/vapo/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/vapo/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:
 
  RAN: /home/vapo/test5/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2/hostpython setup.py install -O2 --root=/home/vapo/test5/.buildozer/android/platform/build/build/python-installs/myapp2 --install-lib=lib/python2.7/site-packages
 
  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import kivy
ImportError: No module named kivy
```
I've never played with `kivent_core` in the requirements. But yes as of today, it seems like your `hostpython2` has a requirement over `kivy` here: https://github.com/kivy/kivent/blob/29dba81/modules/core/setup.py#L4

**Comment by thegameguy** [comment]
Thanks for the reply what do you suggest I should do, I have kivy installed on the system, I have been building apks without kivent installed on linux side.

**Comment by thegameguy** [comment]
does it has to do with the recipes. I have touched the recipes with p4a that came with the kivent_core, kivent_cymunk and kivent_particles. The p4a master files has a recipes folder. A whole bunch of recipes has these three too. but there is just __init__.py files in them. The recipes i touched with p4a were manually downloaded from here: https://github.com/kivy/kivent/tree/29dba8181ad855e0aca181f6a9e5b3d12d5bb0ca/modules/recipes

**Comment by thegameguy** [comment]
found a solution suggested by Jacob!
is to copy kivy and cymunk installation folders from
/home/usermachine/test/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages
to
/home/usermachine/test/.buildozer/anroid/platform/build/build/other_builds/ hostpython2/desktop/hostpython2/lib/site-packages
note: the addressed may vary, basically we need to copy kivy and cymunk installations from python site packages to hostpython sitepackages.

**Comment by AndreMiras** [comment]
Glad you got it working, but it's still a bug right? I don't know if something could be done from the recipe.

**Comment by thegameguy** [comment]
yes true, if a recipe could shutil the folders from one site package to another.
