### ISSUE TITLE
cryptography + python3crystax fails

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1404]
### Versions

* Python: host Python 2/3, target python3crystax
* OS: Ubuntu 18.04
* Kivy: N/A
* Cython: 0.21

### Description

Building `cryptography` on `python3crystax` fails.
This is because the [cryptography recipe depends on enum34](https://github.com/kivy/python-for-android/blob/0eaad14/pythonforandroid/recipes/cryptography/__init__.py#L9).

### Command

```sh
python setup_testapp_python3.py apk --sdk-dir $ANDROID_SDK_HOME --ndk-dir $CRYSTAX_NDK_HOME --bootstrap sdl2 --requirements python3crystax,cryptography
```

### Logs
Here's a log extract, but basically it fails when building `enum34`:
```
[DEBUG]:        running install_scripts
[INFO]:    <- directory context /home/andre/workspace/python-for-android/testapps
[INFO]:    Building enum34 for armeabi-v7a
[INFO]:    enum apparently isn't already in site-packages
[INFO]:    Installing enum34 into site-packages
[INFO]:    -> directory context /home/andre/.local/share/python-for-android/build/other_builds/enum34-python3crystax/armeabi-v7a/enum34
[DEBUG]:   -> running hostpython setup.py install -O2 --root=/home/andre/.local/share/python-for-android/build/python-installs/bdisttest_python3 --install-lib=.
[DEBUG]:        Traceback (most recent call last):
[DEBUG]:          File "setup.py", line 3, in <module>
[DEBUG]:            import setuptools
[DEBUG]:          File "/home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/Lib/site-packages/setuptools/__init__.py", line 5, in <module>
[DEBUG]:            import distutils.core
[DEBUG]:          File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
[DEBUG]:            from distutils.dist import Distribution
[DEBUG]:          File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
[DEBUG]:            import re
[DEBUG]:          File "/usr/lib/python3.6/re.py", line 142, in <module>
[DEBUG]:            class RegexFlag(enum.IntFlag):
[DEBUG]:        AttributeError: module 'enum' has no attribute 'IntFlag'
[DEBUG]:        Error in sys.excepthook:
[DEBUG]:        Traceback (most recent call last):
[DEBUG]:          File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
[DEBUG]:            if not enabled():
[DEBUG]:          File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
[DEBUG]:            import re
[DEBUG]:          File "/usr/lib/python3.6/re.py", line 142, in <module>
[DEBUG]:            class RegexFlag(enum.IntFlag):
[DEBUG]:        AttributeError: module 'enum' has no attribute 'IntFlag'
[DEBUG]:
[DEBUG]:        Original exception was:
[DEBUG]:        Traceback (most recent call last):
[DEBUG]:          File "setup.py", line 3, in <module>
[DEBUG]:            import setuptools
[DEBUG]:          File "/home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/Lib/site-packages/setuptools/__init__.py", line 5, in <module>
[DEBUG]:            import distutils.core
[DEBUG]:          File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
[DEBUG]:            from distutils.dist import Distribution
[DEBUG]:          File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
[DEBUG]:            import re
[DEBUG]:          File "/usr/lib/python3.6/re.py", line 142, in <module>
[DEBUG]:            class RegexFlag(enum.IntFlag):
[DEBUG]:        AttributeError: module 'enum' has no attribute 'IntFlag'
Exception in thread background thread for pid 22263:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/andre/workspace/python-for-android/venv/local/lib/python2.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/andre/workspace/python-for-android/venv/local/lib/python2.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/andre/workspace/python-for-android/venv/local/lib/python2.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/andre/workspace/python-for-android/venv/local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:

  RAN: /home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/hostpython setup.py install -O2 --root=/home/andre/.local/share/python-for-android/build/python-installs/bdisttest_python3 --install-lib=.

  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import setuptools
  File "/home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/Lib/site-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
    from distutils.dist import Distribution
  File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

Original exception was:
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import setuptools
  File "/home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/Lib/site-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
    from distutils.dist import Distribution
  File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'


  STDERR:


Traceback (most recent call last):
  File "setup_testapp_python3.py", line 30, in <module>
    package_data={'testapp': ['*.py', '*.png']}
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/andre/workspace/python-for-android/pythonforandroid/bdistapk.py", line 81, in run
    main()
  File "/home/andre/workspace/python-for-android/pythonforandroid/toolchain.py", line 999, in main
    ToolchainCL()
  File "/home/andre/workspace/python-for-android/pythonforandroid/toolchain.py", line 532, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/andre/workspace/python-for-android/pythonforandroid/toolchain.py", line 145, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/andre/workspace/python-for-android/pythonforandroid/toolchain.py", line 189, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/andre/workspace/python-for-android/pythonforandroid/build.py", line 580, in build_recipes
    recipe.build_arch(arch)
  File "/home/andre/workspace/python-for-android/pythonforandroid/recipe.py", line 814, in build_arch
    self.install_python_package(arch)
  File "/home/andre/workspace/python-for-android/pythonforandroid/recipe.py", line 835, in install_python_package
    _env=hpenv, *self.setup_extra_args)
  File "/home/andre/workspace/python-for-android/pythonforandroid/logger.py", line 176, in shprint
    for line in output:
  File "/home/andre/workspace/python-for-android/venv/local/lib/python2.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/andre/workspace/python-for-android/venv/local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/andre/workspace/python-for-android/venv/local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/hostpython setup.py install -O2 --root=/home/andre/.local/share/python-for-android/build/python-installs/bdisttest_python3 --install-lib=.

  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import setuptools
  File "/home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/Lib/site-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
    from distutils.dist import Distribution
  File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

Original exception was:
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import setuptools
  File "/home/andre/.local/share/python-for-android/build/other_builds/hostpython3crystax/desktop/hostpython3crystax/Lib/site-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
    from distutils.dist import Distribution
  File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'


  STDERR:
```

**Comment by ysangkok** [comment]
Does it work with the new Python 3 recipe?

**Comment by AndreMiras** [comment]
I haven't played with it yet, feel free to give it a try, but this task is specifically about crystax.

**Comment by Huyston** [comment]
Some time ago I tried to build an App which needed to access https. I managed to fix these error by manually copying the files to the App folder and some other tricks. But, in the end, I figured that this is not possible because the python3crystax wasn't build with ssl support.
So I think you need either python2 or compile a python3 with ssl support for this to work.

**Comment by inclement** [comment]
Closing as stale, I believe this works now with the python3 recipe which is preferred over python3crystax. Feel free to reopen if the issue still occurs there.
