### ISSUE TITLE
p4a git master pyjnius build breaks

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1414]
### Versions

* Python: python 3.6+ on host and for running p4a, python3crystax as target
* OS: linux/ubuntu
* Kivy: not used
* Cython: not sure

### Description

p4a doesn't build right now with latest git master with pyjnius as a dependency:

```
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    Applying patch sdl2_jnienv_getter.patch
[DEBUG]:   -> running patch -t -d /root/.local/share/python-for-android/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /usr/local/lib/python3.6/dist-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch
[DEBUG]:   	patching file jnius/jnius_jvm_android.pxi
[DEBUG]:   	patching file setup.py
[DEBUG]:   	Hunk #1 FAILED at 53.
[DEBUG]:   	1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
Exception in thread background thread for pid 4243:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /root/.local/share/python-for-android/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /usr/local/lib/python3.6/dist-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej


  STDERR:


[INFO]:    STDOUT:
	patching file jnius/jnius_jvm_android.pxi	
patching file setup.py	
Hunk #1 FAILED at 53.	
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
[INFO]:    STDERR:
	
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 11, in <module>
    load_entry_point('python-for-android==0.6.0', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 999, in main
    ToolchainCL()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 532, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 145, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 189, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/build.py", line 573, in build_recipes
    recipe.apply_patches(arch)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/recipe.py", line 493, in apply_patches
    arch.arch)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/recipe.py", line 192, in apply_patch
    "-i", filename, _tail=10)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/logger.py", line 176, in shprint
    for line in output:
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 863, in next
    self.wait()
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /root/.local/share/python-for-android/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /usr/local/lib/python3.6/dist-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej


  STDERR:

Build failed.
```

### buildozer.spec

no buildozer used, but I would assume just putting pyjnius as a dependency is enough

### Logs
see above

**Comment by KeyWeeUsr** [comment]
Closed by #1417
