### ISSUE TITLE
Set the api level from 19 to 28 failed

### ISSUE THREAD

**Issue by intellign** [kivy/python-for-android#1482]
### Versions

* Python: 2.7
* OS: Ubuntu 17.06
* Kivy: 1.9.3

### Description

I tried compiling my code with the .spec changes from [](https://github.com/kivy/python-for-android/pull/1381), It seems to be a p4a error... 

```
  STDOUT:
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.    
jni/Android.mk:11: Extraneous text after `ifeq' directive
/home/kivy/.buildozer/android/platform/android-ndk-r17c/build/core/build-binary.mk:688: Android NDK: Module cjpeg depends on undefined modules: cutils    
/home/kivy/.buildozer/android/platform/android-ndk-r17c/build/core/build-binary.mk:701: *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=hoto --bootstrap=sdl2 --requirements=kivy==master,plyer,openssl,pil --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/kivy/Desktop/Hoto/.buildozer/android/platform/build"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
kivy@kivyvm:~/Desktop/Hoto$ 
```

I solved the above problem by setting APP_ALLOW_MISSING_DEPS=true in Application.mk file and by removing the word libcutils in jpeg/build-static.patch

### buildozer.spec

Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = Hoto

# (str) Package name
package.name = hoto

# (str) Package domain (needed for android/ios packaging)
package.domain = intellign

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,mp3, wav, zip, 3gp, TTF, ttf, otf, OTF

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 1.13

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy==master, plyer, openssl, pil

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
presplash.filename = %(source.dir)s/presplash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/appicon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = intellign

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (list) Permissions
android.permissions = INTERNET, ACCESS_WIFI_STATE,ACCESS_NETWORK_STATE, CAMERA

# (int) Android API to use
android.api = 28

# (int) Minimum API required
android.minapi = 21

# (int) Android SDK version to use
android.sdk = 24

# (str) Android NDK version to use
android.ndk = 17c

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path = "/home/kivy/Downloads/android-ndk-r17c/"
#android.arch = armeabi-v7a
p4a.branch = master
#p4a.source_dir = /home/kivy/Repos/python-for-android

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes = 

# (list) python-for-android whitelist
#android.p4a_whitelist =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Bootstrap to use for android builds (android_new only)
# android.bootstrap = sdl2

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar
#android.add_jars = %(source.dir)s/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
android.meta_data = com.google.android.gms.version=@integer/google_play_services_version

# (list) Android library project to add (will be added in the
# project.properties automatically.)
android.library_references =google-play-services_lib/

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
ish@ish-linux:~/Desktop/Hoto$ buildozer android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.18.10 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-9-oracle/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-9-oracle/bin/keytool
# Install platform
# Run "/usr/bin/python -m pip install -q --user 'appdirs' 'colorama>=0.3.3' 'jinja2' 'six'"
# Cwd None
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
# Apache ANT found at /home/ish/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/ish/.buildozer/android/platform/android-sdk-24
# Android NDK found at /home/ish/.buildozer/android/platform/android-ndk-r18b
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=hoto --bootstrap=sdl2 --requirements=kivy,plyer,openssl,pil --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/ish/Desktop/Hoto/.buildozer/android/platform/build"'
# Cwd /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (28)
[INFO]:    Requested API target 28 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r18b
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[WARNING]: Missing executable: autoconf is not installed
[WARNING]: Missing executable: automake is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found multiple valid dependency orders:
[INFO]:        ['hostpython2', 'jpeg', u'openssl', u'plyer', 'png', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', u'pil', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:        ['hostpython2', 'jpeg', u'openssl', u'plyer', 'png', 'pygame_bootstrap_components', 'python2', u'pil', 'sdl', 'six', 'pygame', 'pyjnius', u'kivy']
[INFO]:    Using the first of these: ['hostpython2', 'jpeg', u'openssl', u'plyer', 'png', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', u'pil', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name hoto and recipes (kivy, plyer, openssl, pil)
[INFO]:    Dist will also contain modules (plyer) installed from pip
[INFO]:    -> running cp -r /home/ish/Desktop/Hoto/....(and 198 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Recipe build order is ['hostpython2', 'jpeg', u'openssl', 'png', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', u'pil', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    The requirements (plyer) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hot...(and 56 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    hostpython2 download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading jpeg
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hoto...(and 48 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/jpeg
[INFO]:    -> running basename git://git.linaro.org/p...(and 45 more)
[INFO]:    -> running rm -f .mark-libjpeg-turbo.git
[INFO]:    Downloading jpeg from git://git.linaro.org/people/tomgall/libjpeg-turbo/libjpeg-turbo.git
[INFO]:    -> directory context libjpeg-turbo.git
[INFO]:    -> running git fetch --tags
[INFO]:    -> running git checkout linaro-android
[INFO]:    -> running git pull
[INFO]:    -> running git pull --recurse-submodules
[INFO]:    -> running git submodule update --recursive
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/jpeg
[INFO]:    -> running touch .mark-libjpeg-turbo.git
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hot...(and 52 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/openssl
[INFO]:    -> running basename https://www.openssl.or...(and 30 more)
      [INFO]:    openssl download already cached, skipping                     
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading png
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hoto...(and 47 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/png
[INFO]:    -> running basename https://github.com/jul...(and 38 more)
[INFO]:    png download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hot...(and 55 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hot...(and 55 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hot...(and 53 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hot...(and 52 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/python2
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    python2 download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading pil
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hoto...(and 47 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/pil
[INFO]:    -> running basename http://effbot.org/down...(and 26 more)
                [INFO]:    pil download already cached, skipping               
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hoto...(and 48 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    sdl2 download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hoto...(and 47 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hot...(and 52 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    pyjnius download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/ish/Desktop/Hoto...(and 48 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    kivy download already cached, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop
[INFO]:    hostpython2 is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking jpeg for armeabi-v7a
[INFO]:    -> running basename git://git.linaro.org/p...(and 45 more)
                          [INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/jpeg/armeabi-v7a
[INFO]:    jpeg is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.or...(and 30 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking png for armeabi-v7a
[INFO]:    -> running basename https://github.com/jul...(and 38 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/png/armeabi-v7a
[INFO]:    png is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
                                    [INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking pil for armeabi-v7a
[INFO]:    -> running basename http://effbot.org/down...(and 26 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/pil/armeabi-v7a
[INFO]:    pil is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/six-python2/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython2 for armeabi-v7a
[INFO]:    -> running cp /home/ish/Desktop/Hoto/.bui...(and 221 more)
[INFO]:    Prebuilding jpeg for armeabi-v7a
[INFO]:    jpeg has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for jpeg[armeabi-v7a]
[INFO]:    jpeg already patched, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding png for armeabi-v7a
[INFO]:    png has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding pil for armeabi-v7a
[INFO]:    pil has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pil[armeabi-v7a]
[INFO]:    pil already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython2 for armeabi-v7a
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2
[INFO]:    hostpython already exists, skipping build
[INFO]:    <- directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Building jpeg for armeabi-v7a
[INFO]:    -> directory context /home/ish/Desktop/Hoto/.buildozer/android/platform/build/build/other_builds/jpeg/armeabi-v7a/jpeg
[INFO]:    -> running ndk-build V=1 APP_ABI=armeabi-v7a
           working: jni/Android.mk:11: ExtraneException in thread background thread for pid 2740:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ish/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/ish/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/ish/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_2: 

  RAN: /home/ish/.buildozer/android/platform/android-ndk-r18b/ndk-build V=1 APP_ABI=armeabi-v7a

  STDOUT:
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
jni/Android.mk:11: Extraneous text after `ifeq' directive
/home/ish/.buildozer/android/platform/android-ndk-r18b/build/core/build-binary.mk:707: Android NDK: Module cjpeg depends on undefined modules: cutils    
/home/ish/.buildozer/android/platform/android-ndk-r18b/build/core/build-binary.mk:720: *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 573, in build_recipes
  File "/home/ish/Desktop/Hoto/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipes/jpeg/__init__.py", line 29, in build_arch
    super(JpegRecipe, self).build_arch(arch)
  File "pythonforandroid/recipe.py", line 679, in build_arch
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/home/ish/.local/lib/python2.7/site-packages/sh.py", line 720, in next
    self.wait()
  File "/home/ish/.local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/ish/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /home/ish/.buildozer/android/platform/android-ndk-r18b/ndk-build V=1 APP_ABI=armeabi-v7a

  STDOUT:
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
jni/Android.mk:11: Extraneous text after `ifeq' directive
/home/ish/.buildozer/android/platform/android-ndk-r18b/build/core/build-binary.mk:707: Android NDK: Module cjpeg depends on undefined modules: cutils    
/home/ish/.buildozer/android/platform/android-ndk-r18b/build/core/build-binary.mk:720: *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=hoto --bootstrap=sdl2 --requirements=kivy,plyer,openssl,pil --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/ish/Desktop/Hoto/.buildozer/android/platform/build"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2


[buildozer.txt](https://github.com/kivy/python-for-android/files/2609512/buildozer.txt)
 the error
```

**Comment by inclement** [comment]
You're using the pygame bootstrap, which is no longer really supported. All this should work with the SDL2 bootstrap and python-for-android master, except that I don't think the PIL recipe is supported there.
