### ISSUE TITLE
pyjnius build failure with NDK r17c, NDK 21, SDK 28

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1502]
### Versions

* Python: 3.6.7
* OS: docker, see below
* Kivy: what the recipe installs
* Cython: 0.26.1

### Description

I have just been testing my new docker testing environment, and ran straight into a build error:

```
# cd ~/testapp && p4a apk --arch=armeabi-v7a --requirements=kivy,python3
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI: 28
[INFO]:    Available Android APIs are (28)
[INFO]:    Requested API target 28 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /ndk/
[INFO]:    Got NDK version from $ANDROIDNDKVER: r17c
[INFO]:    Found Android API target in $NDKAPI
[INFO]:    Using Google NDK r17c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    Trying to find a bootstrap that matches the given recipes.
[INFO]:    Found 1 acceptable bootstraps: ['sdl2']
[INFO]:    Using the first of these: sdl2
[INFO]:    Found a single valid recipe set: ['hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name unnamed_dist_3 and recipes (kivy, python3)
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> directory context /root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3
[INFO]:    <- directory context /root/testapp
[INFO]:    Recipe build order is ['hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/hostpython3
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/hostpython3
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> running rm -f .mark-Python-3.7.1.tgz                                                        
[INFO]:    Downloading hostpython3 from https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> running touch .mark-Python-3.7.1.tgz
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/sdl2_image
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/releas...(and 25 more)
[INFO]:    sdl2_image download already cached, skipping                                                   
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/sdl2_mixer
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/releas...(and 25 more)
[INFO]:    sdl2_mixer download already cached, skipping                                                   
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/sdl2_ttf
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/S...(and 21 more)
[INFO]:    -> running rm SDL2_ttf-2.0.14.tar.gz                                                           
[INFO]:    -> running rm -f .mark-SDL2_ttf-2.0.14.tar.gz
[INFO]:    Downloading sdl2_ttf from https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> running touch .mark-SDL2_ttf-2.0.14.tar.gz
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading python3
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/python3
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/python3
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> running rm -f .mark-Python-3.7.1.tgz                                                        
[INFO]:    Downloading python3 from https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> running touch .mark-Python-3.7.1.tgz
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/sdl2
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> running rm -f .mark-SDL2-2.0.4.tar.gz                                                       
[INFO]:    Downloading sdl2 from https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> running touch .mark-SDL2-2.0.4.tar.gz
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/six
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> running rm -f .mark-six-1.9.0.tar.gz                                                        
[INFO]:    Downloading six from https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> running touch .mark-six-1.9.0.tar.gz
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/pyjnius
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/1.1.3.zip
[INFO]:    -> running rm -f .mark-1.1.3.zip                                                               
[INFO]:    Downloading pyjnius from https://github.com/kivy/pyjnius/archive/1.1.3.zip
[INFO]:    -> running touch .mark-1.1.3.zip
[INFO]:    <- directory context /root/testapp
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/packages/kivy
[INFO]:    -> directory context /root/.local/share/python-for-android/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.10.1.zip
[INFO]:    -> running rm -f .mark-1.10.1.zip                                                              
[INFO]:    Downloading kivy from https://github.com/kivy/kivy/archive/1.10.1.zip
[INFO]:    -> running touch .mark-1.10.1.zip
[INFO]:    <- directory context /root/testapp
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop
[INFO]:    -> running tar tf /root/.local/share/python-for-android/packages/hos...(and 25 more)
[INFO]:    -> running mv Python-3.7.1 /root/.local/share/python-for-android/bui...(and 47 more)           
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/releas...(and 25 more)
[INFO]:    -> directory context /root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running tar tf /root/.local/share/python-for-android/packages/sdl...(and 31 more)
[INFO]:    -> running mv SDL2_image-2.0.1 /root/.local/share/python-for-android...(and 51 more)           
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/releas...(and 25 more)
[INFO]:    -> directory context /root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running tar tf /root/.local/share/python-for-android/packages/sdl...(and 31 more)
[INFO]:    -> running mv SDL2_mixer-2.0.1 /root/.local/share/python-for-android...(and 51 more)           
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/S...(and 21 more)
[INFO]:    -> directory context /root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running tar tf /root/.local/share/python-for-android/packages/sdl...(and 28 more)
[INFO]:    -> running mv SDL2_ttf-2.0.14 /root/.local/share/python-for-android/...(and 48 more)           
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking python3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21
[INFO]:    -> running tar tf /root/.local/share/python-for-android/packages/pyth...(and 20 more)
[INFO]:    -> running mv Python-3.7.1 /root/.local/share/python-for-android/bui...(and 58 more)           
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> directory context /root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running tar tf /root/.local/share/python-for-android/packages/sdl2...(and 18 more)
[INFO]:    -> running mv SDL2-2.0.4 /root/.local/share/python-for-android/build...(and 38 more)           
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/six-python3/armeabi-v7a__ndk_target_21
[INFO]:    -> running tar tf /root/.local/share/python-for-android/packages/six/six-1.9.0.tar.gz
[INFO]:    -> running mv six-1.9.0 /root/.local/share/python-for-android/build/...(and 55 more)           
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/1.1.3.zip
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21
[INFO]:    -> running mv pyjnius-1.1.3 /root/.local/share/python-for-android/bu...(and 72 more)
[INFO]:    <- directory context /root/testapp
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.10.1.zip
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/kivy-python3-sdl2/armeabi-v7a__ndk_target_21
[INFO]:    -> running mv kivy-1.10.1 /root/.local/share/python-for-android/buil...(and 64 more)
[INFO]:    <- directory context /root/testapp
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    Applying patch toggle_jpg_png_webp.patch
[INFO]:    -> running patch -t -d /root/.local/share/python-for-android/build/b...(and 151 more)
[INFO]:    Applying patch extra_cflags.patch                                                              
[INFO]:    -> running patch -t -d /root/.local/share/python-for-android/build/b...(and 144 more)
[INFO]:    Applying patch fix_with_ndk_15_plus.patch                                                      
[INFO]:    -> running patch -t -d /root/.local/share/python-for-android/build/b...(and 152 more)
[INFO]:    -> running touch /root/.local/share/python-for-android/build/bootstr...(and 46 more)           
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    Applying patch toggle_modplug_mikmod_smpeg_ogg.patch
[INFO]:    -> running patch -t -d /root/.local/share/python-for-android/build/b...(and 163 more)
[INFO]:    -> running touch /root/.local/share/python-for-android/build/bootstr...(and 46 more)           
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3 for armeabi-v7a
[INFO]:    python3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    Applying patch add_nativeSetEnv.patch
[INFO]:    -> running patch -t -d /root/.local/share/python-for-android/build/b...(and 135 more)
[INFO]:    -> running touch /root/.local/share/python-for-android/build/bootstr...(and 39 more)           
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    Applying patch sdl2_jnienv_getter.patch
[INFO]:    -> running patch -t -d /root/.local/share/python-for-android/build/o...(and 171 more)
[INFO]:    -> running touch /root/.local/share/python-for-android/build/other_b...(and 70 more)           
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build
[INFO]:    -> running configure
[INFO]:    <- directory context /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3
[INFO]:    -> running cp Modules/Setup.dist /root/.local/share/python-for-andro...(and 80 more)
[INFO]:    -> running make -C /root/.local/share/python-for-android/build/other...(and 52 more)
[INFO]:    <- directory context /root/testapp                                                             
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building python3 for armeabi-v7a
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/android-build
[WARNING]: Doing some hacky stuff to link properly
[INFO]:    -> running cp /ndk/platforms/android-21/arch-arm/usr/lib/crtbegin_so.o ./
[INFO]:    -> running cp /ndk/platforms/android-21/arch-arm/usr/lib/crtend_so.o ./
[INFO]:    -> running configure --host=arm-linux-androideabi --build=x86_64-pc-...(and 184 more)
[INFO]:    -> running make all                                                                            
[INFO]:    <- directory context /root/testapp                                                             
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /root/testapp                                                             
[INFO]:    Building six for armeabi-v7a
[INFO]:    six apparently isn't already in site-packages
[INFO]:    Installing six into site-packages
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/six-python3/armeabi-v7a__ndk_target_21/six
[INFO]:    -> running python setup.py install -O2 --root=/root/.local/share/pyt...(and 68 more)
[INFO]:    <- directory context /root/testapp                                                             
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    jnius apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in pyjnius
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21/pyjnius
[INFO]:    -> running python -c import sys; print(sys.path)
cwd is /root/.local/share/python-for-android/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21/pyjnius
[INFO]:    Trying first build of pyjnius to get cython files: this is expected to fail
[INFO]:    -> running python setup.py build_ext -v
           working: error: command 'arm-linux-androideabi-gcc' failed with exit status 1                  Exception in thread background thread for pid 19532:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
/root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Lib/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'jnius' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/jnius
arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=21 -isystem /ndk/sysroot/usr/include/arm-linux-androideabi -isysroot /ndk/sysroot -I/root/.local/share/python-for-android/build/python-installs/unnamed_dist_3/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=21 -isystem /ndk/sysroot/usr/include/arm-linux-androideabi -isysroot /ndk/sysroot -I/root/.local/share/python-for-android/build/python-installs/unnamed_dist_3/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -I/root/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Include -fPIC -I/root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c jnius/jnius.c -o build/temp.linux-x86_64-3.7/jnius/jnius.o
arm-linux-androideabi-gcc: error: jnius/jnius.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
error: command 'arm-linux-androideabi-gcc' failed with exit status 1

  STDERR:


                                                                                                          
[INFO]:    pyjnius first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize jnius/jnius.pyx
[INFO]:    -> running cython ./jnius/jnius.pyx
[INFO]:    -> running python setup.py build_ext -v
           working: error: command 'arm-linux-androideabi-gcc' failed with exit status 1                  Exception in thread background thread for pid 19547:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
/root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Lib/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'jnius' extension
arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=21 -isystem /ndk/sysroot/usr/include/arm-linux-androideabi -isysroot /ndk/sysroot -I/root/.local/share/python-for-android/build/python-installs/unnamed_dist_3/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=21 -isystem /ndk/sysroot/usr/include/arm-linux-androideabi -isysroot /ndk/sysroot -I/root/.local/share/python-for-android/build/python-installs/unnamed_dist_3/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -I/root/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Include -fPIC -I/root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c jnius/jnius.c -o build/temp.linux-x86_64-3.7/jnius/jnius.o
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_convert_jstring_to_python':
jnius/jnius.c:10315:19: warning: assignment discards 'const' qualifier from pointer target type
   __pyx_v_j_chars = (__pyx_v_j_env[0])->GetStringChars(__pyx_v_j_env, __pyx_v_j_string, NULL);
                   ^
jnius/jnius.c: In function '__pyx_pf_5jnius_5jnius_12MetaJavaBase___instancecheck__':
jnius/jnius.c:18694:24: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
           __pyx_t_9 = ((PyObject *)(__pyx_v_j_env[0])->CallLongMethod(__pyx_v_j_env, __pyx_v_obj, __pyx_v_meth));
                        ^
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_py_invoke0':
jnius/jnius.c:34139:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   __pyx_t_2 = ((PyObject *)((void *)__pyx_v_jptr));
                             ^
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_create_proxy_instance':
jnius/jnius.c:35285:46: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   __pyx_t_1 = __Pyx_PyInt_From_PY_LONG_LONG(((PY_LONG_LONG)((void *)__pyx_v_py_obj))); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 168, __pyx_L1_error)
                                              ^
jnius/jnius.c: In function '__Pyx__ExceptionSave':
jnius/jnius.c:54531:19: error: 'PyThreadState' has no member named 'exc_type'
     *type = tstate->exc_type;
                   ^
jnius/jnius.c:54532:20: error: 'PyThreadState' has no member named 'exc_value'
     *value = tstate->exc_value;
                    ^
jnius/jnius.c:54533:17: error: 'PyThreadState' has no member named 'exc_traceback'
     *tb = tstate->exc_traceback;
                 ^
jnius/jnius.c: In function '__Pyx__ExceptionReset':
jnius/jnius.c:54540:22: error: 'PyThreadState' has no member named 'exc_type'
     tmp_type = tstate->exc_type;
                      ^
jnius/jnius.c:54541:23: error: 'PyThreadState' has no member named 'exc_value'
     tmp_value = tstate->exc_value;
                       ^
jnius/jnius.c:54542:20: error: 'PyThreadState' has no member named 'exc_traceback'
     tmp_tb = tstate->exc_traceback;
                    ^
jnius/jnius.c:54543:11: error: 'PyThreadState' has no member named 'exc_type'
     tstate->exc_type = type;
           ^
jnius/jnius.c:54544:11: error: 'PyThreadState' has no member named 'exc_value'
     tstate->exc_value = value;
           ^
jnius/jnius.c:54545:11: error: 'PyThreadState' has no member named 'exc_traceback'
     tstate->exc_traceback = tb;
           ^
jnius/jnius.c: In function '__Pyx__GetException':
jnius/jnius.c:54748:22: error: 'PyThreadState' has no member named 'exc_type'
     tmp_type = tstate->exc_type;
                      ^
jnius/jnius.c:54749:23: error: 'PyThreadState' has no member named 'exc_value'
     tmp_value = tstate->exc_value;
                       ^
jnius/jnius.c:54750:20: error: 'PyThreadState' has no member named 'exc_traceback'
     tmp_tb = tstate->exc_traceback;
                    ^
jnius/jnius.c:54751:11: error: 'PyThreadState' has no member named 'exc_type'
     tstate->exc_type = local_type;
           ^
jnius/jnius.c:54752:11: error: 'PyThreadState' has no member named 'exc_value'
     tstate->exc_value = local_value;
           ^
jnius/jnius.c:54753:11: error: 'PyThreadState' has no member named 'exc_traceback'
     tstate->exc_traceback = local_tb;
           ^
jnius/jnius.c: In function '__Pyx__ExceptionSwap':
jnius/jnius.c:54775:22: error: 'PyThreadState' has no member named 'exc_type'
     tmp_type = tstate->exc_type;
                      ^
jnius/jnius.c:54776:23: error: 'PyThreadState' has no member named 'exc_value'
     tmp_value = tstate->exc_value;
                       ^
jnius/jnius.c:54777:20: error: 'PyThreadState' has no member named 'exc_traceback'
     tmp_tb = tstate->exc_traceback;
                    ^
jnius/jnius.c:54778:11: error: 'PyThreadState' has no member named 'exc_type'
     tstate->exc_type = *type;
           ^
jnius/jnius.c:54779:11: error: 'PyThreadState' has no member named 'exc_value'
     tstate->exc_value = *value;
           ^
jnius/jnius.c:54780:11: error: 'PyThreadState' has no member named 'exc_traceback'
     tstate->exc_traceback = *tb;
           ^
error: command 'arm-linux-androideabi-gcc' failed with exit status 1


  STDERR:


[INFO]:    STDOUT (last 20 lines of 89):                                                                  
	jnius/jnius.c: In function '__Pyx__ExceptionSwap':	
jnius/jnius.c:54775:22: error: 'PyThreadState' has no member named 'exc_type'	
     tmp_type = tstate->exc_type;	
                      ^	
jnius/jnius.c:54776:23: error: 'PyThreadState' has no member named 'exc_value'	
     tmp_value = tstate->exc_value;	
                       ^	
jnius/jnius.c:54777:20: error: 'PyThreadState' has no member named 'exc_traceback'	
     tmp_tb = tstate->exc_traceback;	
                    ^	
jnius/jnius.c:54778:11: error: 'PyThreadState' has no member named 'exc_type'	
     tstate->exc_type = *type;	
           ^	
jnius/jnius.c:54779:11: error: 'PyThreadState' has no member named 'exc_value'	
     tstate->exc_value = *value;	
           ^	
jnius/jnius.c:54780:11: error: 'PyThreadState' has no member named 'exc_traceback'	
     tstate->exc_traceback = *tb;	
           ^	
error: command 'arm-linux-androideabi-gcc' failed with exit status 1
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /root/.local/share/python-for-android/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21/pyjnius && /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

[WARNING]: ERROR: /root/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python failed!
```

I ran into this using my new testing environment, which should allow anyone with docker installed to reproduce this quite easily:

**Steps to reproduce:**

1. Install docker & start docker daemon
2. Get p4a-testing-spaces: `git clone https://github.com/JonasT/p4a-testing-spaces`
3. `cd /path/to/p4a-testing-spaces` and then run: `chmod +x ./p4aspaces.py && ./p4aspaces.py --env p4a-py3-api18ndk21 --p4a master` (your user needs access to docker! Or run with `sudo`)
4. Wait. It will take a while. At some point, a shell will come up.
5. Inside the shell, run the instructed demo build command: `cd ~/testapp && p4a apk --arch=armeabi-v7a  --requirements=kivy,python3`

You should get the above error! (tell me if you don't)

**Comment by JonasT** [comment]
Oops, looks like Cython might just be too old. Looking into it right now, will close if I can confirm this to be the issue

**Comment by JonasT** [comment]
Yup, was just Cython being too old. :joy:
