### ISSUE TITLE
ValueError: storage dir path cannot contain spaces, please specify a path with --storage-dir

### ISSUE THREAD

**Issue by Petar-Luketina** [kivy/python-for-android#1526]
Does anyone have any insight into this error?

```# Cwd /home/pl/python-for-android-master
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pl/python-for-android-master/pythonforandroid/toolchain.py", line 1035, in <module>
    main()
  File "/home/pl/python-for-android-master/pythonforandroid/toolchain.py", line 1031, in main
    ToolchainCL()
  File "/home/pl/python-for-android-master/pythonforandroid/toolchain.py", line 536, in __init__
    self.ctx.setup_dirs(self.storage_dir)
  File "pythonforandroid/build.py", line 105, in setup_dirs
    raise ValueError('storage dir path cannot contain spaces, please '
ValueError: storage dir path cannot contain spaces, please specify a path with --storage-dir
```

Python 2.7 with updated buildozer and p4a. Build for Android

**Comment by SidnetyAtheos** [comment]
I lost hours trying to find the error thank you, I managed to solve

**Comment by parampal290** [comment]
hlo same problem please help me

**Comment by tshirtman** [comment]
don't ask for help everywhere, this is a closed issue, i answered you on discord before you even posted your message here.

**Comment by parampal290** [comment]
Hey new issue now ndk version can you help me

**Comment by tshirtman** [comment]
bug reports are not the place for user support.
