### ISSUE TITLE
raise exc sh.ErrorReturnCode_2: 

### ISSUE THREAD

**Issue by ZhangKuixun** [kivy/python-for-android#1538]
Versions:
---------

- Python: host and target Python3.7.1
- OS: Mac os
- Kivy: N/A
- Cython: N/A

Command:
----------

p4a apk --private /Users/zhangkuixun/Downloads/download/youtube-dl/youtube_dl --package=org.example.myapp --name "My application" --version 0.1 --bootstrap=sdl2 --requirements=python2,kivy

error:
----------

```
yihuyang:~ zhangkuixun$ p4a apk --private /Users/zhangkuixun/Downloads/download/python-for-android-opacam/testapps/testapp  --package=org.example.myapp --name "My application" --version 0.1 --bootstrap=sdl2 --requirements=python2,kivy --arch=armeabi-v7a
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (8, 15, 17, 19, 21, 22, 23, 24, 25, 26, 27, 28)
[INFO]:    Requested API target 21 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r10e
[INFO]:    Found virtualenv at /Library/Frameworks/Python.framework/Versions/3.7/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.8', '4.9', 'clang3.5', 'clang3.6']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found multiple valid dependency orders:
[INFO]:        ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:        ['hostpython2', 'pygame_bootstrap_components', 'python2', 'sdl', 'six', 'pygame', 'pyjnius', 'kivy']
[INFO]:    Using the first of these: ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name unnamed_dist_4 and recipes (python2, kivy)
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> running cp -r /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/bootstraps/sdl2/build /Users/zhangkuixun/.python-fo...(and 52 more)
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2_gradle-python2
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Recipe build order is ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/hostpython2
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/hostpython2
[INFO]:    -> running basename https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    hostpython2 download already cached, skipping                                                                                                                                                 
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/sdl2_image
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    sdl2_image download already cached, skipping                                                                                                                                                  
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/sdl2_mixer
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping                                                                                                                                                  
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/sdl2_ttf
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping                                                                                                                                                    
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/python2
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/python2
[INFO]:    -> running basename https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    python2 download already cached, skipping                                                                                                                                                     
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/sdl2
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    sdl2 download already cached, skipping                                                                                                                                                        
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/six
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    six download already cached, skipping                                                                                                                                                         
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/pyjnius
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    pyjnius download already cached, skipping                                                                                                                                                     
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /Users/zhangkuixun/.python-for-android/packages/kivy
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.10.0.zip
[INFO]:    kivy download already cached, skipping                                                                                                                                                        
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/other_builds/hostpython2/desktop                                                                                            
[INFO]:    hostpython2 is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2_gradle-python2/jni                                                                                    
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2_gradle-python2/jni                                                                                    
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2_gradle-python2/jni                                                                                    
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/other_builds/python2/armeabi-v7a                                                                                            
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2_gradle-python2/jni                                                                                    
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/other_builds/six-python2/armeabi-v7a                                                                                        
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a                                                                               
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.10.0.zip
[INFO]:    -> directory context /Users/zhangkuixun/.python-for-android/build/other_builds/kivy-python2-sdl2/armeabi-v7a                                                                                  
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /Users/zhangkuixun
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython2 for armeabi-v7a
[INFO]:    -> running cp /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/recipes/hostpython2/Setup /Users/zhangkuixun/.python-f...(and 75 more)
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    Applying patch sdl2_jnienv_getter.patch
[INFO]:    -> running patch -t -d /Users/zhangkuixun/.python-for-android/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a/pyjnius -p1 -i /Library/Frameworks/Python.framewo...(and 101 more)
           working: 1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej                                                                                                                        Exception in thread background thread for pid 2950:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /Users/zhangkuixun/.python-for-android/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a/pyjnius -p1 -i /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
Reversed (or previously applied) patch detected!  Assuming -R.
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej


  STDERR:


[INFO]:    STDOUT:                                                                                                                                                                                       
	patching file jnius/jnius_jvm_android.pxi	
Reversed (or previously applied) patch detected!  Assuming -R.	
patching file setup.py	
Hunk #1 FAILED at 53.	
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
[INFO]:    STDERR:
	
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/p4a", line 11, in <module>
    load_entry_point('python-for-android==0.6.0', 'console_scripts', 'p4a')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/build.py", line 566, in build_recipes
    recipe.apply_patches(arch)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/recipe.py", line 486, in apply_patches
    arch.arch)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/recipe.py", line 194, in apply_patch
    "-i", filename, _tail=10)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 720, in next
    self.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /Users/zhangkuixun/.python-for-android/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a/pyjnius -p1 -i /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
Reversed (or previously applied) patch detected!  Assuming -R.
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej


  STDERR:

yihuyang:~ zhangkuixun$ 

```

**Comment by inclement** [comment]
I think this old patching issue has been fixed, certainly it hasn't come up again recently.
