### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by Watashis** [kivy/python-for-android#1599]
### Versions

* Python: Python 3.6.7
* OS: Linux mint 19
* Kivy: v1.10.1
* Cython: Cython version 0.29.2

### Description

no work

### buildozer.spec

Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

title = My Application

package.name = myapp

package.domain = org.test

source.dir = .

source.include_exts = py,png,jpg,kv,atlas

version = 0.1

requirements = python3crystax,kivy

orientation = portrait

osx.python_version = 3.6

osx.kivy_version = 1.9.1

fullscreen = 0

android.api = 19

android.ndk = 10.3.2

android.ndk_path = /home/vladislav/.buildozer/android/platform/crystax-ndk-10.3.2
android.arch = armeabi-v7a

[buildozer]

log_level = 2
warn_on_root = 1
```

### Logs

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Система управления пакетами Debian «dpkg», версия 1.19.0.5 (amd64).
Это свободное программное обеспечение. См. условия распространения в
Универсальной общественной лицензии GNU версии 2 или более поздней.
НИКАКИЕ гарантии не предоставляются.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-oracle/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-oracle/jre/bin/keytool
# Install platform
# Run "/usr/bin/python3 -m pip install -q --user 'appdirs' 'colorama>=0.3.3' 'jinja2' 'six'"
# Cwd None
# Apache ANT found at /home/vladislav/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/vladislav/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/vladislav/.buildozer/android/platform/crystax-ndk-10.3.2
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3crystax,kivy --ndk-api 9 --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build"'
# Cwd /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (15, 19, 24)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[WARNING]: NDK version was set as r10.3.2, but checking the NDK dir claims it is 10.3.2.
[WARNING]: The build will try to continue, but it may fail and you should check that your setting is correct.
[WARNING]: If the NDK dir result is correct, you don't need to manually set the NDK ver.
[INFO]:    Using Crystax NDK r10.3.2
[INFO]:    Found virtualenv at /usr/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3crystax', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name myapp and recipes (python3crystax, kivy)
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> running cp -r /home/vladislav/coding/p...(and 257 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Recipe build order is ['hostpython3crystax', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3crystax
[INFO]:    Skipping hostpython3crystax download as no URL is set
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 81 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping                        
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 81 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping                        
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 79 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping                          
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading python3crystax
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 85 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/python3crystax
[INFO]:    -> running basename 
[INFO]:    -> running rm -f .mark-
[INFO]:    -> running touch .mark-
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 75 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    sdl2 download already cached, skipping                              
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 74 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping                               
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 78 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    pyjnius download already cached, skipping                           
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/vladislav/codin...(and 75 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    kivy download already cached, skipping                              
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3crystax for armeabi-v7a
[INFO]:    Skipping hostpython3crystax unpack as no URL is set
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking python3crystax for armeabi-v7a
[INFO]:    -> running basename 
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a
[INFO]:    python3crystax is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 27 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/other_builds/kivy-python3crystax-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3crystax for armeabi-v7a
[INFO]:    hostpython3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3crystax for armeabi-v7a
[INFO]:    python3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3crystax for armeabi-v7a
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building python3crystax for armeabi-v7a
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Building six for armeabi-v7a
[INFO]:    six apparently isn't already in site-packages
[INFO]:    Installing six into site-packages
[INFO]:    -> directory context /home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a/six
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/build.py", line 573, in build_recipes
    recipe.build_arch(arch)
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipe.py", line 775, in build_arch
    self.install_python_package(arch)
  File "/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipe.py", line 789, in install_python_package
    hostpython = sh.Command(self.hostpython_location)
  File "/home/vladislav/.local/lib/python3.6/site-packages/sh.py", line 1028, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: python3.5
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3crystax,kivy --ndk-api 9 --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/vladislav/coding/python/gui/kivy/android/1/.buildozer/android/platform/build"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
   
```

**Comment by JonasT** [comment]
`python3crystax` is a bit buggy, maybe it doesn't work with python 3.6+ on the host in some circumstances? Nevertheless, for python 3 I really recommend:

1. install p4 from git master as described here: https://python-for-android.readthedocs.io/en/latest/quickstart/ --> `pip install git+https://github.com/kivy/python-for-android.git`

   (This will give you our latest changes to use `python3` with the regular Google SDK/NDK, no Crystax needed.)

2. I recommend these SDK & API levels (minimum 19 will no longer work on master, I believe):

   SDK target api 28, build-tools;28.0.3, minimum API/NDK API 21, NDK release r17c

And make sure to use `python3` in the `--requirements`, not `python3crystax`!

Does that fix the problem for you?

**Comment by inclement** [comment]
python3crystax never got a hostpython3crystax build, so you need to have locally the same python version you're trying to target on Android. It looks like you're building python3crystax3.5 with local python 3.6 (or something else).

You can specify `python3crystax==3.6` in the requirements if you have python3.6 available locally, but it would be better to use the new method @JonasT has explained.
