### ISSUE TITLE
App crashing following successful build

### ISSUE THREAD

**Issue by OptimusGREEN** [kivy/python-for-android#1719]
### Versions

* Python: 3.7
* OS: ubuntu 18.04
* Kivy: master
* Cython: 0.29.5

### Description

App compiles successfully but crashes on launch.

When I revert commit #1714 then this error does't appear and my app works as expected.

### buildozer.spec

Command:
```
buildozer android debug
```

Spec file:
```
[app]

#########################################################
#     Python2
#
#requirements = python2legacy,kivy==master,pyopenssl,openssl,urllib3,android,pyjnius,dropbox,requests==2.20.0,chardet,certifi,idna

#
#     Python3
#
requirements = python3,kivy==master,pyopenssl,openssl,urllib3,android,pyjnius,dropbox,requests==2.20.0,chardet,certifi,idna
#########################################################

# SHORTCUTS

#########################################################

android.api = 27
android.gradle_dependencies = "com.android.support:support-compat:26.0.0-alpha1", 'com.android.support:support-fragment:26.0.0-alpha1', 'com.android.support:appcompat-v7:26.0.0-alpha1'
android.add_src = ./libs/java/*.java
android.add_jars = ./libs/java/*.jar

#########################################################


android.permissions = WRITE_EXTERNAL_STORAGE, INTERNET
android.minapi = 21
p4a.hook = ./tools/hooks/hook.py

# MAC
#android.ndk_path = ~/Development/Android/NDK/android-ndk-r17c
#p4a.source_dir = /Users/john/Development/Git/python-for-android/

# Linux
android.ndk_path = /home/kivy/Android/android-ndk-r17c
#android.sdk_path = /home/kivy/Android/android-sdk-28
p4a.source_dir = /media/psf/Development/Git/python-for-android/

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a


#########################################################

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity


#########################################################

# (str) Title of your application
title = OptiDev

# (str) Package name
package.name = optileave.dev

# (str) Package domain (needed for android/ios packaging)
package.domain = com.optimusgreen

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,ttf

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
#version = 0.1.6

# (str) Application versioning (method 2)
version.regex = app_version_code = ['"](.*)['"]
version.filename = %(source.dir)s/libs/modules/strings.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
#requirements = kivy==1.10.1,android
#requirements = kivy==1.10.1,android,python3crystax==3.6

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
# garden_requirements = navigationdrawer

# (str) Presplash of the application
presplash.filename = %(source.dir)s/art/splash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/art/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
#osx.python_version = 3

# Kivy version to use
#osx.kivy_version = 1.10.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET, ACCESS_NETWORK_STATE, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE

# (int) Android API to use
#android.api = 27

# (int) Minimum API required
#android.minapi = 19

# (int) Android SDK version to use
#android.sdk = 23

# (str) Android NDK version to use
#android.ndk = 10.3.2

# (int) Android NDK API to use (optional). This is the minimum API your app will support.
#android.ndk_api = 19

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path = ~/Development/NDK/crystax-ndk-10.3.2
#android.ndk_path = ~/Development/NDK/android-ndk-r16b

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (str) python-for-android branch to use, defaults to stable
p4a.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
android.logcat_filters = *:S python:V

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
#android.arch = arm64-v8a

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir = /Users/john/Development/python-for-android-master

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook = ./tools/hooks/hook.py

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ~/Development/kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

### Logs

logcat error
```

                            Process com.optimusgreen.optileave.dev created for activity com.optimusgreen.optileave.dev/org.kivy.android.PythonActivity
                            PID: 14070   UID:    GIDs:

                 Zygote  E  isWhitelistProcess - Process is Whitelisted
                SELinux  W  SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SM-G950F_8.0.0_0018, [-1 -1 -1 -1 0 1]
                         I  SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.optimusgreen.optileave.dev
               zygote64  I  Late-enabling -Xcheck:jni
         ActivityThread  D  Added TimaKeyStore provider
            vndksupport  I  sphal namespace is not configured for this process. Loading /vendor/lib64/egl/libGLES_mali.so from the current namespace instead.
                 libEGL  D  loaded /vendor/lib64/egl/libGLES_mali.so
         PythonActivity  V  PythonActivity onCreate running
                         V  About to do super onCreate
                    SDL  V  Device: dreamlte
                         V  Model: SM-G950F
                         V  onCreate()
         PythonActivity  V  Did super onCreate
                    SDL  V  getting identifier
                         V  kind is drawable and name presplash
                         V  result is 2131099745
                         V  asked to get string presplash_color
                         V  getting identifier
                         V  kind is string and name presplash_color
                         V  result is 2131361824
         PythonActivity  V  Ready to unpack
                         V  UNPACKING!!! private app
                    SDL  V  asked to get string private_version
                         V  getting identifier
                         V  kind is string and name private_version
                         V  result is 2131361825
         PythonActivity  V  Data version is 1550581936.26
                         V  onResume()
                    SDL  V  onResume()
         OpenGLRenderer  D  HWUI GL Pipeline
@7f7dce[PythonActivity]  D  setView = DecorView@9f184ef[PythonActivity] TM=true MM=false
             System.err  W  Attempt to get length of null array
             ScrollView  D  initGoToTop
972c2fb[PythonActivity]  D  setView = DecorView@667af18[] TM=true MM=false
               zygote64  E  No implementation found for void org.libsdl.app.SDLActivity.nativeSetenv(java.lang.String, java.lang.String) (tried Java_org_libsdl_app_SDLActivity_nativ
                            eSetenv and Java_org_libsdl_app_SDLActivity_nativeSetenv__Ljava_lang_String_2Ljava_lang_String_2)
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.optimusgreen.optileave.dev, PID: 14070
                         E  java.lang.UnsatisfiedLinkError: No implementation found for void org.libsdl.app.SDLActivity.nativeSetenv(java.lang.String, java.lang.String) (tried Java_
                            org_libsdl_app_SDLActivity_nativeSetenv and Java_org_libsdl_app_SDLActivity_nativeSetenv__Ljava_lang_String_2Ljava_lang_String_2)
                         E      at org.libsdl.app.SDLActivity.nativeSetenv(Native Method)
                         E      at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:176)
                         E      at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:121)
                         E      at android.os.AsyncTask.finish(AsyncTask.java:695)
                         E      at android.os.AsyncTask.-wrap1(Unknown Source:0)
                         E      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                         E      at android.os.Handler.dispatchMessage(Handler.java:105)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6938)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

                            Process com.optimusgreen.optileave.dev (PID: 14070) ended
```

Build output - [https://paste.city/160](url)

**Comment by OptimusGREEN** [comment]
Further investigation has found this issue is happening regardless of the above mentioned commit when building for Arm v8.

**Comment by j-devel** [comment]
I have also encountered this problem in 64bit build cases.  Addressed in #1701.

**Comment by SwagatRanjit84** [comment]
@OptimusGREEN After doing python-for-android recipes, its showing error even after installing pbs:
 ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

I am using windows 10 64 bit

**Comment by OptimusGREEN** [comment]
Just built successfully with master on arm7 so the above mentioned commit isn't to blame. must've been an issue with my env previously. I will merge #1701 as mentioned by @j-devel and test a clean arm7 and arm 8 build and report back.

**Comment by SwagatRanjit84** [comment]
@OptimusGREEN  I havn't got it going!! Will it work on windows? Some are saying it won't work on windows?

**Comment by OptimusGREEN** [comment]
> @OptimusGREEN I havn't got it going!! Will it work on windows? Some are saying it won't work on windows?

Sorry, I have no idea. I don't use windows. I haven't got arm 8 working yet. just testing at the moment.

**Comment by SwagatRanjit84** [comment]
@OptimusGREEN Are you doing it on ubunutu or mac?

**Comment by OptimusGREEN** [comment]
unfortunately on ubuntu as the Mac building process is currently broken as per #1647

**Comment by OptimusGREEN** [comment]
I can confirm that #1701 fixes this issue for arm8.
arm7 also built and ran without problem

**Comment by SwagatRanjit84** [comment]
@OptimusGREEN  didn't work on my side Windows 10 :/
