### ISSUE TITLE
Missing symbols when using numpy on older android

### ISSUE THREAD

**Issue by qwenger** [kivy/python-for-android#1805]
### Versions

* Python: 3.7.1
* OS: working: Android 7.0.1 (api 24), Android 8.0.0 (api 26); crashing: Android 5.0.2 (api 21)
* Kivy: 1.10.1
* Cython: 0.27.3, 0.28.2, 0.29
* p4a: only master branch (compilation fails in stable, something wrong/missing with the NPK version)
* build machine: Archlinux x64, Python 3.7.3
* numpy: from the recipe, i.e. 1.15.1.
* buildozer: 0.39.0

### Description

The APK compiles fine, but the app crashes on startup on older Android due to missing symbols in the multiarray.so shared object of numpy.

### Similar issues

#1778: different symbol missing, no info about the versions of Android
#1678: was solved with python3 and recent Cython, not applicable here

### App

```
__version__ = "0.1"

import numpy

from kivy.app import App
from kivy.uix.button import Button


class TestApp(App):
    def build(self):
        return Button(text=str(numpy.array([1, 2, 3])))


if __name__ == "__main__":
    TestApp().run()
```

### buildozer.spec

Command:
```xonsh
#! /usr/bin/xonsh

# https://stackoverflow.com/a/51644855
with ${...}.swap(JAVA_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee"):
    buildozer --verbose android debug
```
Then:
```xonsh
#! /usr/bin/xonsh

# https://stackoverflow.com/a/51644855
with ${...}.swap(JAVA_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee"):
    buildozer --verbose android deploy run logcat
```

Spec file:
```
[app]

# (str) Title of your application
title = QWPeaks

# (str) Package name
package.name = qwpeaks

# (str) Package domain (needed for android/ios packaging)
package.domain = org.qwpeaks

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,npy

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = tests,bin,android_resources

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
#version = 0.1

# (str) Application versioning (method 2)
version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,plyer,openssl,cryptography,kivy,numpy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
presplash.filename = %(source.dir)s/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = landscape

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION,ACCESS_LOCATION_EXTRA_COMMANDS,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE

# (int) Target Android API, should be as high as possible.
android.api = 27

# (int) Minimum API your APK will support.
android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = android_resources/android-ndk-r17c

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
android.sdk_path = android_resources/android_sdk

# (str) ANT directory (if empty, it will be automatically downloaded.)
android.ant_path = android_resources/apache-ant-1.9.4

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
#android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to master
#p4a.branch = stable

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir = android_resources/python-for-android

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 1

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

### Logs

```
--------- beginning of system
--------- beginning of main
I/python  (11388): Initializing Python for Android
I/python  (11388): Setting additional env vars from p4a_env_vars.txt
I/python  (11388): Changing directory to the one provided by ANDROID_ARGUMENT
I/python  (11388): /data/data/org.qwpeaks.qwpeaks/files/app
I/python  (11388): Preparing to initialize python
I/python  (11388): _python_bundle dir exists
I/python  (11388): calculated paths to be...
I/python  (11388): /data/data/org.qwpeaks.qwpeaks/files/app/_python_bundle/stdlib.zip:/data/data/org.qwpeaks.qwpeaks/files/app/_python_bundle/modules
I/python  (11388): set wchar paths...
I/python  (11388): Initialized python
I/python  (11388): AND: Init threads
I/python  (11388): testing python print redirection
I/python  (11388): Android path ['.', '/data/data/org.qwpeaks.qwpeaks/files/app/_python_bundle/stdlib.zip', '/data/data/org.qwpeaks.qwpeaks/files/app/_python_bundle/modules', '/data/data/org.qwpeaks.qwpeaks/files/app/_python_bundle/site-packages']
I/python  (11388): os.environ is environ({'PATH': '/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'ASEC_MOUNTPOINT': '/mnt/asec', 'LOOP_MOUNTPOINT': '/mnt/obb', 'BOOTCLASSPATH': '/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar:/system/framework/wifi-wfdservice.jar:/system/framework/HTCCommonctrl.jar:/system/framework/HTCDev.jar:/system/framework/HTCExtension.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/usbnet.jar', 'LD_PRELOAD': 'libsigchain.so', 'EXTERNAL_STORAGE': '/storage/emulated/legacy', 'EMULATED_STORAGE_SOURCE': '/mnt/shell/emulated', 'EMULATED_STORAGE_TARGET': '/storage/emulated', 'EXTERNAL_STORAGE4': '/storage/usb', 'EXTERNAL_STORAGE5': '/storage/usb', 'ANDROID_PROPERTY_WORKSPACE': '9,0', 'ANDROID_SOCKET_zygote': '10', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/data/org.qwpeaks.qwpeaks/files/app', 'ANDROID_APP_PATH': '/data/data/org.qwpeaks.qwpeaks/files/app', 'ANDROID_PRIVATE': '/data/data/org.qwpeaks.qwpeaks/files', 'ANDROID_UNPACK': '/data/data/org.qwpeaks.qwpeaks/files/app', 'PYTHONHOME': '/data/data/org.qwpeaks.qwpeaks/files/app', 'PYTHONPATH': '/data/data/org.qwpeaks.qwpeaks/files/app:/data/data/org.qwpeaks.qwpeaks/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'False', 'P4A_ORIENTATION': 'landscape', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
I/python  (11388): Android kivy bootstrap done. __name__ is __main__
I/python  (11388): AND: Ran string
I/python  (11388): Run user program, change dir and execute entrypoint
I/python  (11388): Traceback (most recent call last):
I/python  (11388):   File "/data/dev/python/qwpeaks/.buildozer/android/platform/build/build/python-installs/qwpeaks/numpy/core/__init__.py", line 16, in <module>
I/python  (11388): ImportError: dlopen failed: cannot locate symbol "malloc" referenced by "multiarray.so"...
I/python  (11388): During handling of the above exception, another exception occurred:
I/python  (11388): Traceback (most recent call last):
I/python  (11388):   File "/data/dev/python/qwpeaks/.buildozer/android/app/main.py", line 3, in <module>
I/python  (11388):   File "/data/dev/python/qwpeaks/.buildozer/android/platform/build/build/python-installs/qwpeaks/numpy/__init__.py", line 142, in <module>
I/python  (11388):   File "/data/dev/python/qwpeaks/.buildozer/android/platform/build/build/python-installs/qwpeaks/numpy/add_newdocs.py", line 13, in <module>
I/python  (11388):   File "/data/dev/python/qwpeaks/.buildozer/android/platform/build/build/python-installs/qwpeaks/numpy/lib/__init__.py", line 8, in <module>
I/python  (11388):   File "/data/dev/python/qwpeaks/.buildozer/android/platform/build/build/python-installs/qwpeaks/numpy/lib/type_check.py", line 11, in <module>
I/python  (11388):   File "/data/dev/python/qwpeaks/.buildozer/android/platform/build/build/python-installs/qwpeaks/numpy/core/__init__.py", line 26, in <module>
I/python  (11388): ImportError: 
I/python  (11388): Importing the multiarray numpy extension module failed.  Most
I/python  (11388): likely you are trying to import a failed build of numpy.
I/python  (11388): If you're working with a numpy git repo, try `git clean -xdf` (removes all
I/python  (11388): files not under version control).  Otherwise reinstall numpy.
I/python  (11388): Original error was: dlopen failed: cannot locate symbol "malloc" referenced by "multiarray.so"...
I/python  (11388): Python for android ended.
```

**Comment by qwenger** [comment]
@tshirtman
