### ISSUE TITLE
Problems with posixpath

### ISSUE THREAD

**Issue by Depau** [kivy/python-for-android#188]
I noticed a problem in your android implementation of posixpath. Apparently it seems that it tries to look for "endswith" in java.io.File, which doesn't have it, throwing an exception.

```
I/python  (20867):  Traceback (most recent call last):
I/python  (20867):    File "/home/davideddu/Stuff/karaokivy/.buildozer/android/app/main.py", line 681, in <module>
I/python  (20867):    File "/home/davideddu/Stuff/karaokivy/.buildozer/android/app/main.py", line 140, in check_env
I/python  (20867):    File "/home/davideddu/karaokivy/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/posixpath.py", line 68, in join
I/python  (20867):  AttributeError: 'java.io.File' object has no attribute 'endswith'
I/python  (20867): Python for android ended.
```
##

**Comment by inclement** [comment]
Closing this old issue as long-fixed :)
