### ISSUE TITLE
dlopen failed: jnius.so is for EM_ARM (40) instead of EM_386 (3)

### ISSUE THREAD

**Issue by Fak3** [kivy/python-for-android#1927]
p4a version: develop branch

I built my apk for arm architecture, then built it for x86, with `--arch=x86`. When i start my app on x86 android studio emulator, i am getting an error that jnius was built for arm, instead of x86:
```
07-21 12:56:00.446 I/python  ( 7384): [INFO   ] [Logger      ] Record log in /data/user/0/org.spbelect.paradox2/files/app/.kivy/logs/kivy_19-07-21_0.txt
07-21 12:56:00.446 I/python  ( 7384): [INFO   ] [Kivy        ] v2.0.0.dev0, git-Unknown, 20190721
07-21 12:56:00.446 I/python  ( 7384): [INFO   ] [Kivy        ] Installed at "/data/user/0/org.spbelect.paradox2/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
07-21 12:56:00.447 I/python  ( 7384): [INFO   ] [Python      ] v3.7.1 (default, Jul 21 2019, 12:25:20) 
07-21 12:56:00.447 I/python  ( 7384): [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
07-21 12:56:00.447 I/python  ( 7384): [INFO   ] [Python      ] Interpreter at "android_python"
07-21 12:56:02.723 I/python  ( 7384): [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
07-21 12:56:02.957 I/python  ( 7384): [INFO   ] [Window      ] Provider: sdl2
07-21 12:56:02.994 I/python  ( 7384): [INFO   ] [Window      ] Android windowed mode
07-21 12:56:03.028 I/python  ( 7384): [INFO   ] [Window      ] orientations: ""
07-21 12:56:03.042 V/SDL     ( 7384): setOrientation() orientation=-1 width=800 height=600 resizable=true hint=
07-21 12:56:03.047 I/python  ( 7384): [INFO   ] [Window      ] failed to enable multisamples
07-21 12:56:03.048 V/SDL     ( 7384): setOrientation() orientation=-1 width=800 height=600 resizable=true hint=
07-21 12:56:03.081 V/SDL     ( 7384): pixel format RGBA_8888
07-21 12:56:03.081 V/SDL     ( 7384): Window size: 480x764
07-21 12:56:03.081 V/SDL     ( 7384): Device size: 480x800
07-21 12:56:03.114 I/python  ( 7384): [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
07-21 12:56:03.116 I/python  ( 7384): [INFO   ] [GL          ] Backend used <sdl2>
07-21 12:56:03.121 I/python  ( 7384): [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 (4.2 (Core Profile) Mesa 19.0.4)'>
07-21 12:56:03.121 I/python  ( 7384): [INFO   ] [GL          ] OpenGL vendor <b'Google (Intel Open Source Technology Center)'>
07-21 12:56:03.126 I/python  ( 7384): [INFO   ] [GL          ] OpenGL renderer <b'Android Emulator OpenGL ES Translator (Mesa DRI Intel(R) Ivybridge Mobile )'>
07-21 12:56:03.126 I/python  ( 7384): [INFO   ] [GL          ] OpenGL parsed version: 2, 0
07-21 12:56:03.127 I/python  ( 7384): [INFO   ] [GL          ] Texture max size <16384>
07-21 12:56:03.127 I/python  ( 7384): [INFO   ] [GL          ] Texture max units <16>
07-21 12:56:03.317 I/python  ( 7384): [INFO   ] [Window      ] auto add sdl2 input provider
07-21 12:56:03.328 I/python  ( 7384): [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
07-21 12:56:03.505 I/python  ( 7384): [INFO   ] [Text        ] Provider: sdl2
07-21 12:56:03.512 I/python  ( 7384):  Traceback (most recent call last):
07-21 12:56:03.513 I/python  ( 7384):    File "/home/z/pproj/paradox_dev/main.py", line 64, in <module>
07-21 12:56:03.513 I/python  ( 7384):    File "/home/u1/.local/share/python-for-android/build/python-installs/paradox/jnius/__init__.py", line 12, in <module>
07-21 12:56:03.514 I/python  ( 7384):  ImportError: dlopen failed: "/data/data/org.spbelect.paradox2/files/app/_python_bundle/site-packages/jnius/jnius.so" is for EM_ARM (40) instead of EM_386 (3)
07-21 12:56:03.514 I/python  ( 7384): Python for android ended.
```

Expected results: rebuilding with another arch should not include previously built packages for different arch

**Comment by Fak3** [comment]
Ah! This could have been caused by `--dist-name` flag, which i provided. Will check.
