### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 77317: invalid continuation byte

### ISSUE THREAD

**Issue by tsrift** [kivy/python-for-android#2023]
Help!
I'm struggling to make "Hello world" app running on android. It's crushing immediately after launching
with python 3.7.
[https://github.com/kivy/buildozer/issues/990]
In buildozer.spec
when requirements = python3,kivy
logcat is full of permissions errors, finishing with:
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 77317: invalid continuation byte**
And when I add these these requirements:
sqlite3,openssl,python3,kivy,requests,urllib3,chardet,certifi,idna,android,pyjnius,
logcat looks like this:

```
11-04 18:53:50.139 1115 1150 D AutomaticBrightnessController: onSensorChanged: lux = 8.0
11-04 18:53:50.152 495 17699 D AudioTrackShared: front(25280), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.172 495 17699 D AudioTrackShared: front(25600), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.193 495 17699 D AudioTrackShared: front(25920), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.213 495 17699 D AudioTrackShared: front(26240), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.233 495 17699 D AudioTrackShared: front(26560), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.253 495 17699 D AudioTrackShared: front(26880), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.274 495 17699 D AudioTrackShared: front(27200), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.293 495 17699 D AudioTrackShared: front(27520), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.313 495 17699 D AudioTrackShared: front(27840), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.333 495 17699 D AudioTrackShared: front(28160), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.353 495 17699 D AudioTrackShared: front(28480), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.373 495 17699 D AudioTrackShared: front(28800), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.393 495 17699 D AudioTrackShared: front(29120), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.413 495 17699 D AudioTrackShared: front(29440), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.433 495 17699 D AudioTrackShared: front(29760), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.453 495 17699 D AudioTrackShared: front(30080), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.473 495 17699 D AudioTrackShared: front(30400), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.493 495 17699 D AudioTrackShared: front(30720), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.513 495 17699 D AudioTrackShared: front(31040), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.533 495 17699 D AudioTrackShared: front(31360), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.553 495 17699 D AudioTrackShared: front(31680), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.573 495 17699 D AudioTrackShared: front(32000), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.593 495 17699 D AudioTrackShared: front(32320), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.613 495 17699 D AudioTrackShared: front(32640), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.633 495 17699 D AudioTrackShared: front(32960), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.653 495 17699 D AudioTrackShared: front(33280), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.673 495 17699 D AudioTrackShared: front(33600), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.693 495 17699 D AudioTrackShared: front(33920), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.713 495 17699 D AudioTrackShared: front(34240), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.733 495 17699 D AudioTrackShared: front(34560), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.753 495 17699 D AudioTrackShared: front(34880), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.773 495 17699 D AudioTrackShared: front(35200), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.794 495 17699 D AudioTrackShared: front(35520), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.813 495 17699 D AudioTrackShared: front(35840), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.833 495 17699 D AudioTrackShared: front(36160), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.853 495 17699 D AudioTrackShared: front(36480), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.873 495 17699 D AudioTrackShared: front(36800), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.893 495 17699 D AudioTrackShared: front(37120), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.913 495 17699 D AudioTrackShared: front(37440), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.919 1115 1115 E WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 300 num clients 17
11-04 18:53:50.920 1115 1115 E WifiTrafficPoller: packet count Tx=259921 Rx=432465
11-04 18:53:50.933 495 17699 D AudioTrackShared: front(37760), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.952 495 17699 D AudioTrackShared: front(38080), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.972 495 17699 D AudioTrackShared: front(38400), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.974 1115 1277 D WifiStateMachine: ConnectedState (when=-2ms what=131155 arg1=146!CMD_RSSI_POLL rt=100623738/141145452 146 0 "ARROW_017930" 0c:b9:12:01:79:30 rssi=-36 f=2422 sc=60 link=65 tx=0,0, 0,0, 0,0 rx=0,0 bcn=0 [on:0 tx:0 rx:0 period:2559] from screen [on:0 period:932000638] gl hn u24 rssi=-34 ag=0 hr ticks 0,0,15 ls-=0 [56,56,56,56,61] brc=0 lrc=0 offload-stoppedmmls=
11-04 18:53:50.974 1115 1277 D WifiStateMachine: Fail=4 Retry=27 MulRetry=17 ACKFail=369 FCSErr=454 TxOk=142 RxOk=236 Rst:Reason=0 Time=0 RoamFail:Times=0 Time=0 TxDone:IsARP=0 ArrDrv=0 EnQ=0 DeQ=0 LeaveDrv=0 Curr=0 CurrTime=0
11-04 18:53:50.974 1115 1277 D WifiStateMachine: fw log: 1 769 ScanCnt: 3 0 2 0 RoamCnt: 1 90 132 RFCnt: 3 3 0 0 0 CoexCnt: 0 0 1 LPCnt: 3354 3392 2 BBCnt: 0 0 0 0 0 0 0 0 0 0 50462752 41877504 MacRXCnt: 3613217 1289670 6 549915 229129 0 0 3624801901 0 0 0 0 0 MacTXCnt: 688988032 0
11-04 18:53:50.975 1115 1277 D WifiStateMachine: L2ConnectedState (when=-4ms what=131155 arg1=146!CMD_RSSI_POLL rt=100623739/141145453 146 0 "ARROW_017930" 0c:b9:12:01:79:30 rssi=-36 f=2422 sc=60 link=65 tx=0,0, 0,0, 0,0 rx=0,0 bcn=0 [on:0 tx:0 rx:0 period:1] from screen [on:0 period:932000639] gl hn u24 rssi=-34 ag=0 hr ticks 0,0,15 ls-=0 [56,56,56,56,61] brc=0 lrc=0 offload-stoppedmmls=
11-04 18:53:50.975 1115 1277 D WifiStateMachine: Fail=4 Retry=27 MulRetry=17 ACKFail=369 FCSErr=454 TxOk=142 RxOk=236 Rst:Reason=0 Time=0 RoamFail:Times=0 Time=0 TxDone:IsARP=0 ArrDrv=0 EnQ=0 DeQ=0 LeaveDrv=0 Curr=0 CurrTime=0
11-04 18:53:50.975 1115 1277 D WifiStateMachine: fw log: 1 769 ScanCnt: 3 0 2 0 RoamCnt: 1 90 132 RFCnt: 3 3 0 0 0 CoexCnt: 0 0 1 LPCnt: 3354 3392 2 BBCnt: 0 0 0 0 0 0 0 0 0 0 50462752 41877504 MacRXCnt: 3613217 1289670 6 549915 229129 0 0 3624801901 0 0 0 0 0 MacTXCnt: 688988032 0
11-04 18:53:50.979 1115 1277 D WifiStateMachine: get link layer stats 0
11-04 18:53:50.982 1115 1277 D WifiHW : enter -->wifi_send_command cmd=IFNAME=wlan0 SIGNAL_POLL
11-04 18:53:50.982 1332 1332 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
11-04 18:53:50.986 1115 1277 D WifiHW : leave --> reply=RSSI=-36
11-04 18:53:50.986 1115 1277 D WifiHW : LINKSPEED=65
11-04 18:53:50.986 1115 1277 D WifiHW : NOISE=9999
11-04 18:53:50.986 1115 1277 D WifiHW : FREQUENCY=2422
11-04 18:53:50.986 1115 1277 D WifiHW :
11-04 18:53:50.989 1115 1277 I WifiStateMachine: fetchRssiLinkSpeedAndFrequencyNative, newRssi:-36, newLinkSpeed:65, SSID:"ARROW_017930"
11-04 18:53:50.989 1115 1277 D WifiHW : enter -->wifi_send_command cmd=IFNAME=wlan0 DRIVER GET_STA_LINK_DETECT
11-04 18:53:50.989 1332 1332 D wpa_supplicant: wlan0: Control interface command 'DRIVER GET_STA_LINK_DETECT'
11-04 18:53:50.989 1332 1332 D wpa_supplicant: iface wlan0 recv cmd GET_STA_LINK_DETECT
11-04 18:53:50.989 1332 1332 D wpa_supplicant: get_sta_link_detect
11-04 18:53:50.989 1332 1332 D wpa_supplicant: nl80211: Test Mode buflen = 16, ifindex=23
11-04 18:53:50.992 495 17699 D AudioTrackShared: front(38400), mIsOut(0), mAvailToClient=320 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:50.996 1115 1277 D WifiHW : leave --> reply=
11-04 18:53:50.996 1115 1277 D WifiHW : Fail=0 Retry=8 MulRetry=2 ACKFail=16 FCSErr=57 TxOk=54 RxOk=37 Rst:Reason=0 Time=0 RoamFail:Times=0 Time=0 TxDone:IsARP=0 ArrDrv=0 EnQ=0 DeQ=0 LeaveDrv=0 Curr=0 CurrTime=0
11-04 18:53:50.996 1115 1277 D WifiHW : fw log: 1 100795137 ScanCnt: 29 7 34 0 RoamCnt: 1 90 132 RFCnt: 132 132 0 0 0 CoexCnt: 0 0 1 LPCnt: 3354 3392 0 BBCnt: 1043 789 0 653 221 0 22 2 98 100 50462752 41877504 MacRXCnt: 3613417 1289727 6 549952 229162 0 0 3627826587 0 0 0 0 0 MacTXCnt: 689237769 0
11-04 18:53:50.996 1115 1277 E WifiStateMachine: wifiLinkStatics=
11-04 18:53:50.996 1115 1277 E WifiStateMachine: Fail=0 Retry=8 MulRetry=2 ACKFail=16 FCSErr=57 TxOk=54 RxOk=37 Rst:Reason=0 Time=0 RoamFail:Times=0 Time=0 TxDone:IsARP=0 ArrDrv=0 EnQ=0 DeQ=0 LeaveDrv=0 Curr=0 CurrTime=0
11-04 18:53:50.996 1115 1277 E WifiStateMachine: fw log: 1 100795137 ScanCnt: 29 7 34 0 RoamCnt: 1 90 132 RFCnt: 132 132 0 0 0 CoexCnt: 0 0 1 LPCnt: 3354 3392 0 BBCnt: 1043 789 0 653 221 0 22 2 98 100 50462752 41877504 MacRXCnt: 3613417 1289727 6 549952 229162 0 0 3627826587 0 0 0 0 0 MacTXCnt: 689237769 0
11-04 18:53:50.996 1115 1277 D WifiStateMachine: mLastSignalLevel:4, newSignalLevel:4
11-04 18:53:50.997 1115 1277 E WifiConfigStore: updateConfiguration freq=2422 BSSID=0c:b9:12:01:79:30 RSSI=-36 "ARROW_017930"WPA_PSK
11-04 18:53:51.001 1115 1277 V ActivityManager: Broadcast sticky: Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{4a21b7f 1115:system/1000}
11-04 18:53:51.009 1115 1322 D WifiWatchdogStateMachine: RSSI current: 4 new: -36, 4
11-04 18:53:51.012 495 17699 D AudioTrackShared: front(38720), mIsOut(0), mAvailToClient=320 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.015 1394 1394 D StatusBar.NetworkController: slot=-10;action=android.net.wifi.RSSI_CHANGED
11-04 18:53:51.032 495 17699 D AudioTrackShared: front(38720), mIsOut(0), mAvailToClient=640 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.052 495 17699 D AudioTrackShared: front(39680), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.072 495 17699 D AudioTrackShared: front(40000), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.092 495 17699 D AudioTrackShared: front(40320), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.109 1115 1269 D InputReader: AP_PROF:AppLaunch_dispatchPtr:Down:100623873, ID:0, Index:2004799424
11-04 18:53:51.109 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.109 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.110 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.110 1115 1268 D PowerManagerService: userActivityFromNative
11-04 18:53:51.111 1115 1268 D PowerManagerService: userActivityNoUpdateLocked: eventTime=100623873, event=2, flags=0x0, uid=1000
11-04 18:53:51.112 1115 1268 D PowerManagerNotifier: onUserActivity: event=2, uid=1000
11-04 18:53:51.112 1115 1268 D PowerManagerService: updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=100665874 (in 41998 ms)
11-04 18:53:51.112 1115 1268 D DisplayPowerController: requestPowerState: policy=BRIGHT, useProximitySensor=false, screenBrightness=139, screenAutoBrightnessAdjustment=-0.14960629, brightnessSetByUser=true, useAutoBrightness=true, blockScreenOn=false, lowPowerMode=false, boostScreenBrightness=false, dozeScreenBrightness=-1, dozeScreenState=UNKNOWN, waitForNegativeProximity=false, changed=false
11-04 18:53:51.112 1115 1268 D PowerManagerService: updateDisplayPowerStateLocked: mDisplayReady=true, policy=3, mWakefulness=1, mWakeLockSummary=0x1, mUserActivitySummary=0x1, mBootCompleted=true, mScreenBrightnessBoostInProgress=false
11-04 18:53:51.112 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.115 495 17699 D AudioTrackShared: front(40640), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.116 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623873, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.121 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.121 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.121 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.122 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.123 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623879, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.124 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.125 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.125 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.125 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.129 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623888, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.132 495 17699 D AudioTrackShared: front(40960), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.133 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.133 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.133 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.133 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.133 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623897, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.138 1669 2519 D OpenGLRenderer: Allocate layer: 0x7f53cb7e80 256x256
11-04 18:53:51.141 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.141 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.142 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.142 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.142 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623905, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.144 349 402 I BufferQueueProducer: com.miui.home/com.miui.home.launcher.Launcher queueBuffer: fps=0.60 dur=3307.25 max=2975.36 min=331.89
11-04 18:53:51.149 349 349 D MALI : eglCreateImageKHR:511: [Crop] 0 0 0 0 img[1080 1920]
11-04 18:53:51.150 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.150 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.150 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.151 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.151 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623914, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.151 349 349 I SurfaceFlinger: [Built-in Screen (type:0)] fps:16.366062,dur:2994.00,max:2194.18,min:3.27
11-04 18:53:51.152 495 17699 D AudioTrackShared: front(41280), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.158 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.159 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.159 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.159 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.160 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623922, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.168 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.168 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.168 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.168 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.171 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623931, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.172 495 17699 D AudioTrackShared: front(41600), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.176 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.176 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.176 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.176 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.176 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623939, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.184 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.184 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.184 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.185 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.185 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623948, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.192 495 17699 D AudioTrackShared: front(41920), mIsOut(0), mAvailToClient=0 stepCount=320 minimum=320, FUTEX_WAKE
11-04 18:53:51.193 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.193 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:51.193 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.193 1115 1268 I PerfService: PerfServiceNative_boostEnableTimeoutMsAsync:3, 100
11-04 18:53:51.194 1394 1394 V WallpaperService: Delivering touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=945.1249, y[0]=800.583, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x3, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100623957, downTime=100623873, deviceId=2, source=0x1002 }
11-04 18:53:51.201 1115 1115 D SettingsInterface: from settings cache , name = three_gesture_screenshot , value = null
11-04 18:53:51.201 1115 1115 D SettingsInterface: from settings cache , name = is_show_three_gesture_alert , value = null
11-04 18:53:5Traceback (most recent call last):
File "/home/jovan/anaconda3/envs/kivy/bin/buildozer", line 10, in
sys.exit(main())
File "/home/jovan/anaconda3/envs/kivy/lib/python3.7/site-packages/buildozer/scripts/client.py", line 13, in main
Buildozer().run_command(sys.argv[1:])
File "/home/jovan/anaconda3/envs/kivy/lib/python3.7/site-packages/buildozer/init.py", line 1044, in run_command
self.target.run_commands(args)
File "/home/jovan/anaconda3/envs/kivy/lib/python3.7/site-packages/buildozer/target.py", line 92, in run_commands
func(args)
File "/home/jovan/anaconda3/envs/kivy/lib/python3.7/site-packages/buildozer/targets/android.py", line 1223, in cmd_logcat
show_output=True)
File "/home/jovan/anaconda3/envs/kivy/lib/python3.7/site-packages/buildozer/init.py", line 316, in cmd
stderr.write(chunk.decode('utf-8'))
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 77317: invalid continuation byte**
```

_Originally posted by @tsrift in https://github.com/kivy/python-for-android/issues/1987#issuecomment-554145167_

**Comment by Julian-O** [comment]
Could this be a buildozer bug?
