### ISSUE TITLE
ft2font build error with Matplotlib

### ISSUE THREAD

**Issue by marcets** [kivy/python-for-android#2058]
I'm trying to use matplotlib in my kivy app but I'm not able to create my .apk file. I got an error for matplotlib.ft2font build

I'm using "setup_testapp_python3_matplotlib.py" in your test_apps, but I changed the NDK (crystax 10.3.2) for the latest version of NDK "r21". I also use Matplotlib 2.1.2 and I changed the path file in the recipes to match to this version.  The reason I'm using Matplotlib 2.1.2 is because I also have problem with kiwisolver module (see buildozer issue #1003).

See my setup_testapp_python3_matplotlib.py below:

```
from distutils.core import setup
from setuptools import find_packages

options = {'apk': {'requirements': 'python3,sdl2,matplotlib,pyparsing,cycler,python-dateutil,numpy,kivy',
                   'android-api': 27,
                   'ndk-api': 21,
                   'dist-name': 'matplotlib_testapp',
                   'ndk-dir': '/home/kivy/.buildozer/android/platform/android-ndk-r21',			
                   'sdk-dir': '/home/kivy/.buildozer/android/platform/android-sdk',
                   }}

package_data = {'': ['*.py',
                     '*.png']
                }

packages = find_packages()
print('packages are', packages)

setup(
    name='matplotlib_testapp',
    version='0.1',
    description='p4a setup.py test',
    author='Alexander Taylor',
    author_email='alexanderjohntaylor@gmail.com',
    packages=find_packages(),
    options=options,
    package_data={'testapp_matplotlib': ['*.py', '*.png']}
)
```

* Python: 3.6
* OS: LUbuntu 18.04
* Kivy: 1.11.1

This is my error code:

```
[INFO]:    Building matplotlib for armeabi-v7a
[INFO]:    matplotlib apparently isn't already in site-packages
[INFO]:    Building compiled components in matplotlib
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/matplotlib-python3/armeabi-v7a__ndk_target_21/matplotlib
[INFO]:    -> running python3 setup.py build_ext -v
           working: error: command '/usr/bin/ccache' failed ...(and 18 more) Exception in thread background thread for pid 19165:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh-1.12.14-py3.6.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/kivy/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [2.1.2]
                python: yes [3.7.1 (default, Feb  3 2020, 19:20:39)  [GCC
                        8.3.0]]
              platform: yes [linux]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [not found. pip may install it below.]
                   six: yes [six was not found.pip will attempt to install
                        it after matplotlib.]
              dateutil: yes [dateutil was not found. It is required for date
                        axis support. pip/easy_install may attempt to
                        install it after matplotlib.]
backports.functools_lru_cache: yes [Not required]
          subprocess32: yes [Not required]
                  pytz: yes [pytz was not found. pip/easy_install may
                        attempt to install it after matplotlib.]
                cycler: yes [cycler was not found. pip/easy_install may
                        attempt to install it after matplotlib.]
               tornado: yes [tornado was not found. It is required for the
                        WebAgg backend. pip/easy_install may attempt to
                        install it after matplotlib.]
             pyparsing: yes [pyparsing was not found. It is required for
                        mathtext support. pip/easy_install may attempt to
                        install it after matplotlib.]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: yes [version 2.8.1]
                   png: yes [version 1.6.34]
                 qhull: yes [pkg-config information for 'libqhull' could not
                        be found. Using local copy.]

OPTIONAL SUBPACKAGES
           sample_data: no  [skipping due to configuration]
              toolkits: yes [installing]
                 tests: no  [skipping due to configuration]
        toolkits_tests: no  [skipping due to configuration]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [skipping due to configuration]
                qt5agg: no  [PySide2 not found; PyQt5 not found]
                qt4agg: no  [skipping due to configuration]
               gtk3agg: no  [skipping due to configuration]
             gtk3cairo: no  [skipping due to configuration]
                gtkagg: no  [Requires pygtk]
                 tkagg: no  [Disabled by patching during Android build]
                 wxagg: no  [skipping due to configuration]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [skipping due to configuration]
             windowing: no  [skipping due to configuration]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: yes [version 9.26]
                 latex: no
               pdftops: yes [version 0.62.0]

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]


running build_ext
building 'matplotlib.ft2font' extension
/usr/bin/ccache /home/kivy/.buildozer/android/platform/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -I/home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include -DANDROID -D__ANDROID_API__=21 -I/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/arm-linux-androideabi -I/home/kivy/.local/share/python-for-android/build/python-installs/matplotlib_testapp/include/python3.7 -I/home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include -fPIC -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -I/home/kivy/.local/share/python-for-android/build/other_builds/matplotlib-python3/armeabi-v7a__ndk_target_21/matplotlib/.eggs/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/core/include -I/usr/include/libpng16 -I/usr/include/freetype2 -I/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include -I. -I/home/kivy/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/kivy/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c src/ft2font.cpp -o build/temp.linux-x86_64-3.7/src/ft2font.o
/usr/bin/ccache /home/kivy/.buildozer/android/platform/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -I/home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include -DANDROID -D__ANDROID_API__=21 -I/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/arm-linux-androideabi -I/home/kivy/.local/share/python-for-android/build/python-installs/matplotlib_testapp/include/python3.7 -I/home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include -fPIC -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -I/home/kivy/.local/share/python-for-android/build/other_builds/matplotlib-python3/armeabi-v7a__ndk_target_21/matplotlib/.eggs/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/core/include -I/usr/include/libpng16 -I/usr/include/freetype2 -I/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include -I. -I/home/kivy/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/kivy/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c src/ft2font_wrapper.cpp -o build/temp.linux-x86_64-3.7/src/ft2font_wrapper.o
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:42:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:39:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/bits/pthread_types.h:38:3: error: unknown type name 'size_t'
  size_t stack_size;
  ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/bits/pthread_types.h:39:3: error: unknown type name 'size_t'
  size_t guard_size;
  ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:116:1: error: unknown type name 'size_t'; did you mean 'ssize_t'?
size_t fread(void* __buf, size_t __size, size_t __count, FILE* __fp);
^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:116:27: error: unknown type name 'size_t'; did you mean 'ssize_t'?
size_t fread(void* __buf, size_t __size, size_t __count, FILE* __fp);
                          ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:116:42: error: unknown type name 'size_t'; did you mean 'ssize_t'?
size_t fread(void* __buf, size_t __size, size_t __count, FILE* __fp);
                                         ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:118:1: error: unknown type name 'size_t'; did you mean 'ssize_t'?
size_t fwrite(const void* __buf, size_t __size, size_t __count, FILE* __fp);
^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:118:34: error: unknown type name 'size_t'; did you mean 'ssize_t'?
size_t fwrite(const void* __buf, size_t __size, size_t __count, FILE* __fp);
                                 ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:118:49: error: unknown type name 'size_t'; did you mean 'ssize_t'?
size_t fwrite(const void* __buf, size_t __size, size_t __count, FILE* __fp);
                                                ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:123:37: error: unknown type name 'size_t'; did you mean 'ssize_t'?
ssize_t getdelim(char** __line_ptr, size_t* __line_length_ptr, int __delimiter, FILE* __fp) __INTRODUCED_IN(18);
                                    ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:124:36: error: unknown type name 'size_t'; did you mean 'ssize_t'?
ssize_t getline(char** __line_ptr, size_t* __line_length_ptr, FILE* __fp) __INTRODUCED_IN(18);
                                   ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:137:50: error: unknown type name 'size_t'; did you mean 'ssize_t'?
int setvbuf(FILE* __fp, char* __buf, int __mode, size_t __size);
                                                 ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:299:27: error: unknown type name 'size_t'; did you mean 'ssize_t'?
int snprintf(char* __buf, size_t __size, const char* __fmt, ...) __printflike(3, 4);
                          ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:302:28: error: unknown type name 'size_t'; did you mean 'ssize_t'?
int vsnprintf(char* __buf, size_t __size, const char* __fmt, va_list __args) __printflike(3, 0);
                           ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:25:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/stdio.h:107:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/stdio.h:333:26: error: unknown type name 'size_t'; did you mean 'ssize_t'?
char* fgetln(FILE* __fp, size_t* __length_ptr);
                         ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
/home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:27:5: error: "Python.h requires that stdio.h define NULL."
#   error "Python.h requires that stdio.h define NULL."
    ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:30:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/string.h:60:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/string.h:36:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/bits/strcasecmp.h:68:53: error: unknown type name 'size_t'; did you mean 'ssize_t'?
int strncasecmp(const char* __s1, const char* __s2, size_t __n) __attribute_pure__;
                                                    ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:30:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/string.h:60:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/string.h:41:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/strings.h:56:81: error: unknown type name 'size_t'; did you mean 'ssize_t'?
static __inline__ __always_inline void __bionic_bcopy(const void* b1, void* b2, size_t len) {
                                                                                ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:30:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/string.h:60:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/string.h:41:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/strings.h:62:64: error: unknown type name 'size_t'; did you mean 'ssize_t'?
static __inline__ __always_inline void __bionic_bzero(void* b, size_t len) {
                                                               ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
In file included from src/ft2font_wrapper.cpp:1:
In file included from src/mplutils.h:31:
In file included from /home/kivy/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:30:
In file included from /home/kivy/.buildozer/android/platform/android-ndk-r21/sources/cxx-stl/llvm-libc++/include/string.h:60:
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/string.h:44:64: error: unknown type name 'size_t'; did you mean 'ssize_t'?
void* memccpy(void* __dst, const void* __src, int __stop_char, size_t __n);
                                                               ^
/home/kivy/.buildozer/android/platform/android-ndk-r21/sysroot/usr/include/sys/types.h:128:26: note: 'ssize_t' declared here
typedef __kernel_ssize_t ssize_t;
                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
error: command '/usr/bin/ccache' failed with exit status 1
```

**Comment by marcets** [comment]
I have solved my problem by installing "apt install python-openssl". I also applied the patch from buildozer issue #1003 and used matplolitb 3.0.3 (original recipes).

I was able to compile my code, but it crash with android.
ImportError: dlopen failed: cannot locate symbol "_ZNSt12length_errorD1Ev" referenced by "/data/data/org.rheolution.kivy_plot/files/app/_python_bundle/site-packages/matplotlib/_path.so"

But this is an other issue.
