### ISSUE TITLE
virtualenv not entering

### ISSUE THREAD

**Issue by emanuele-f** [kivy/python-for-android#212]
When I add pure python package dependecies and run distribute script I get

```
Installing collected packages: eyeD3, suds, python-magic
  Found existing installation: eyeD3 0.6.18
    Uninstalling eyeD3:
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1294, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 525, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1639, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 294, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/eyeD3-0.6.18-py2.7.egg-info'
```
It seems like virtual env is not entered, probably a subshell related issue

**Comment by FeralBytes** [comment]
Seems resolved.
