### ISSUE TITLE
Platform linux on some android devices

### ISSUE THREAD

**Issue by sergiomorillo** [kivy/python-for-android#2163]
### Versions

* python-for-android: 3.8.
* Kivy: master (2.0.0rc1)

### Description

Last week I had to rebuild a kivy app that was working in many android devices. I normally do it with buildozer docker image.
I was able to create the apk again and it works as expected ... in some devices! In other ones the app crashes during splash screen due to a PermissionError. 
After debugging with adb logcat I noticed kivy is not recognizing the platform correctly as it return 'linux' instead of 'android'.
This causes that [ANDROID_APP_PATH is not used](https://github.com/kivy/kivy/blob/b6eddbb2fcf97a21b7f0c4cfbf0d8ccdb74fb3ec/kivy/__init__.py#L339) and it tries to write on /data/ path.

I'm using kivy==master on buildozer.spec.

### Logs

```
04-27 14:54:56.946  7788  7807 I python  : Android kivy bootstrap done. name is main
04-27 14:54:56.946  7788  7807 I python  : AND: Ran string
04-27 14:54:56.946  7788  7807 I python  : Run user program, change dir and execute entrypoint
04-27 14:54:57.303  7788  7807 I python  :  Traceback (most recent call last):
04-27 14:54:57.303  7788  7807 I python  :    File "/home/user/hostcwd/.buildozer/android/app/main.py", line 10, in <module>
04-27 14:54:57.304  7788  7807 I python  :    File "/home/user/hostcwd/.buildozer/android/app/app.py", line 4, in <module>
04-27 14:54:57.305  7788  7807 I python  :    File "/home/use
r/hostcwd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/__init__.py", line 351, in <module>
04-27 14:54:57.306  7788  7807 I python  :  PermissionError: [Errno 13] Permission denied: '/data/.kivy'
04-27 14:54:57.306  7788  7807 I python  : Python for android ended.
```

**Comment by sergiomorillo** [comment]
> In other ones the app crashes during splash screen due to a PermissionError.

Some models in which app crashes:
* Xiaomi Mi A2 Lite
* Samsung Galaxy S8

**Comment by AndreMiras** [comment]
Thanks for the bug report. That could be related to https://github.com/kivy/kivy/pull/6798
@misl6 and @opacam have confirmed the bug.
Could you try to revert build prior that commit and see if it solves the bug?
I'm transferring out the issue to kivy/kivy
