### ISSUE TITLE
build failed.

### ISSUE THREAD

**Issue by foocker** [kivy/python-for-android#2212]
### Versions

* Python:3.7.6, in anaconda3 env
* OS:ubuntu18.04
* Kivy:1.11.1
* Cython:0.29.16

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?
i have do some efforts, but failed.
A simple button  app, but has some python extral package to install such as python-opencv, numpy etc. i did it in my anaconda3 environment and oppsite, the same wrong as follows. i just want to build successed. thx!!!

### buildozer.spec

Command:
```sh
sh bash script, not buildozer.spec
p4a apk --private $HOME/demoapp \
--package=demoapp --name="My Hello World on Android" \
--name "My application" \
--version 0.0 \
--bootstrap=sdl2 \
--requirements=python3.7.6,kivy,opencv-python==3.4.2.16,opencv-contrib-python=3.4.2.16,faiss-cpu,swig,openblas,numpy=1.18.1 \
--arch=arm64-v8a \
# --arch=armeabiv-v7a
--dist_name=MyDemoProject_2 \
--ndk_dir=$ANDROIDNDK --sdk_dir=$ANDROIDSDK \
# --release
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
... some common INFO ....
[INFO]:    kivy said it is already built, skipping
[INFO]:    # Biglinking object files
[WARNING]: Context's python recipe found, skipping biglink (will this work?)
[INFO]:    # Postbuilding recipes
[INFO]:    Postbuilding hostpython3 for arm64-v8a
[INFO]:    Postbuilding libffi for arm64-v8a
[INFO]:    Postbuilding openssl for arm64-v8a
[INFO]:    Postbuilding sdl2_image for arm64-v8a
[INFO]:    Postbuilding sdl2_mixer for arm64-v8a
[INFO]:    Postbuilding sdl2_ttf for arm64-v8a
[INFO]:    Postbuilding sqlite3 for arm64-v8a
[INFO]:    Postbuilding python3 for arm64-v8a
[INFO]:    Postbuilding sdl2 for arm64-v8a
[INFO]:    Postbuilding setuptools for arm64-v8a
[INFO]:    Postbuilding six for arm64-v8a
[INFO]:    Postbuilding pyjnius for arm64-v8a
[INFO]:    Copying pyjnius java class to classes build dir
[INFO]:    -> directory context /root/.local/share/python-for-android/build/other_builds/pyjnius-sdl2/arm64-v8a__ndk_target_21/pyjnius
[INFO]:    -> running cp -a jnius/src/org /root/.local/share/python-for-android/build/javaclasses/unnamed_dist_1
[INFO]:    <- directory context /root/Codes/Synthesize/Kivy
[INFO]:    Postbuilding android for arm64-v8a
[INFO]:    Postbuilding kivy for arm64-v8a
[INFO]:    # Installing pure Python modules
[INFO]:    *** PYTHON PACKAGE / PROJECT INSTALL STAGE ***
[INFO]:    The requirements (certifi, faiss-cpu, numpy=1.18.1, openblas, opencv-contrib-python=3.4.2.16, opencv-python, python3.7.6, swig) don't have recipes, attempting to install them with pip
[INFO]:    If this fails, it may mean that the module has compiled components and needs a recipe.
[INFO]:    -> directory context /root/.local/share/python-for-android/build
[INFO]:    -> running python3 -m venv venv
[INFO]:    Upgrade pip to latest version
[INFO]:    -> running bash -c source venv/bin/activate && pip install -U pip
[INFO]:    Install Cython in case one of the modules needs it to build                                                                               
[INFO]:    -> running bash -c venv/bin/pip install Cython
           working: Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/pip/: There was a problem confirming the ssl certi...(and 219 more) Exception in thread background thread for pid 17688:
Traceback (most recent call last):
  File "/root/anaconda3/envs/mmretina/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/mmretina/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/sh.py", line 2606, in background_thread
    handle_exit_code(exit_code)
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/sh.py", line 2304, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /bin/bash -c 'venv/bin/pip install Cython'

  STDOUT:
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting Cython
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/cython/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/cython/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement Cython (from versions: none)
ERROR: No matching distribution found for Cython
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping


  STDERR:


Traceback (most recent call last):                                                                                                                   
  File "/root/anaconda3/envs/mmretina/bin/p4a", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 688, in __init__
    getattr(self, command)(args)
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 154, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 208, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/pythonforandroid/build.py", line 598, in build_recipes
    ignore_setup_py=ignore_project_setup_py
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/pythonforandroid/build.py", line 778, in run_pymodules_install
    ), _env=copy.copy(base_env))
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/sh.py", line 925, in next
    self.wait()
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/sh.py", line 849, in wait
    self.handle_command_exit_code(exit_code)
  File "/root/anaconda3/envs/mmretina/lib/python3.7/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /bin/bash -c 'venv/bin/pip install Cython'

  STDOUT:
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting Cython
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/cython/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/cython/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement Cython (from versions: none)
ERROR: No matching distribution found for Cython
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping


  STDERR:

main.sh: 12: main.sh: --dist_name=MyDemoProject_2: not found
```

**Comment by AndreMiras** [comment]
The error is `Can't connect to HTTPS URL because the SSL module is not available.` this is a dup bug. Please use the search or Discord for support
