### ISSUE TITLE
Pillow with kivy and kivymd error ImportError: dlopen failed: cannot locate symbol "log" referenced by "_imaging.so"...

### ISSUE THREAD

**Issue by Sahil-pixel** [kivy/python-for-android#2317]
### Checklist

- [ ] the issue is indeed a bug and not a support request
- [ ] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [ ] I have a short, runnable example that reproduces the issue
- [ ] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [ ] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python:3.6.9
- OS:kubuntu 18.04
- Kivy:1.11.1
-kivymd:0.104.1
- Cython:0.29.19
- OpenJDK:8

### Description

I installed app in android 5.1 and when i launch the apk it crashes 

### buildozer.spec

Command:
```sh
buildozer -v android debug
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
// Keep the triple grave accent (aka backquote/backtick) to have the code formatted
```

Spec file:

```
[app]

# (str) Title of your application
title = Image edit

# (str) Package name
package.name = image_edit

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
# version.regex = __version__ = '(.*)'
# version.filename = %(source.dir)s/main.py

# (str) Application versioning (method 2)
version = 1.0

# (list) Application requirements
requirements =  hostpython3==3.7.5,python3==3.7.5,kivy,kivymd==0.104.1,Pillow,freetype,png,jpeg,setuptools,android,pyjnius

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0


#
# Android specific
#

# (list) Permissions
android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,CAMERA



# (int) Android API to use
#android.api = 14

# (int) Minimum API required (8 = Android 2.2 devices)
#android.minapi = 8

# (int) Android SDK version to use
#android.sdk = 21

# (str) Android NDK version to use
#android.ndk = 9

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path = 

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters = 

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

#
# iOS specific
#

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2


# -----------------------------------------------------------------------------
# List as sections
# 
# You can define all the "list" as [section:key].
# Each line will be considered as a option to the list.
# Let's take [app] / source.exclude_patterns.
# Instead of doing:
#
#     [app]
#     source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
# This can be translated into:
#
#     [app:source.exclude_patterns]
#     license
#     data/audio/*.wav
#     data/images/original/*
#


# -----------------------------------------------------------------------------
# Profiles
#
# You can extend section / key with a profile
# For example, you want to deploy a demo version of your application without
# HD content. You could first change the title to add "(demo)" in the name
# and extend the excluded directories to remove the HD content.
#
#     [app@demo]
#     title = My Application (demo)
#
#     [app:source.exclude_patterns@demo]
#     images/hd/*
#
# Then, invoke the command line with the "demo" profile:
#
#     buildozer --profile demo android debug

```

### Logs

```
// REPLACE ME: Paste the build output containing the error
 I/python  (17867): Initializing Python for Android
I/python  (17867): Setting additional env vars from p4a_env_vars.txt
I/python  (17867): Changing directory to the one provided by ANDROID_ARGUMENT
I/python  (17867): /data/data/org.test.image_edit/files/app
I/python  (17867): Preparing to initialize python
I/python  (17867): _python_bundle dir exists
I/python  (17867): calculated paths to be...
I/python  (17867): /data/data/org.test.image_edit/files/app/_python_bundle/stdlib.zip:/data/data/org.test.image_edit/files/app/_python_bundle/modules
I/python  (17867): set wchar paths...
I/python  (17867): Initialized python
I/python  (17867): AND: Init threads
I/python  (17867): testing python print redirection
I/python  (17867): Android path ['.', '/data/data/org.test.image_edit/files/app/_python_bundle/stdlib.zip', '/data/data/org.test.image_edit/files/app/_python_bundle/modules', '/data/data/org.test.image_edit/files/app/_python_bundle/site-packages']
I/python  (17867): os.environ is environ({'PATH': '/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'ASEC_MOUNTPOINT': '/mnt/asec', 'LOOP_MOUNTPOINT': '/mnt/obb', 'BOOTCLASSPATH': '/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar', 'USBOTG_STORAGE': '/storage/usbotg', 'LD_PRELOAD': 'libdirect-coredump.so', 'EXTERNAL_STORAGE': '/storage/emulated/legacy', 'SECONDARY_STORAGE': '/storage/sdcard1', 'EMULATED_STORAGE_SOURCE': '/mnt/shell/emulated', 'EMULATED_STORAGE_TARGET': '/storage/emulated', 'ANDROID_PROPERTY_WORKSPACE': '9,0', 'ANDROID_SOCKET_zygote': '10', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/data/org.test.image_edit/files/app', 'ANDROID_APP_PATH': '/data/data/org.test.image_edit/files/app', 'ANDROID_PRIVATE': '/data/data/org.test.image_edit/files', 'ANDROID_UNPACK': '/data/data/org.test.image_edit/files/app', 'PYTHONHOME': '/data/data/org.test.image_edit/files/app', 'PYTHONPATH': '/data/data/org.test.image_edit/files/app:/data/data/org.test.image_edit/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
I/python  (17867): Android kivy bootstrap done. __name__ is __main__
I/python  (17867): AND: Ran string
I/python  (17867): Run user program, change dir and execute entrypoint
I/python  (17867): [INFO   ] [Logger      ] Record log in /data/data/org.test.image_edit/files/app/.kivy/logs/kivy_20-09-17_77.txt
I/python  (17867): [INFO   ] [Kivy        ] v1.11.1
I/python  (17867): [INFO   ] [Kivy        ] Installed at "/data/data/org.test.image_edit/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
I/python  (17867): [INFO   ] [Python      ] v3.7.5 (default, Sep 16 2020, 17:54:52) 
I/python  (17867): [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
I/python  (17867): [INFO   ] [Python      ] Interpreter at "android_python"
I/python  (17867): [INFO   ] [KivyMD      ] v0.104.1
I/python  (17867): [INFO   ] [Factory     ] 184 symbols loaded
I/python  (17867): [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
I/python  (17867): [INFO   ] [Window      ] Provider: sdl2
I/python  (17867): [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
I/python  (17867): [INFO   ] [GL          ] Backend used <sdl2>
I/python  (17867): [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
I/python  (17867): [INFO   ] [GL          ] OpenGL vendor <b'ARM'>
I/python  (17867): [INFO   ] [GL          ] OpenGL renderer <b'Mali-400 MP'>
I/python  (17867): [INFO   ] [GL          ] OpenGL parsed version: 2, 0
I/python  (17867): [INFO   ] [GL          ] Texture max size <4096>
I/python  (17867): [INFO   ] [GL          ] Texture max units <8>
I/python  (17867): [INFO   ] [Window      ] auto add sdl2 input provider
I/python  (17867): [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
I/python  (17867): [INFO   ] [Text        ] Provider: sdl2
I/python  (17867): [INFO   ] [GL          ] NPOT texture support is available
I/python  (17867):  Traceback (most recent call last):
I/python  (17867):    File "/home/sahil/firstapp/.buildozer/android/app/main.py", line 15, in <module>
I/python  (17867):    File "/home/sahil/firstapp/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/image_edit/PIL/Image.py", line 69, in <module>
I/python  (17867):  ImportError: dlopen failed: cannot locate symbol "log" referenced by "_imaging.so"...
I/python  (17867): Python for android ended.


// Keep the triple grave accent (a.k.a. backquote/backtick) to have the code formatted
```

**Comment by Adonis35** [comment]
Did you find a resolution for this?

**Comment by Sahil-pixel** [comment]
https://github.com/kivy/buildozer/issues/1020

**Comment by oukiar** [comment]
the solution is edit the file `/home/oscar/mobox/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/Pillow/__init__.py` and add the math lib to the line containing LIBS:
`
env['LIBS'] = ' -lpng -lfreetype -lharfbuzz -ljpeg -lturbojpeg -lm'
`

try again rebuilding the apk
```
buildozer android clean
buildozer android debug
```
