### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by CA1R7** [kivy/python-for-android#2321]
### Versions

- Python: 3.8.4rc1
- OS: windows 10 x64 system

Command:
i did try `p4a` and `python-for-android` but same trouble.

### Logs
my logs
```
Traceback (most recent call last):
  File "c:\users\aaami\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\aaami\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\aaami\AppData\Local\Programs\Python\Python38\Scripts\python-for-android.exe\__main__.py", line 4, in <module>
  File "c:\users\aaami\appdata\local\programs\python\python38\lib\site-packages\pythonforandroid\entrypoints.py", line 1, in <module>
    from pythonforandroid.recommendations import check_python_version
  File "c:\users\aaami\appdata\local\programs\python\python38\lib\site-packages\pythonforandroid\recommendations.py", line 7, in <module>
    from pythonforandroid.logger import info, warning
  File "c:\users\aaami\appdata\local\programs\python\python38\lib\site-packages\pythonforandroid\logger.py", line 4, in <module>
    import sh
  File "c:\users\aaami\appdata\local\programs\python\python38\lib\site-packages\sh.py", line 36, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by RobertFlatt** [comment]
Python for Android does not run on a native Windows shell. 
Use Windows Subsystem for Linux (Ubuntu is a good choice). 
https://python-for-android.readthedocs.io/en/latest/quickstart/#installation

Also consider Buildozer a wrapper around p4a that handles the Google dependencies.
https://buildozer.readthedocs.io/en/latest/installation.html

**Comment by CA1R7** [comment]
@RobertFlatt uh ok thank you
