### ISSUE TITLE
Gradle Problem

### ISSUE THREAD

**Issue by xcodz-dot** [kivy/python-for-android#2352]
### Checklist

- [x] the issue is indeed a bug and not a support request
- [x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [x] I have a short, runnable example that reproduces the issue
- [ ] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [ ] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: 3.8
- OS: Ubunto 20.04
- Kivy: Not Installed
- Cython: 0.29.21
- OpenJDK: 1.8.0_272

### Description

I was trying to build a simple Flask App to test the tool

It had this directory structure
```
test
+--MyApp
   +--main.py
```
I ran the command in test directory

content of main.py:
```python
import flask

app = flask.Flask("MySampleApp")


@app.route('/')
def home():
	return """
<html>
<head>
	<title> Android Flask Hello 23 Sample </title>
</head>
<body>
	Hello World with p4a on Android
</body>
</html>
"""

app.run(host="127.0.0.1", port=5364)
```

Command:

It did not ran any command but a command i used is this:
`p4a apk --private MyApp --package=test.xcodz.webpy --name "FlaskWEBTEST" --requirements flask --bootstrap=webview --dist_name FlaskXcodzWebTest --version 1.0.0 --arch x86 --permission INTERNET --port 5364`

Spec file:
No Spec file was generated

### Logs

Log is big so i have attached it as a file
[log.txt](https://github.com/kivy/python-for-android/files/5528349/log.txt)

**Comment by obfusk** [comment]
Have you tried using the latest development version (`p4a.branch = develop`)?

**Comment by xcodz-dot** [comment]
noop, i will try soon

**Comment by xcodz-dot** [comment]
```
xcodz@xcodz-iBall-CompBook-Marvel6-V3:~/test/flaskapp$ p4a apk --private MyApp --package=test.xcodz.webpy --name "FlaskWEBTEST" --requirements flask --bootstrap=webview --dist_name FlaskXcodzWebTest --version 1.0.0 --arch x86 --permission INTERNET --port 5364
[WARNING]: $ANDROIDNDKVER is deprecated and no longer necessary, the value you set is ignored
[INFO]:    Will compile for the following archs: x86
[INFO]:    Found Android API target in $ANDROIDAPI: 27
Traceback (most recent call last):
  File "/home/xcodz/.local/bin/p4a", line 8, in <module>
    sys.exit(main())
  File "/home/xcodz/.local/lib/python3.8/site-packages/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/xcodz/.local/lib/python3.8/site-packages/pythonforandroid/toolchain.py", line 715, in __init__
    getattr(self, command)(args)
  File "/home/xcodz/.local/lib/python3.8/site-packages/pythonforandroid/toolchain.py", line 143, in wrapper_func
    ctx.prepare_build_environment(user_sdk_dir=self.sdk_dir,
  File "/home/xcodz/.local/lib/python3.8/site-packages/pythonforandroid/build.py", line 300, in prepare_build_environment
    apis = get_available_apis(self.sdk_dir)
  File "/home/xcodz/.local/lib/python3.8/site-packages/pythonforandroid/build.py", line 74, in get_available_apis
    targets = get_targets(sdk_dir)
  File "/home/xcodz/.local/lib/python3.8/site-packages/pythonforandroid/build.py", line 62, in get_targets
    targets = avdmanager('list', 'target').stdout.decode('utf-8').split('\n')
  File "/home/xcodz/.local/lib/python3.8/site-packages/sh.py", line 1520, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/xcodz/.local/lib/python3.8/site-packages/sh.py", line 784, in __init__
    self.wait()
  File "/home/xcodz/.local/lib/python3.8/site-packages/sh.py", line 841, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/xcodz/.local/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/xcodz/android/sdk/tools/bin/avdmanager list target

  STDOUT:


  STDERR:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

It seems like i have encountered a new error

**Comment by obfusk** [comment]
> It seems like i have encountered a new error

That error seems to come from `avdmanager`, not p4a. Maybe there's something wrong with your android SDK setup?

I'd recommend using `buildozer` instead of using p4a directly. It will also handle installing the SDK for you.

**Comment by xcodz-dot** [comment]
thanks anyways, i will better learn kotlin
