### ISSUE TITLE
pyyaml recipe not available

### ISSUE THREAD

**Issue by elaith9** [kivy/python-for-android#2448]
I'm finding discussion about pyaaml recipe in the past but there is no actual folder with recipe. Only pyaml. Does anyone know why is that? I really need that one.

I tried to create my own but it keeps failing for some reason.
Here is the recipe:

```
from pythonforandroid.recipe import PythonRecipe

class PyYAMLRecipe(PythonRecipe):
    version = "5.3.1"
    url = 'http://pyyaml.org/download/pyyaml/PyYAML-{version}.tar.gz'
    depends = ["setuptools"]

recipe = PyYAMLRecipe()

```
And whole output:
```
[WARNING]:   **** FUTURE BEHAVIOR CHANGE WARNING ****
[WARNING]: Your project appears to contain a setup.py file.
[WARNING]: Currently, these are ignored by default.
[WARNING]: This will CHANGE in an upcoming version!
[WARNING]: 
[WARNING]: To ensure your setup.py is ignored, please specify:
[WARNING]:     --ignore-setup-py
[WARNING]: 
[WARNING]: To enable what will some day be the default, specify:
[WARNING]:     --use-setup-py
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Getting Android API version from user argument: 27
[INFO]:    Available Android APIs are (27)
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Getting NDK dir from from user argument
[INFO]:    Found NDK version 19b
[WARNING]: NDK API target was not set manually, using the default of 21 = min(android-api=27, default ndk-api=21)
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['certifi', 'dataclasses', 'editdistance', 'future', 'hostpython3', 'libffi', 'mkl', 'mkl-include', 'ninja', 'openssl', 'panphon', 'requests', 'resampy', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'typing_extensions', 'python3', 'sdl2', 'setuptools', 'cython', 'pycparser', 'pyyaml', 'six', 'cffi', 'numpy', 'pyjnius', 'android', 'kivy', 'torch', 'allosaurus']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name unnamed_dist_1 and requirements (python3, kivy, numpy, certifi, torch, allosaurus)
[INFO]:    Dist contains the following requirements as recipes: ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'cython', 'pycparser', 'pyyaml', 'six', 'cffi', 'numpy', 'pyjnius', 'android', 'kivy', 'torch', 'allosaurus']
[INFO]:    Dist will also contain modules (typing_extensions, editdistance, ninja, mkl-include, future, requests, resampy, panphon, certifi, mkl, dataclasses) installed from pip
[INFO]:    Dist will be build in mode debug
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/bootstrap_builds/sdl2
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Recipe build order is ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'cython', 'pycparser', 'pyyaml', 'six', 'cffi', 'numpy', 'pyjnius', 'android', 'kivy', 'torch', 'allosaurus']
[INFO]:    The requirements (certifi, dataclasses, editdistance, future, mkl, mkl-include, ninja, panphon, requests, resampy, typing_extensions) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 31 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/hostpython3
[INFO]:    -> running basename https://www.python.org/ftp/pytho...(and 24 more)
[INFO]:    hostpython3 download already cached, skipping                                 
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading libffi
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 26 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/libffi
[INFO]:    -> running basename https://github.com/libffi/libffi...(and 20 more)
[INFO]:    libffi download already cached, skipping                                      
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 27 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/openssl
[INFO]:    -> running basename https://www.openssl.org/source/o...(and 20 more)
[INFO]:    openssl download already cached, skipping                                     
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 30 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects...(and 42 more)
[INFO]:    sdl2_image download already cached, skipping                                  
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 30 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects...(and 42 more)
[INFO]:    sdl2_mixer download already cached, skipping                                  
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 28 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/...(and 38 more)
[INFO]:    sdl2_ttf download already cached, skipping                                    
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading sqlite3
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 27 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/sqlite3
[INFO]:    -> running basename https://www.sqlite.org/2021/sqli...(and 27 more)
[INFO]:    sqlite3 download already cached, skipping                                     
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading python3
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 27 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/python3
[INFO]:    -> running basename https://www.python.org/ftp/pytho...(and 24 more)
[INFO]:    python3 download already cached, skipping                                     
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 24 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
[INFO]:    sdl2 download already cached, skipping                                        
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading setuptools
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 30 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/setuptools
[INFO]:    -> running basename https://pypi.python.org/package...(and 46 more)
[INFO]:    setuptools download already cached, skipping                                  
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading cython
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 26 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/cython
[INFO]:    -> running basename https://github.com/cython/cython...(and 23 more)
[INFO]:    cython download already cached, skipping                                      
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading pycparser
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 29 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/pycparser
[INFO]:    -> running basename https://pypi.python.org/package...(and 42 more)
[INFO]:    pycparser download already cached, skipping                                   
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading pyyaml
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 26 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/pyyaml
[INFO]:    -> running basename http://pyyaml.org/download/pyyam...(and 21 more)
[INFO]:    pyyaml download already cached, skipping                                      
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 23 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages...(and 31 more)
[INFO]:    six download already cached, skipping                                         
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading cffi
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 24 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/cffi
[INFO]:    -> running basename https://pypi.python.org/packages...(and 33 more)
[INFO]:    cffi download already cached, skipping                                        
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading numpy
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 25 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/numpy
[INFO]:    -> running basename https://pypi.python.org/packages...(and 32 more)
[INFO]:    numpy download already cached, skipping                                       
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 27 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/1.3.0.zip
[INFO]:    pyjnius download already cached, skipping                                     
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 24 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/2.0.0.zip
[INFO]:    kivy download already cached, skipping                                        
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading torch
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 25 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/torch
[INFO]:    -> running basename git+https://github.com/pytorch/pytorch.git
[INFO]:    -> running rm -f .mark-pytorch.git                                            
[INFO]:    Downloading torch from git+https://github.com/pytorch/pytorch.git
[INFO]:    -> directory context pytorch.git
[INFO]:    -> running git fetch --tags --recurse-submodules
[INFO]:    -> running git checkout v1.8.1                                                
[INFO]:    -> running git submodule update --recursive                                   
[INFO]:    <- directory context /home/user/.local/share/python-for-android/packages/torch
[INFO]:    -> running touch .mark-pytorch.git
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Downloading allosaurus
[INFO]:    -> running mkdir -p /home/user/.local/share/python-f...(and 30 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/packages/allosaurus
[INFO]:    -> running basename https://github.com/xinjli/allosa...(and 34 more)
[INFO]:    allosaurus download already cached, skipping                                  
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/pytho...(and 24 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/hostpython3/desktop
[INFO]:    hostpython3 is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking libffi for armeabi-v7a
[INFO]:    -> running basename https://github.com/libffi/libffi...(and 20 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/libffi/armeabi-v7a__ndk_target_21
[INFO]:    libffi is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.org/source/o...(and 20 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/openssl/armeabi-v7a__ndk_target_21
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects...(and 42 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/bootstrap_builds/sdl2/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects...(and 42 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/bootstrap_builds/sdl2/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/...(and 38 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/bootstrap_builds/sdl2/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking sqlite3 for armeabi-v7a
[INFO]:    -> running basename https://www.sqlite.org/2021/sqli...(and 27 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/sqlite3/armeabi-v7a__ndk_target_21
[INFO]:    sqlite3 is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking python3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/pytho...(and 24 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21
[INFO]:    python3 is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/bootstrap_builds/sdl2/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking setuptools for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/package...(and 46 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/setuptools/armeabi-v7a__ndk_target_21
[INFO]:    setuptools is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking cython for armeabi-v7a
[INFO]:    -> running basename https://github.com/cython/cython...(and 23 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/cython/armeabi-v7a__ndk_target_21
[INFO]:    cython is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking pycparser for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/package...(and 42 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/pycparser/armeabi-v7a__ndk_target_21
[INFO]:    pycparser is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking pyyaml for armeabi-v7a
[INFO]:    -> running basename http://pyyaml.org/download/pyyam...(and 21 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/pyyaml/armeabi-v7a__ndk_target_21
[INFO]:    -> running mv PyYAML-5.3.1 /home/user/.local/share/...(and 78 more)
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages...(and 31 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/six/armeabi-v7a__ndk_target_21
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking cffi for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages...(and 33 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/cffi/armeabi-v7a__ndk_target_21
[INFO]:    cffi is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking numpy for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages...(and 32 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/numpy/armeabi-v7a__ndk_target_21
[INFO]:    numpy is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/1.3.0.zip
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    -> running rm -rf /home/user/.local/share/python-fo...(and 76 more)
[INFO]:    -> running cp -a /home/user/app/pythonforandroid/re...(and 127 more)
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/2.0.0.zip
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/kivy/armeabi-v7a__ndk_target_21
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking torch for armeabi-v7a
[INFO]:    -> running basename git+https://github.com/pytorch/pytorch.git
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/torch/armeabi-v7a__ndk_target_21
[INFO]:    torch is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Unpacking allosaurus for armeabi-v7a
[INFO]:    -> running basename https://github.com/xinjli/allosa...(and 34 more)
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/allosaurus/armeabi-v7a__ndk_target_21
[INFO]:    allosaurus is already unpacked, skipping
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for hostpython3[armeabi-v7a]
[INFO]:    hostpython3 already patched, skipping
[INFO]:    Prebuilding libffi for armeabi-v7a
[INFO]:    libffi has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for libffi[armeabi-v7a]
[INFO]:    libffi already patched, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sqlite3 for armeabi-v7a
[INFO]:    sqlite3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3 for armeabi-v7a
[INFO]:    python3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python3[armeabi-v7a]
[INFO]:    python3 already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding setuptools for armeabi-v7a
[INFO]:    setuptools has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding cython for armeabi-v7a
[INFO]:    cython has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pycparser for armeabi-v7a
[INFO]:    pycparser has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyyaml for armeabi-v7a
[INFO]:    pyyaml has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding cffi for armeabi-v7a
[INFO]:    cffi has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for cffi[armeabi-v7a]
[INFO]:    cffi already patched, skipping
[INFO]:    Prebuilding numpy for armeabi-v7a
[INFO]:    numpy has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for numpy[armeabi-v7a]
[INFO]:    numpy already patched, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/android-sdl2/armeabi-v7a__ndk_target_21/android
[INFO]:    <- directory context /home/user/allosaurus
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding torch for armeabi-v7a
[INFO]:    torch has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding allosaurus for armeabi-v7a
[INFO]:    allosaurus has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[INFO]:    hostpython3 said it is already built, skipping
[INFO]:    Building libffi for armeabi-v7a
[INFO]:    libffi said it is already built, skipping
[INFO]:    -> running cp /home/user/.local/share/python-for-an...(and 174 more)
[INFO]:    Building openssl for armeabi-v7a
[INFO]:    openssl said it is already built, skipping
[INFO]:    -> running cp /home/user/.local/share/python-for-an...(and 300 more)
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building sqlite3 for armeabi-v7a
[INFO]:    sqlite3 said it is already built, skipping
[INFO]:    Building python3 for armeabi-v7a
[INFO]:    python3 said it is already built, skipping
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/bootstrap_builds/sdl2/jni
[INFO]:    -> running ndk-build V=1 NDK_DEBUG=1
[INFO]:    <- directory context /home/user/allosaurus                                    
[INFO]:    Building setuptools for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    setuptools said it is already built, skipping
[INFO]:    Building cython for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    cython said it is already built, skipping
[INFO]:    Building pycparser for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    pycparser said it is already built, skipping
[INFO]:    Building pyyaml for armeabi-v7a
[INFO]:    pyyaml apparently isn't already in site-packages
[INFO]:    Installing pyyaml into site-packages
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/pyyaml/armeabi-v7a__ndk_target_21/pyyaml
[INFO]:    -> running python3 setup.py install -O2 --root=/hom...(and 91 more)
[INFO]:    <- directory context /home/user/allosaurus                                    
[INFO]:    Building six for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    six said it is already built, skipping
[INFO]:    Building cffi for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    cffi said it is already built, skipping
[INFO]:    Building numpy for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    numpy said it is already built, skipping
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    pyjnius said it is already built, skipping
[INFO]:    Building android for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    android said it is already built, skipping
[INFO]:    Building kivy for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    kivy said it is already built, skipping
[INFO]:    Building torch for armeabi-v7a
[INFO]:    torch apparently isn't already in site-packages
[INFO]:    Installing torch into site-packages
[INFO]:    -> directory context /home/user/.local/share/python-for-android/build/other_builds/torch/armeabi-v7a__ndk_target_21/torch
[INFO]:    -> running python3 setup.py install -O2 --root=/hom...(and 91 more)
           working: Please install it via `conda install pyyaml` or `pip install pyyaml` Exception in thread background thread for pid 59755:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/app/venv/lib/python3.8/site-packages/sh.py", line 1637, in wrap
    fn(*rgs, **kwargs)
  File "/home/user/app/venv/lib/python3.8/site-packages/sh.py", line 2561, in background_thread
    handle_exit_code(exit_code)
  File "/home/user/app/venv/lib/python3.8/site-packages/sh.py", line 2265, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/user/app/venv/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/user/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/home/user/.local/share/python-for-android/build/python-installs/unnamed_dist_1 --install-lib=.

  STDOUT:
fatal: not a git repository (or any of the parent directories): .git
Building wheel torch-1.8.0a0+Unknown
-- Building version 1.8.0a0+Unknown
Traceback (most recent call last):
  File "setup.py", line 368, in check_pydep
    importlib.import_module(importname)
  File "/home/user/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Lib/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 313, in build_deps
    check_pydep('yaml', 'pyyaml')
  File "setup.py", line 370, in check_pydep
    raise RuntimeError(missing_pydep.format(importname=importname, module=module))
RuntimeError: Missing build dependency: Unable to `import yaml`.
Please install it via `conda install pyyaml` or `pip install pyyaml`


  STDERR:

Traceback (most recent call last):                                                       
  File "/home/user/app/venv/bin/p4a", line 11, in <module>
    load_entry_point('python-for-android', 'console_scripts', 'p4a')()
  File "/home/user/app/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/user/app/pythonforandroid/toolchain.py", line 725, in __init__
    getattr(self, command)(args)
  File "/home/user/app/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/user/app/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/user/app/pythonforandroid/build.py", line 580, in build_recipes
    recipe.build_arch(arch)
  File "/home/user/app/pythonforandroid/recipe.py", line 961, in build_arch
    self.install_python_package(arch)
  File "/home/user/app/pythonforandroid/recipe.py", line 977, in install_python_package
    shprint(hostpython, 'setup.py', 'install', '-O2',
  File "/home/user/app/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/user/app/venv/lib/python3.8/site-packages/sh.py", line 911, in next
    self.wait()
  File "/home/user/app/venv/lib/python3.8/site-packages/sh.py", line 841, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/user/app/venv/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/user/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/home/user/.local/share/python-for-android/build/python-installs/unnamed_dist_1 --install-lib=.

  STDOUT:
fatal: not a git repository (or any of the parent directories): .git
Building wheel torch-1.8.0a0+Unknown
-- Building version 1.8.0a0+Unknown
Traceback (most recent call last):
  File "setup.py", line 368, in check_pydep
    importlib.import_module(importname)
  File "/home/user/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Lib/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 313, in build_deps
    check_pydep('yaml', 'pyyaml')
  File "setup.py", line 370, in check_pydep
    raise RuntimeError(missing_pydep.format(importname=importname, module=module))
RuntimeError: Missing build dependency: Unable to `import yaml`.
Please install it via `conda install pyyaml` or `pip install pyyaml`


  STDERR:
  ```

**Comment by elaith9** [comment]
`from pythonforandroid.recipe import PythonRecipe


class PyYAMLRecipe(PythonRecipe):
    version = "5.3.1"
    url = 'http://pyyaml.org/download/pyyaml/PyYAML-{version}.tar.gz'
    depends = ["setuptools"]
    #site_packages_name = 'pyaml'
    #call_hostpython_via_targetpython = False

recipe = PyYAMLRecipe()`
