### ISSUE TITLE
ValueError: name is too long

### ISSUE THREAD

**Issue by Andrea055** [kivy/python-for-android#2517]
### Checklist

- [x] the issue is indeed a bug and not a support request
- [x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [x] I have a short, runnable example that reproduces the issue
- [x] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [x] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: 3.8.10
- OS: Ubuntu 20.04.3 LTS
- Kivy: 2
- Cython: 0.29.19
- OpenJDK: 1.8.0_292

### Description

hello, I'm trying to build my application but during the operation the error comes out: "ValueError: name is too long", this happens on 1 pc with Debian 11 and a vps with Ubuntu 20 while on another device with Debian 11 no problem, they all have the required packages installed. What could be the cause of the error?

### buildozer.spec

Command:
```sh
p4a apk --private . --package=org.gtt --name "GTT" --version 0.5 --bootstrap=sdl2 --requirements=python3,requests,chardet,charset-normalizer,idna,kivy==2.0.0,kivymd==0.104.2,pillow,urllib3,openssl,sdl2_ttf==2.0.15 --sdk-dir $HOME/Android/Sdk --ndk-dir $HOME/Android/android-ndk-r19c --android-api 31 --ndk-api 21 --permission INTERNET
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
...
Listing '/root/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr'...
Listing '/root/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr/local'...
Listing '/root/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr/local/bin'...
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/usr/local/lib/python3.8/dist-packages/pythonforandroid/toolchain.py", line 725, in __init__
    getattr(self, command)(args)
  File "/usr/local/lib/python3.8/dist-packages/pythonforandroid/toolchain.py", line 154, in wrapper_func
    func(self, args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/pythonforandroid/toolchain.py", line 1144, in apk
    output, build_args = self._build_package(args, package_type='apk')
  File "/usr/local/lib/python3.8/dist-packages/pythonforandroid/toolchain.py", line 1045, in _build_package
    build_args = build.parse_args_and_make_package(
  File "/root/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/build.py", line 930, in parse_args_and_make_package
    make_package(args)
  File "/root/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/build.py", line 329, in make_package
    make_tar(
  File "/root/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/build.py", line 205, in make_tar
    tf.addfile(tinfo)
  File "/usr/lib/python3.8/tarfile.py", line 1993, in addfile
    buf = tarinfo.tobuf(self.format, self.encoding, self.errors)
  File "/usr/lib/python3.8/tarfile.py", line 824, in tobuf
    return self.create_ustar_header(info, encoding, errors)
  File "/usr/lib/python3.8/tarfile.py", line 841, in create_ustar_header
    info["prefix"], info["name"] = self._posix_split_name(info["name"], encoding, errors)
  File "/usr/lib/python3.8/tarfile.py", line 926, in _posix_split_name
    raise ValueError("name is too long")
ValueError: name is too long

```

**Comment by Andrea055** [comment]
fix installing openjdk 13
