### ISSUE TITLE
aiohttp/_http_parser.pyx:46:0: '_headers.pxi' not found

### ISSUE THREAD

**Issue by bitinerant** [kivy/python-for-android#2651]
### Checklist

- [x] the issue is indeed a bug and not a support request
- [x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [x] I have a short, runnable example that reproduces the issue
- [x] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [x] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: 3.8.10
- OS: Ubuntu 20.04.4
- Kivy: n/a
- Cython: 0.29.32
- OpenJDK: 13.0.7+5-Ubuntu-0ubuntu120.04

### Description

I am trying to build a recent version of the Python package [aiohttp](https://github.com/aio-libs/aiohttp) for Android. This package has a [recipe](https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes/aiohttp), and it builds successfully for v3.6.2, v3.7.3, and v3.7.4.post0. However, when building v3.8.0a7 and v3.8.1, I get `aiohttp/_http_parser.pyx:46:0: '_headers.pxi' not found`. The missing `_headers.pxi` file is supposed to be created by the [`tools/gen.py`](https://github.com/aio-libs/aiohttp/blob/3.8/tools/gen.py) line in [`Makefile`](https://github.com/aio-libs/aiohttp/blob/3.8/Makefile) but it appears that this doesn't get run during the Buildozer build.

### buildozer.spec

Steps to reproduce:
```sh
#begin with a fresh Ubuntu 20.04
sudo apt update
sudo DEBIAN_FRONTEND=noninteractive apt install -y git zip unzip openjdk-13-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev ccache lld
export PATH=$PATH:~/.local/bin
python3 -m pip install --upgrade Cython==0.29.32 virtualenv
python3 -m pip install git+https://github.com/kivy/buildozer.git@64c6094b97308d32da3f2af1478251adb782bdef  # version 1.4.1.dev0
mkdir ~/libapp && cd $_
vi buildozer.spec  # see below
echo y | buildozer android release
```

Spec file:
```
[app]
title = My Application
package.name = myapp
package.domain = org.domain
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,aiohttp==v3.8.1
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.archs = arm64-v8a, armeabi-v7a
android.allow_backup = True
android.release_artifact = aar
p4a.branch = develop
p4a.commit = HEAD
p4a.bootstrap = service_library
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0
ios.codesign.allowed = false
[buildozer]
log_level = 2
warn_on_root = 1
```

### Logs

```
...
[DEBUG]:   	Installing easy_install script to /home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/usr/local/bin
[DEBUG]:   	Installing easy_install-3.9 script to /home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/usr/local/bin
[DEBUG]:   	creating /home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages/distutils-precedence.pth
[INFO]:    <- directory context /home/ubuntu/libapp/.buildozer/android/platform/python-for-android
[INFO]:    Building aiohttp for arm64-v8a
[INFO]:    aiohttp apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in aiohttp
[INFO]:    -> directory context /home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/aiohttp/arm64-v8a__ndk_target_21/aiohttp
stty: 'standard input': Inappropriate ioctl for device
[DEBUG]:   -> running python3 -c import sys; print(sys.path)
[DEBUG]:   	['', '/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib', '/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages', '/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/build/lib.linux-x86_64-3.9', '/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/build/temp.linux-x86_64-3.9', '/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/build/scripts-3.9', '/usr/local/lib/python39.zip', '/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Lib']
[DEBUG]:   cwd is /home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/aiohttp/arm64-v8a__ndk_target_21/aiohttp
[INFO]:    Trying first build of aiohttp to get cython files: this is expected to fail
stty: 'standard input': Inappropriate ioctl for device
[DEBUG]:   -> running python3 setup.py build_ext -v
[DEBUG]:   	*********************
[DEBUG]:   	* Accelerated build *
[DEBUG]:   	*********************
[DEBUG]:   	running build_ext
[DEBUG]:   	building 'aiohttp._websocket' extension
[DEBUG]:   	creating build
[DEBUG]:   	creating build/temp.linux-x86_64-3.9
[DEBUG]:   	creating build/temp.linux-x86_64-3.9/aiohttp
[DEBUG]:   	/usr/bin/ccache /home/ubuntu/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Include -DANDROID -I/home/ubuntu/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/include/python3.9 -fPIC -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c aiohttp/_websocket.c -o build/temp.linux-x86_64-3.9/aiohttp/_websocket.o
[DEBUG]:   	clang-12: error: no such file or directory: 'aiohttp/_websocket.c'
[DEBUG]:   	clang-12: error: no input files
[DEBUG]:   	error: command '/usr/bin/ccache' failed with exit code 1
Exception in thread background thread for pid 44999:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
*********************
* Accelerated build *
*********************
running build_ext
building 'aiohttp._websocket' extension
creating build
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/aiohttp
/usr/bin/ccache /home/ubuntu/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Include -DANDROID -I/home/ubuntu/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/arm64-v8a/include/python3.9 -fPIC -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c aiohttp/_websocket.c -o build/temp.linux-x86_64-3.9/aiohttp/_websocket.o
clang-12: error: no such file or directory: 'aiohttp/_websocket.c'
clang-12: error: no input files
error: command '/usr/bin/ccache' failed with exit code 1


  STDERR:

[INFO]:    aiohttp first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize aiohttp/_helpers.pyx
stty: 'standard input': Inappropriate ioctl for device
[DEBUG]:   -> running python3 -cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main()); ./aiohttp/_helpers.pyx
[DEBUG]:   	/home/ubuntu/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/aiohttp/arm64-v8a__ndk_target_21/aiohttp/aiohttp/_helpers.pyx
[DEBUG]:   	  tree = Parsing.p_module(s, pxd, full_module_name)
[INFO]:    Cythonize aiohttp/_http_parser.pyx
stty: 'standard input': Inappropriate ioctl for device
[DEBUG]:   -> running python3 -cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main()); ./aiohttp/_http_parser.pyx
[DEBUG]:   	
[DEBUG]:   	Error compiling Cython file:
[DEBUG]:   	------------------------------------------------------------
[DEBUG]:   	...
[DEBUG]:   	
[DEBUG]:   	cimport cython
[DEBUG]:   	
[DEBUG]:   	from aiohttp cimport _cparser as cparser
[DEBUG]:   	
[DEBUG]:   	include "_headers.pxi"
[DEBUG]:   	^
[DEBUG]:   	------------------------------------------------------------
[DEBUG]:   	
[DEBUG]:   	aiohttp/_http_parser.pyx:46:0: '_headers.pxi' not found
[DEBUG]:   	
Exception in thread background thread for pid 45015:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./aiohttp/_http_parser.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...

cimport cython

from aiohttp cimport _cparser as cparser

include "_headers.pxi"
^
------------------------------------------------------------

aiohttp/_http_parser.pyx:46:0: '_headers.pxi' not found



  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1297, in <module>
    main()
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 731, in __init__
    getattr(self, command)(args)
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 154, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 213, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 505, in build_recipes
    recipe.build_arch(arch)
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1044, in build_arch
    self.build_cython_components(arch)
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1069, in build_cython_components
    self.cythonize_build(env=env)
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1117, in cythonize_build
    self.cythonize_file(env, build_dir, join(root, filename))
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1106, in cythonize_file
    shprint(python_command, "-c"
  File "/home/ubuntu/libapp/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 915, in next
    self.wait()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./aiohttp/_http_parser.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...

cimport cython

from aiohttp cimport _cparser as cparser

include "_headers.pxi"
^
------------------------------------------------------------

aiohttp/_http_parser.pyx:46:0: '_headers.pxi' not found



  STDERR:


# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=service_library --requirements=python3,aiohttp==v3.8.1 --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/ubuntu/libapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     PWD = '/home/ubuntu/libapp'
#     LOGNAME = 'ubuntu'
#     XDG_SESSION_TYPE = 'tty'
#     MOTD_SHOWN = 'pam'
#     HOME = '/home/ubuntu'
#     LANG = 'C.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     PROMPT_COMMAND = 'if [ $? -ne 0 ];then ERROR_FLAG=1;else ERROR_FLAG=;fi; '
#     SSH_CONNECTION = 'fd42:3977:ef9e:328b::1 38474 fd42:3977:ef9e:328b:216:3eff:fe45:bfd1 22'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'ubuntu'
#     SHLVL = '0'
#     XDG_SESSION_ID = '756'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     PS1 = '\\[\\033[0m\\]\\u\\[\\033[1;34m\\]@\\[\\033[0;33m\\]$hname\\[\\033[0m\\]:\\[\\033[1;34m\\]\\w\\[\\033[0;32m\\]${ERROR_FLAG:+\\[\\033[1;31m\\]}\\$\\[\\033[0m\\] '
#     SSH_CLIENT = 'fd42:3977:ef9e:328b::1 38474 22'
#     XDG_DATA_DIRS = '/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     PATH = '/home/ubuntu/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     SSH_TTY = '/dev/pts/1'
#     OLDPWD = '/home/ubuntu'
#     _ = '/home/ubuntu/.local/bin/buildozer'
#     PACKAGES_PATH = '/home/ubuntu/.buildozer/android/packages'
#     ANDROIDSDK = '/home/ubuntu/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/ubuntu/.buildozer/android/platform/android-ndk-r23b'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by misl6** [comment]
Hi @bitinerant !

This is something expectable, as recipes are really tied to a specific version.

We have an `on-hold` PR: https://github.com/kivy/python-for-android/pull/2518 which encountered the same issue during the test build.

Maybe we want to switch this issue to a feature request like "aiohttp is outdated"?

**Comment by bitinerant** [comment]
This issue is basically a duplicate of PR #2518. I added a note there and will close this issue. Thank you!

**Comment by xavierfiechter** [comment]
Yo @bitinerant 

Have you found a solution to this problem? 
Are there workarounds?
