### ISSUE TITLE
building pydantic failed

### ISSUE THREAD

**Issue by andrisas** [kivy/python-for-android#2661]
### Versions

- Python: 3
- OS: fedora 36

### Description

building pydantic failed

### buildozer.spec

Command:
```sh
buildozer android debug deploy
```

Spec file:
```
[app]

# (str) Title of your application
title = osa

# (str) Package name
package.name = osa

# (str) Package domain (needed for android/ios packaging)
package.domain = com.aas

# (str) Source code where the main.py live
source.dir = ./src

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,ini,json

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin, venv

# (list) List of exclusions using pattern matching
# Do not prefix with './'
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,plyer,wikipedia,beautifulsoup4,jnius,nltk,regex,requests,urllib3,charset_normalizer,idna,future,pandas,pymmh3,pydantic

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/img/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
services = Myservice:service.py:sticky

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (string) Presplash animation using Lottie format.
# see https://lottiefiles.com/ for examples and https://airbnb.design/lottie/
# for general documentation.
# Lottie files can be created using various tools, like Adobe After Effect or Synfig.
#android.presplash_lottie = "path/to/lottie/file.json"

# (str) Adaptive icon of the application (used if Android API level is 26+ at runtime)
#icon.adaptive_foreground.filename = %(source.dir)s/data/icon_fg.png
#icon.adaptive_background.filename = %(source.dir)s/data/icon_bg.png

# (list) Permissions
android.permissions = INTERNET, RECORD_AUDIO

# (list) features (adds uses-feature -tags to manifest)
#android.features = android.hardware.usb.host

# (int) Target Android API, should be as high as possible.
android.api = 31

# (int) Minimum API your APK / AAB will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 23b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.kivy.android.PythonActivity

# (str) Full name including package path of the Java class that implements Android Activity
# use that parameter together with android.entrypoint to set custom Java class instead of PythonActivity
#android.activity_class_name = org.kivy.android.PythonActivity

# (str) Extra xml to write directly inside the <manifest> element of AndroidManifest.xml
# use that parameter to provide a filename from where to load your custom XML code
#android.extra_manifest_xml = ./src/android/extra_manifest.xml

# (str) Extra xml to write directly inside the <manifest><application> tag of AndroidManifest.xml
# use that parameter to provide a filename from where to load your custom XML arguments:
#android.extra_manifest_application_arguments = ./src/android/extra_manifest_application_arguments.xml

# (str) Full name including package path of the Java class that implements Python Service
# use that parameter to set custom Java class instead of PythonService
#android.service_class_name = org.kivy.android.PythonService

# (str) Android app theme, default is ok for Kivy-based app
#android.apptheme = "@android:style/Theme.Translucent.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add
#android.add_aars =

# (list) Put these files or directories in the apk assets directory.
# Either form may be used, and assets need not be in 'source.include_exts'.
# 1) android.add_assets = source_asset_relative_path
# 2) android.add_assets = source_asset_path:destination_asset_relative_path
#android.add_assets =

# (list) Gradle dependencies to add
#android.gradle_dependencies =

# (bool) Enable AndroidX support. Enable when 'android.gradle_dependencies'
# contains an 'androidx' package, or any package from Kotlin source.
# android.enable_androidx requires android.api >= 28
#android.enable_androidx = False

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_packaging_options =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
android.manifest.intent_filters = intent.xml

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Android logcat only display log for activity's pid
#android.logcat_pid_only = False

# (str) Android additional adb arguments
#android.adb_args = -H host.docker.internal

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (list) The Android archs to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
# In past, was `android.arch` as we weren't supporting builds for multiple archs at the same time.
android.archs = arm64-v8a, armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

# (bool) enables Android auto backup feature (Android API >=23)
android.allow_backup = True

# (str) XML file for custom backup rules (see official auto backup documentation)
# android.backup_rules =

# (str) If you need to insert variables into your AndroidManifest.xml file,
# you can do so with the manifestPlaceholders property.
# This property takes a map of key-value pairs. (via a string)
# Usage example : android.manifest_placeholders = [myCustomUrl:\"org.kivy.customurl\"]
# android.manifest_placeholders = [:]

# (bool) disables the compilation of py to pyc/pyo files when packaging
#android.no-compile-pyo = True

# (str) The format used to package the app for release mode (aab or apk or aar).
android.release_artifact = aab

# (str) The format used to package the app for debug mode (apk or aar).
# android.debug_artifact = apk

#
# Python for android (p4a) specific
#

# (str) python-for-android URL to use for checkout
#p4a.url =

# (str) python-for-android fork to use in case if p4a.url is not specified, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
p4a.branch = develop

# (str) python-for-android specific commit to use, defaults to HEAD, must be within p4a.branch
#p4a.commit = HEAD

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes = recipes

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =

# Control passing the --use-setup-py vs --ignore-setup-py to p4a
# "in the future" --use-setup-py is going to be the default behaviour in p4a, right now it is not
# Setting this to false will pass --ignore-setup-py, true will pass --use-setup-py
# NOTE: this is general setuptools integration, having pyproject.toml is enough, no need to generate
# setup.py if you're using Poetry, but you need to add "toml" to source.include_exts.
#p4a.setup_py = false

# (str) extra command line arguments to pass when invoking pythonforandroid.toolchain
#p4a.extra_args =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0

# (bool) Whether or not to sign the code
ios.codesign.allowed = false

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) The development team to use for signing the debug version
#ios.codesign.development_team.debug = <hexstring>

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s

# (str) The development team to use for signing the release version
#ios.codesign.development_team.release = <hexstring>

# (str) URL pointing to .ipa file to be installed
# This option should be defined along with `display_image_url` and `full_size_image_url` options.
#ios.manifest.app_url =

# (str) URL pointing to an icon (57x57px) to be displayed during download
# This option should be defined along with `app_url` and `full_size_image_url` options.
#ios.manifest.display_image_url =

# (str) URL pointing to a large icon (512x512px) to be used by iTunes
# This option should be defined along with `app_url` and `display_image_url` options.
#ios.manifest.full_size_image_url =


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .aab, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
[INFO]:    Building pydantic for armeabi-v7a
[INFO]:    pydantic apparently isn't already in site-packages
[INFO]:    Installing pydantic into site-packages
[INFO]:    -> directory context /home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/pydantic/armeabi-v7a__ndk_target_21/pydantic
[DEBUG]:   -> running python3 setup.py install -O2 --root=/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/osa/armeabi-v7a --install-lib=.
[DEBUG]:        running install
[DEBUG]:        running build
[DEBUG]:        running build_py
[DEBUG]:        running build_ext
[DEBUG]:        building 'pydantic.__init__' extension
[DEBUG]:        /usr/bin/ccache /home/Andris/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O3 -DANDROID -I/home/Andris/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/osa/armeabi-v7a/include/python3.9 -fPIC -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c pydantic/__init__.c -o build/temp.linux-x86_64-3.9/pydantic/__init__.o
[DEBUG]:        In file included from pydantic/__init__.c:18:
[DEBUG]:        In file included from /home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/Python.h:50:
[DEBUG]:        /home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/pyport.h:741:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
[DEBUG]:        #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
[DEBUG]:         ^
[DEBUG]:        pydantic/__init__.c:223:39: error: expression is not an integer constant expression
[DEBUG]:            enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
[DEBUG]:                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[DEBUG]:        pydantic/__init__.c:223:41: note: division by zero
[DEBUG]:            enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
[DEBUG]:                                                ^
[DEBUG]:        2 errors generated.
[DEBUG]:        error: command '/usr/bin/ccache' failed with exit code 1
Exception in thread background thread for pid 8152:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/sh-1.14.3-py3.10.egg/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sh-1.14.3-py3.10.egg/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.10/site-packages/sh-1.14.3-py3.10.egg/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.10/site-packages/sh-1.14.3-py3.10.egg/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/osa/armeabi-v7a --install-lib=.

  STDOUT:
running install
running build
running build_py
running build_ext
building 'pydantic.__init__' extension
/usr/bin/ccache /home/Andris/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O3 -DANDROID -I/home/Andris/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/osa/armeabi-v7a/include/python3.9 -fPIC -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c pydantic/__init__.c -o build/temp.linux-x86_64-3.9/pydantic/__init__.o
In file included from pydantic/__init__.c:18:
In file included from /home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/Python.h:50:
/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/pyport.h:741:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 ^
pydantic/__init__.c:223:39: error: expression is not an integer constant expression
    enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pydantic/__init__.c:223:41: note: division by zero
    enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
                                        ^
2 errors generated.
error: command '/usr/bin/ccache' failed with exit code 1


  STDERR:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1297, in <module>
    main()
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 730, in __init__
    getattr(self, command)(args)
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 505, in build_recipes
    recipe.build_arch(arch)
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 932, in build_arch
    self.install_python_package(arch)
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 948, in install_python_package
    shprint(hostpython, 'setup.py', 'install', '-O2',
  File "/home/Andris/Programing/osa/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/usr/local/lib/python3.10/site-packages/sh-1.14.3-py3.10.egg/sh.py", line 915, in next
    self.wait()
  File "/usr/local/lib/python3.10/site-packages/sh-1.14.3-py3.10.egg/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.10/site-packages/sh-1.14.3-py3.10.egg/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/osa/armeabi-v7a --install-lib=.

  STDOUT:
running install
running build
running build_py
running build_ext
building 'pydantic.__init__' extension
/usr/bin/ccache /home/Andris/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O3 -DANDROID -I/home/Andris/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/osa/armeabi-v7a/include/python3.9 -fPIC -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c pydantic/__init__.c -o build/temp.linux-x86_64-3.9/pydantic/__init__.o
In file included from pydantic/__init__.c:18:
In file included from /home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/Python.h:50:
/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/pyport.h:741:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 ^
pydantic/__init__.c:223:39: error: expression is not an integer constant expression
    enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pydantic/__init__.c:223:41: note: division by zero
    enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
                                        ^
2 errors generated.
error: command '/usr/bin/ccache' failed with exit code 1


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=osa --bootstrap=sdl2 --requirements=python3,kivy,plyer,wikipedia,beautifulsoup4,jnius,nltk,regex,requests,urllib3,charset_normalizer,idna,future,pandas,pymmh3,pydantic,https://gitlab.com/aas12315/haystackandroid/-/archive/main/haystackandroid-main.zip --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/Andris/Programing/osa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/unix:@/tmp/.ICE-unix/2039,unix/unix:/tmp/.ICE-unix/2039'
#     COLORTERM = 'truecolor'
#     HISTCONTROL = 'ignoredups'
#     XDG_MENU_PREFIX = 'gnome-'
#     TERM_PROGRAM_VERSION = '1.70.2'
#     HOSTNAME = 'fedora'
#     HISTSIZE = '1000'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'gnome'
#     NO_AT_BRIDGE = '1'
#     EDITOR = '/usr/bin/nano'
#     PWD = '/home/Andris/Programing/osa'
#     XDG_SESSION_DESKTOP = 'gnome'
#     LOGNAME = 'Andris'
#     XDG_SESSION_TYPE = 'wayland'
#     SYSTEMD_EXEC_PID = '2093'
#     _ = '/usr/local/bin/buildozer'
#     XAUTHORITY = '/run/user/1000/.mutter-Xwaylandauth.1S8HR1'
#     VSCODE_GIT_ASKPASS_NODE = '/usr/share/code/code'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     GDM_LANG = 'en_US.UTF-8'
#     HOME = '/home/Andris'
#     USERNAME = 'Andris'
#     LANG = 'en_US.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:'
#     XDG_CURRENT_DESKTOP = 'GNOME'
#     WAYLAND_DISPLAY = 'wayland-0'
#     GIT_ASKPASS = '/usr/share/code/resources/app/extensions/git/dist/askpass.sh'
#     INVOCATION_ID = '9e9b03a643e44931b394b05e4ae58e06'
#     MANAGERPID = '1913'
#     CHROME_DESKTOP = 'code-url-handler.desktop'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     VSCODE_GIT_ASKPASS_EXTRA_ARGS = '--ms-enable-electron-run-as-node'
#     GNOME_SETUP_DISPLAY = ':1'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     LESSOPEN = '||/usr/bin/lesspipe.sh %s'
#     USER = 'Andris'
#     VSCODE_GIT_IPC_HANDLE = '/run/user/1000/vscode-git-9f3be6c921.sock'
#     DISPLAY = ':0'
#     SHLVL = '2'
#     QT_IM_MODULE = 'ibus'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     DEBUGINFOD_URLS = 'https://debuginfod.fedoraproject.org/ '
#     which_declare = 'declare -f'
#     VSCODE_GIT_ASKPASS_MAIN = '/usr/share/code/resources/app/extensions/git/dist/askpass-main.js'
#     JOURNAL_STREAM = '8:32244'
#     XDG_DATA_DIRS = '/home/Andris/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     GDK_BACKEND = 'x11'
#     PATH = '/home/Andris/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/Andris/.local/bin:/home/Andris/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin'
#     GDMSESSION = 'gnome'
#     ORIGINAL_XDG_CURRENT_DESKTOP = 'GNOME'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     MAIL = '/var/spool/mail/Andris'
#     GIO_LAUNCHED_DESKTOP_FILE_PID = '2955'
#     GIO_LAUNCHED_DESKTOP_FILE = '/usr/share/applications/code.desktop'
#     TERM_PROGRAM = 'vscode'
#     BASH_FUNC_which%% = ('() {  ( alias;\n'
 ' eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias '
 '--read-functions --show-tilde --show-dot $@\n'
 '}')
#     PACKAGES_PATH = '/home/Andris/.buildozer/android/packages'
#     ANDROIDSDK = '/home/Andris/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/Andris/.buildozer/android/platform/android-ndk-r23b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
```

**Comment by ConnerLabs** [comment]
Also just run into this exact same problem, any updates?

**Comment by kailash6789** [comment]
Same problem. Any solution please ?
Also, having similar issues with pyusb

**Comment by ConnerLabs** [comment]
The problem only happens on 32 bit Android builds. I fixed it by removing the 32 bit build and only doing a 64 bit one.

**Comment by kailash6789** [comment]
Thanks. Will try it out

**Comment by kwebber3** [comment]
Same issue here. Couldn't figure out how to make it only 64 bit, but I don't see any evidence I am using 32 bit on anything.
