### ISSUE TITLE
Android app crash on starting up by accessing texture. Error:No module named 'typing_extensions'

### ISSUE THREAD

**Issue by Jubileus-ryz** [kivy/python-for-android#2743]
-python version: 3.9.9 
-Kivy version: 2.1.0
-p4a version : 2023.1.28

It works well when building with p4a version 2022.12.20. But crash after updating to 2023.1.28

Detail Logs:
```
09-02 15:05:41.647  9575  9601 I python  :  Traceback (most recent call last):
09-02 15:05:41.647  9575  9601 I python  :    File "/home/ubuntu/Source/virtualeconomy/gemmer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/gemmer/arm64-v8a/kivy/lang/builder.py", line 240, in create_handler
09-02 15:05:41.647  9575  9601 I python  :    File "/data/data/net.primecoin.app.gemmer/files/app/gemmer.kv", line 87, in <module>
09-02 15:05:41.647  9575  9601 I python  :      texture: self.qrcodeImage(self.info).texture
09-02 15:05:41.647  9575  9601 I python  :    File "/home/ubuntu/Source/virtualeconomy/gemmer/.buildozer/android/app/gui/qr.py", line 19, in qrcodeImage
09-02 15:05:41.647  9575  9601 I python  :    File "/home/ubuntu/Source/virtualeconomy/gemmer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/gemmer/arm64-v8a/qrcode/__init__.py", line 1, in <module>
09-02 15:05:41.648  9575  9601 I python  :    File "/home/ubuntu/Source/virtualeconomy/gemmer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/gemmer/arm64-v8a/qrcode/main.py", line 15, in <module>
09-02 15:05:41.648  9575  9601 I python  :  ModuleNotFoundError: No module named 'typing_extensions'
```

How can I fixed it?

**Comment by misl6** [comment]
Hi @Jubileus-ryz !

Can you share your requirements list?

**Comment by Jubileus-ryz** [comment]
> Hi @Jubileus-ryz !
> 
> Can you share your requirements list?

Here is my requirements :

```
requirements = openssl,libzbar,python3,kivy==2.1.0,qrcode,Pillow,plyer,mnemonic,zbarlight,requests,urllib3,chardet,idna,certifi,python-axolotl-curve25519,base58,pyvsystems==0.3.2,pyblake2,PyNaCl,oscpy,git+ssh://git@github.com/primecoin/python-bitcoinlib.git@29c3a4fbcc54eabf78805c56367ff1a67b9eb27e,git+ssh://git@github.com/virtualeconomy/gemmer.git@05d24c8942a5ab0262044bbe963e8771b9b32d7a
```

**Comment by jianni1** [comment]
> > Hi @Jubileus-ryz !
> > Can you share your requirements list?
> 
> Here is my requirements :
> 
> ```
> requirements = openssl,libzbar,python3,kivy==2.1.0,qrcode,Pillow,plyer,mnemonic,zbarlight,requests,urllib3,chardet,idna,certifi,python-axolotl-curve25519,base58,pyvsystems==0.3.2,pyblake2,PyNaCl,oscpy,git+ssh://git@github.com/primecoin/python-bitcoinlib.git@29c3a4fbcc54eabf78805c56367ff1a67b9eb27e,git+ssh://git@github.com/virtualeconomy/gemmer.git@05d24c8942a5ab0262044bbe963e8771b9b32d7a
> ```

Having the same problem as you, I tried to fix it by adding 'requirements=typing_extensions'.
my requirements:

```
requirements = typing_extensions,openssl,libzbar,python3,kivy==2.1.0,qrcode,Pillow,plyer,mnemonic,zbarlight,requests,urllib3,chardet,idna,certifi,python-axolotl-curve25519,base58,pyvsystems==0.3.2,pyblake2,PyNaCl,oscpy,git+ssh://git@github.com/primecoin/python-bitcoinlib.git@29c3a4fbcc54eabf78805c56367ff1a67b9eb27e,git+ssh://git@github.com/virtualeconomy/gemmer.git@fa7271b7e2c73fde07511a259335104ea3a6712e
```

But crash
Error:No module named 'png'
Detail Logs:
```
02-07 13:42:17.380 17913 17960 I python  :  BuilderException: Parser: File "/data/data/net.primecoin.app.gemmer/files/app/gemmer.kv", line 87:
02-07 13:42:17.380 17913 17960 I python  :  ...
02-07 13:42:17.381 17913 17960 I python  :       85:<QRcodeImage>
02-07 13:42:17.381 17913 17960 I python  :       86:    info: ""
02-07 13:42:17.381 17913 17960 I python  :  >>   87:    texture: self.qrcodeImage(self.info).texture
02-07 13:42:17.381 17913 17960 I python  :       88:
02-07 13:42:17.381 17913 17960 I python  :       89:<QRcodeLabel>
02-07 13:42:17.381 17913 17960 I python  :  ...
02-07 13:42:17.381 17913 17960 I python  :  ModuleNotFoundError: No module named 'png'
```

I tried to fix the problem by adding 'requirements=pypng', and the program worked
Final my requirements:

```requirements = 
pypng,ptyping_extensions,openssl,libzbar,python3,kivy==2.1.0,qrcode,Pillow,plyer,mnemonic,zbarlight,requests,urllib3,chardet,idna,certifi,python-axolotl-curve25519,base58,pyvsystems==0.3.2,pyblake2,PyNaCl,oscpy,git+ssh://git@github.com/primecoin/python-bitcoinlib.git@29c3a4fbcc54eabf78805c56367ff1a67b9eb27e,git+ssh://git@github.com/virtualeconomy/gemmer.git@fa7271b7e2c73fde07511a259335104ea3a6712e```

**Comment by sunnyking** [comment]
```
class QRcodeImage(Image):

    def qrcodeImage(self, data: str):
        import qrcode
        from io import BytesIO
        from kivy.core.image import Image as CoreImage
        qr = qrcode.QRCode(version=1, box_size=64)
        qr.add_data(data)
        qr.make(fit=True)
        png = BytesIO()
        qrPillow = qr.make_image(fill='black', back_color='white')
        qrPillow.save(png, format='png')  # save pillow image to memory buffer
        png.seek(0)
        return CoreImage(BytesIO(png.read()), ext='png')  # ram buffer to image
```

**Comment by sunnyking** [comment]
Does it look like the Image class now requires pypng and typing_extensions to be declared as explicit requirements?
