### ISSUE TITLE
cython uses system python instead of hostpython

### ISSUE THREAD

**Issue by kived** [kivy/python-for-android#277]
Which can sometimes be an issue:

```
/home/kivy/android/python-for-android/src/tools/liblink -lm -L/home/kivy/android/python-for-android/build/libs -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/android/android-ndk-r8c/platforms/android-14/arch-arm build/temp.linux-i686-2.7/twisted/python/sendmsg.o -L/home/kivy/android/python-for-android/build/python-install/lib -lpython2.7 -o build/lib.linux-i686-2.7/twisted/python/sendmsg.so
Traceback (most recent call last):
  File "/usr/local/bin/cython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 22, in <module>
    import zipfile
  File "/usr/lib/python2.7/zipfile.py", line 6, in <module>
    import io
  File "/usr/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /home/kivy/android/python-for-android/build/hostpython/Python-2.7.2/build/lib.linux-i686-2.7/_io.so: undefined symbol: PyUnicodeUCS2_Replace
```
##

**Comment by inclement** [comment]
This should be fixed in master now.
