### ISSUE TITLE
org.kivy.android.PythonActivity$NewIntentListener is not visible from class loader java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Ahd999** [kivy/python-for-android#2770]
App used to check: Pydroid3

The Code:
`from jnius import cast
from jnius import autoclass
from android import activity
import kivy

        

PythonActivity = autoclass('org.renpy.android.PythonActivity')
Intent = autoclass('android.content.Intent')

intent = Intent()
intent.setAction(Intent.ACTION_PICK)
intent.setType("image/*")
PythonActivity.mActivity.startActivityForResult(intent, 0x123)

def on_activity_result(requestCode, resultCode, data):
        print ("### ACTIVITY CALLBACK ###")
    
def on_new_intent(intent):
        print ("#### INTENT", intent)

activity.bind(on_new_intent=on_new_intent,on_activity_result=on_activity_result)`

The error:

`Traceback (most recent call last):
   File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 24, in <module>
     activity.bind(on_new_intent=on_new_intent,on_activity_result=on_activity_result)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/android/activity.py", line 43, in bind
     listener = NewIntentListener(callback)
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/android/activity.py", line 17, in __init__
     super().__init__(**kwargs)
   File "jnius/jnius_proxy.pxi", line 28, in jnius.jnius.PythonJavaClass.__init__
   File "jnius/jnius_proxy.pxi", line 34, in jnius.jnius.PythonJavaClass._init_j_self_ptr
   File "jnius/jnius_proxy.pxi", line 182, in jnius.jnius.create_proxy_instance
   File "jnius/jnius_export_class.pxi", line 856, in jnius.jnius.JavaMethod.__call__
   File "jnius/jnius_export_class.pxi", line 1028, in jnius.jnius.JavaMethod.call_staticmethod
   File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
 jnius.jnius.JavaException: JVM exception occurred: interface org.kivy.android.PythonActivity$NewIntentListener is not visible from class loader java.lang.IllegalArgumentException
`

**Comment by Ahd999** [comment]
Wrong place for posting I'd do it at pyjnius
