### ISSUE TITLE
enaml recipe build fail

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/python-for-android#2804]
### Logs

```
[1m[INFO][0m:    [36m-> directory context /home/bobf/ex/regression/.buildozer/android/platform/build-arm64-v8a/build/other_builds/atom/arm64-v8a__ndk_target_21/atom[39m
[1m[90m[DEBUG][39m[0m:   [90m->[0m running python3 setup.py build_ext -v[0m
[1m[90m[DEBUG][39m[0m:   	Traceback (most recent call last):
[1m[90m[DEBUG][39m[0m:   	  File "/home/bobf/ex/regression/.buildozer/android/platform/build-arm64-v8a/build/other_builds/atom/arm64-v8a__ndk_target_21/atom/setup.py", line 13, in <module>
[1m[90m[DEBUG][39m[0m:   	    from cppy import CppyBuildExt
[1m[90m[DEBUG][39m[0m:   	ImportError: cannot import name 'CppyBuildExt' from 'cppy' (/home/bobf/ex/regression/.buildozer/android/platform/build-arm64-v8a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages/cppy/__init__.py)
[1m[90m[DEBUG][39m[0m:   	
[1m[90m[DEBUG][39m[0m:   	The above exception was the direct cause of the following exception:
[1m[90m[DEBUG][39m[0m:   	
[1m[90m[DEBUG][39m[0m:   	Traceback (most recent call last):
[1m[90m[DEBUG][39m[0m:   	  File "/home/bobf/ex/regression/.buildozer/android/platform/build-arm64-v8a/build/other_builds/atom/arm64-v8a__ndk_target_21/atom/setup.py", line 15, in <module>
[1m[90m[DEBUG][39m[0m:   	    raise RuntimeError(
[1m[90m[DEBUG][39m[0m:   	RuntimeError: Missing setup required dependencies: cppy. Installing through pip as recommended ensure one never hits this issue.
```

**Comment by AndreMiras** [comment]
I could reproduce from the CI via https://github.com/kivy/python-for-android/actions/runs/14010016065/job/39228612288
```
Traceback (most recent call last):
  File "/home/user/.local/share/python-for-android/build/other_builds/atom/x86__ndk_target_24/atom/setup.py", line 12, in <module>
    from cppy import CppyBuildExt
ModuleNotFoundError: No module named 'cppy'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/user/.local/share/python-for-android/build/other_builds/atom/x86__ndk_target_24/atom/setup.py", line 14, in <module>
    raise RuntimeError(
RuntimeError: Missing setup required dependencies: cppy. Installing through pip as recommended ensure one never hits this issue.
  STDERR:
```
We can look this up and update the recipe after #2802 is addressed since it relies on it
