### ISSUE TITLE
pyrxp recipe build fail

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/python-for-android#2817]
### Logs

```
[1m[INFO][0m:    Downloading pyrxp from https://bitbucket.org/rptlab/pyrxp/get/2a02cecc87b9.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1312, in <module>
    main()
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 734, in __init__
    getattr(self, command)(args)
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 482, in build_recipes
    recipe.download_if_necessary()
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 348, in download_if_necessary
    self.download()
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 398, in download
    self.download_file(self.versioned_url, filename)
  File "/home/bobf/ex/regression/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 202, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Faboli76** [comment]
I got the same error message when converting a py file to apk.
