### ISSUE TITLE
[BUG]: ctypes: AttributeError: undefined symbol: PyCapsule_New

### ISSUE THREAD

**Issue by T-Dynamos** [kivy/python-for-android#2840]
Full Logs:
```
06-21 09:09:53.471  5591  5636 I python  :  Traceback (most recent call last):
06-21 09:09:53.471  5591  5636 I python  :    File "/home/tdynamos/Kodvaan/.buildozer/android/app/main.py", line 24, in <module>
06-21 09:09:53.472  5591  5636 I python  :    File "/home/tdynamos/Kodvaan/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kodvaan/arm64-v8a/pylint/lint/__init__.py", line 22, in <module>
06-21 09:09:53.472  5591  5636 I python  :    File "/home/tdynamos/Kodvaan/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kodvaan/arm64-v8a/pylint/lint/parallel.py", line 13, in <module>
06-21 09:09:53.473  5591  5636 I python  :    File "/home/tdynamos/Kodvaan/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kodvaan/arm64-v8a/dill/__init__.py", line 26, in <module>
06-21 09:09:53.474  5591  5636 I python  :    File "/home/tdynamos/Kodvaan/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kodvaan/arm64-v8a/dill/_dill.py", line 1854, in <module>
06-21 09:09:53.474  5591  5636 I python  :    File "/home/tdynamos/Kodvaan/.buildozer/android/platform/build-arm64-v8a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/ctypes/__init__.py", line 387, in __getattr__
06-21 09:09:53.475  5591  5636 I python  :    File "/home/tdynamos/Kodvaan/.buildozer/android/platform/build-arm64-v8a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/ctypes/__init__.py", line 392, in __getitem__
06-21 09:09:53.476  5591  5636 I python  :  AttributeError: undefined symbol: PyCapsule_New
```
To reproduce:
```
import ctypes 
```

**Comment by T-Dynamos** [comment]
Same as #1866
