### ISSUE TITLE
homebrew prerequisite openssl@1.1 is disabled

### ISSUE THREAD

**Issue by DingoBingoAdmin** [kivy/python-for-android#3081]
### Description

**prerequisites.py** line 265
OpenSSLPrerequisite() defines the following variable
homebrew_formula_name = "openssl@1.1"

This formula has been disabled in homebrew
(https://formulae.brew.sh/formula/openssl@1.1)

I manually changed the value to
homebrew_formula_name = "openssl@3"

Now the Prerequisite can be met.

```
Sorry, I didn't keep the build error.
```

**Comment by hardikfuria12** [comment]
```
[INFO]:    No helper available for prerequisite: openssl on macOS
[INFO]:    python-for-android can automatically install prerequisite: openssl
Do you want automatically install prerequisite openssl? [y/N] y
[INFO]:    Installing OpenSSL ...
Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/hardikfuria/Desktop/try3/loginapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 25, in <module>
    check()
  File "/Users/hardikfuria/Desktop/try3/loginapp/.buildozer/android/platform/python-for-android/pythonforandroid/checkdependencies.py", line 69, in check
    check_and_install_default_prerequisites()
  File "/Users/hardikfuria/Desktop/try3/loginapp/.buildozer/android/platform/python-for-android/pythonforandroid/prerequisites.py", line 404, in check_and_install_default_prerequisites
    prerequisite.install()
  File "/Users/hardikfuria/Desktop/try3/loginapp/.buildozer/android/platform/python-for-android/pythonforandroid/prerequisites.py", line 60, in install
    self.darwin_installer()
  File "/Users/hardikfuria/Desktop/try3/loginapp/.buildozer/android/platform/python-for-android/pythonforandroid/prerequisites.py", line 285, in darwin_installer
    subprocess.check_output(["brew", "install", self.homebrew_formula_name])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['brew', 'install', 'openssl@1.1']' returned non-zero exit status 1.
# This buildozer version requires a python-for-android version with AAB (Android App Bundle) support. Please update your pinned version accordingly.
```

Above is the error log that i get when facing the same issue

**Comment by hemna** [comment]
yup, I am completely stuck and unable to build because of this.

**Comment by kuzeyron** [comment]
Also mentioned on [Buildozer](https://github.com/kivy/buildozer/issues/1872).
