### ISSUE TITLE
apk packages can't find standardlibrary libs if using external storage

### ISSUE THREAD

**Issue by thica** [kivy/python-for-android#363]
It's likely a bug in buildozer or python-for-android:

```
Creating a simple akp works with android default settings.
Creating a simple akp works with android.private_storage = False
Creating an akp which uses libs from the python standard library (eg. from xml.etree              import ElementInclude) with android default settings works.
Creating an akp which uses libs from the python standard library (eg. from xml.etree              import ElementInclude) with android.private_storage = True works not.
```

Looks like either the path to the lib is not ok, or it is not compiled properly. My build logs are alread attached in the previous logs!

Logfile part:

```
INFO              ] Logger: Record log in /mnt/sdcard/org.orca.orca/.kivy/logs/kivy_15-04-16_1.txt
[INFO              ] Kivy: v1.9.0
[INFO              ] Python: v2.7.2 (default, Apr 16 2015, 10:58:27)
[GCC 4.8]
[INFO              ] Factory: 173 symbols loaded
[WARNING           ] stderr: /data/data/org.orca.orca/files/lib/python2.7/site-packages/kivy/core/image/img_pygame.py:13: RuntimeWarning: import cdrom: No module named cdrom
[WARNING           ] stderr: (ImportError: No module named cdrom)
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/home/kivy/workbd/.buildozer/android/app/main.py", line 37, in <module>
[WARNING           ] stderr:   File "/home/kivy/workbd/.buildozer/android/app/ORCA/App.py", line 31, in <module>
[WARNING           ] stderr:   File "/home/kivy/workbd/.buildozer/android/app/ORCA/InterfaceClass.py", line 38, in <module>
[WARNING           ] stderr:   File "/home/kivy/workbd/.buildozer/android/app/ORCA/Events.py", line 28, in <module>
[WARNING           ] stderr:   File "/home/kivy/workbd/.buildozer/android/app/ORCA/utils/XML.py", line 25, in <module>
[WARNING           ] stderr:   File "/home/kivy/workbd/.buildozer/android/app/ORCA/utils/XML.py", line 25, in <module>
[WARNING           ] stderr: ImportError: No module named etree
```
##

**Comment by tito** [comment]
Where is etree in your apk? Can you try extracting a list of files in the apk, and in the .mp3 (private.mp3 and public.mp3) ?

**Comment by thica** [comment]
Hi tito,
both apks (private vs public) looks similar, having just a private.mp3, where a lib folder contains a python27.zip folder with the xml/etree folder. No public.mp3!

**Comment by inclement** [comment]
External storage is no longer supported in the current toolchain.
