### ISSUE TITLE
buildozer needs markupsafe to build 

### ISSUE THREAD

**Issue by Potitius** [kivy/python-for-android#399]
Traceback (most recent call last):
  File "build.py", line 15, in <module>
    import jinja2
  File "buildlib/jinja2.egg/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "buildlib/jinja2.egg/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "buildlib/jinja2.egg/jinja2/nodes.py", line 18, in <module>
    from jinja2.utils import Markup
  File "buildlib/jinja2.egg/jinja2/utils.py", line 520, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

I just installed python-markupsafe

**Comment by tito** [comment]
This has been fixed in master
