### ISSUE TITLE
Error: JAVA_HOME is not defined correctly.

### ISSUE THREAD

**Issue by kasramvd** [kivy/python-for-android#427]
After running the following command : 

```
./build.py --package org.test.touchtracer --name touchtracer --version 1.0 --dir ./python-install/share/kivy-examples/demo/touchtracer debug
```

I got the following error : 

```
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/jdk1.7.0/bin/java
Traceback (most recent call last):
  File "./build.py", line 508, in <module>
    make_package(args)
  File "./build.py", line 357, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
```

Am I need to install `jdk1.7.0` or I need to change the path of  `java`? 

this is this the result of `ls` command in `/usr/lib/jvm` : 

```
default-java  java-1.7.0-openjdk-amd64  java-7-openjdk-amd64  java-7-oracle
```

And in some of this directories I have `/bin/java`.

And after that I change the name of (for example ) the directory `java-1.7.0-openjdk-amd64` to `jdk1.7.0` it raise the following error:

```
BUILD FAILED
/home/username/python-for-android/dist/default/build.xml:6: Source resource does not exist: /home/username/python-for-android/dist/default/project.properties

Total time: 0 seconds
Traceback (most recent call last):
  File "./build.py", line 508, in <module>
    make_package(args)
  File "./build.py", line 357, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
```
##

**Comment by inclement** [comment]
Closing as this issue relates to the old toolchain which is no longer supported. Please open a new issue if you experience this problem with the current master branch.
