### ISSUE TITLE
[revamp] Recipes can only depend on other recipes

### ISSUE THREAD

**Issue by str4d** [kivy/python-for-android#449]
Reading the code, this appears to be intentional, but is there scope for allowing recipes to depend on modules? I am trying to write a Twisted recipe, and it depends on `zope.interface`, which is a trivial Python module that requires no special treatment. But currently I have to make a trivial recipe for it; I am wondering if that should be necessary. One reason for requiring a recipe is that then e.g. tests can be stripped out, but maybe that could be reliably automated for Python modules?

**Comment by inclement** [comment]
I should be possible to depend on anything in pypi, if that doesn't work then it's a bug. Does adding the pypi module name in the depends not work?

**Comment by str4d** [comment]
The Python module is correctly detected in `get_recipe_order_and_bootstrap()` at line 2245, but then in the subsequent call to `graph.remove_remaining_conflicts()` it blows up:

```
[INFO]:    Loaded recipe twisted (depends on ['zope.interface'])
[INFO]:    No recipe named zope.interface; will attempt to install with pip
Traceback (most recent call last):
  File "/home/str4d/.local/bin/p4a", line 11, in <module>
    sys.exit(ToolchainCL())
  File "/home/str4d/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 2428, in __init__
    getattr(self, args.command)(unknown)
  File "/home/str4d/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 169, in wrapper_func
    args = build_dist_from_args(ctx, dist, args)
  File "/home/str4d/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 2202, in build_dist_from_args
    build_order, python_modules, bs = get_recipe_order_and_bootstrap(ctx, dist.recipes, bs)
  File "/home/str4d/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 2262, in get_recipe_order_and_bootstrap
    graph.remove_remaining_conflicts(ctx)
  File "/home/str4d/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 481, in remove_remaining_conflicts
    recipe = Recipe.get_recipe(name, ctx)
  File "/home/str4d/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 1774, in get_recipe
    mod = importlib.import_module("pythonforandroid.recipes.{}".format(name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named zope.interface
```

**Comment by inclement** [comment]
Okay, I guess recipes haven't ever depended on pypi modules before, so
it's a bug.

**Comment by inclement** [comment]
A method to resolve this was introduced by https://github.com/kivy/python-for-android/pull/559
