### ISSUE TITLE
SDL2 bootstrap broken with blacklist?

### ISSUE THREAD

**Issue by tito** [kivy/python-for-android#567]
I don't pass any --blacklist option, but i got this issue after building a distribution then an apk:

```
# Run 'python -m pythonforandroid.toolchain apk --bootstrap=sdl2 --dist_name nrt8000 --name NRT-8000 --version 2.0.0 --package com.nrtech.nrt8000 --android_api 19 --private /home/tito/code/nrtpackage/nrt/.buildozer/android/app --permission INTERNET --permission ACCESS_NETWORK_STATE --permission ACCESS_WIFI_STATE --permission BLUETOOTH --permission BLUETOOTH_ADMIN --presplash /home/tito/code/nrtpackage/nrt/./presplash.jpg --icon /home/tito/code/nrtpackage/nrt/./icon.png --orientation landscape'
# Cwd /home/tito/code/python-for-android
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
[INFO]:    Will compile for the following archs: armeabi
[INFO]:    Getting Android API version from user argument
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv-2.7
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	nrt8000: includes recipes (hostpython2, sdl2_image, sdl2_mixer, sdl2_ttf, python2, sdl2, six, pyjnius, kivy==master), built for archs (armeabi)
[INFO]:    nrt8000 has compatible recipes, using this one
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	nrt8000: includes recipes (hostpython2, sdl2_image, sdl2_mixer, sdl2_ttf, python2, sdl2, six, pyjnius, kivy==master), built for archs (armeabi)
[INFO]:    nrt8000 has compatible recipes, using this one
[INFO]:    -> directory context /home/tito/.local/share/python-for-android/dists/nrt8000
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tito/code/python-for-android/pythonforandroid/toolchain.py", line 686, in <module>
    main()
  File "/home/tito/code/python-for-android/pythonforandroid/toolchain.py", line 683, in main
    ToolchainCL()
  File "/home/tito/code/python-for-android/pythonforandroid/toolchain.py", line 305, in __init__
    getattr(self, args.command)(unknown)
  File "/home/tito/code/python-for-android/pythonforandroid/toolchain.py", line 106, in wrapper_func
    func(self, args)
  File "/home/tito/code/python-for-android/pythonforandroid/toolchain.py", line 530, in apk
    build.parse_args(args)
  File "/home/tito/.local/share/python-for-android/dists/nrt8000/build.py", line 361, in parse_args
    with open(args.blacklist) as fd:
IOError: [Errno 2] No such file or directory: '/home/tito/.local/share/python-for-android/dists/nrt8000/blacklist.txt'
```

**Comment by tito** [comment]
CF PR #552 ?
