### ISSUE TITLE
build.py TypeError args.services object is not iterable

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#616]
Trying to build a debug .apk fails:
```
Traceback (most recent call last):
  File "/home/brussee/.local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.3', 'console_scripts', 'p4a')()
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 708, in main
    ToolchainCL()
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 323, in __init__
    getattr(self, args.command)(unknown)
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 106, in wrapper_func
    func(self, args)
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 555, in apk
    build.parse_args(args)
  File "/home/brussee/.local/share/python-for-android/dists/testproject/build.py", line 464, in parse_args
    make_package(args)
  File "/home/brussee/.local/share/python-for-android/dists/testproject/build.py", line 308, in make_package
    for entrypoint in args.services:
TypeError: 'NoneType' object is not iterable
```

**Comment by inclement** [comment]
Should be fixed now.
