### ISSUE TITLE
Jpeg recipe is broken

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#617]
It is missing /home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/recipes/jpeg/Application.mk
Perpaps just the path is incorrect?
```
[INFO]:    Prebuilding jpeg for armeabi
[INFO]:    jpeg has no prebuild_armeabi, skipping
[DEBUG]:   -> running cp /home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/recipes/jpeg/Application.mk /home/brussee/.local/share/python-for-android/build/other_builds/jpeg/armeabi/jpeg/Application.mk
[DEBUG]:   	/bin/cp: cannot stat ‘/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/recipes/jpeg/Application.mk’: No such file or directory
Traceback (most recent call last):
  File "/home/brussee/.local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.3', 'console_scripts', 'p4a')()
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 708, in main
    ToolchainCL()
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 323, in __init__
    getattr(self, args.command)(unknown)
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 105, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 142, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/build.py", line 543, in build_recipes
    recipe.prebuild_arch(arch)
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/recipes/jpeg/__init__.py", line 22, in prebuild_arch
    shprint(sh.cp, join(self.get_recipe_dir(), 'Application.mk'), app_mk)
  File "/home/brussee/.local/lib/python2.7/site-packages/pythonforandroid/logger.py", line 160, in shprint
    for line in output:
  File "/home/brussee/.local/lib/python2.7/site-packages/sh.py", line 565, in next
    self.wait()
  File "/home/brussee/.local/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/brussee/.local/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1
```

**Comment by kived** [comment]
`*.mk` files in the recipe folders were not being installed. Try installing again and it should work. (The recipe itself does work, but I have p4a installed in pip editable mode.)
