### ISSUE TITLE
Patch files not found

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#633]
Using the attribute patches = [] cannot find the patch files in the obvious location: next to the recipe.

```
[INFO]:    Applying patches for libtorrent[armeabi]
[INFO]:    Applying patch disable-so-version.patch
[DEBUG]:   -> running patch -t -d /home/paul/.local/share/python-for-android/build/other_builds/libtorrent/armeabi/libtorrent -p1 -i ./recipes/libtorrent/disable-so-version.patch
[DEBUG]:   	/usr/bin/patch: **** Can't open patch file ./recipes/libtorrent/disable-so-version.patch : No such file or directory
```

**Comment by inclement** [comment]
Is the path it is trying wrong? What would be correct? And what is your syntax in the python file?

**Comment by kived** [comment]
Are you using `patches = ['disable-so-version.patch']`? It assumes all patches are relative to the recipe package.

**Comment by brussee** [comment]
After copying them from the local recipes folder to the 'global' p4a recipes folder it works.

**Comment by brussee** [comment]
Related to #613 most likely.

**Comment by AndreMiras** [comment]
I'm also affected by this issue, see error below:
```
[INFO]:    Applying patches for eth-rlp[armeabi-v7a]
[INFO]:    Applying patch disable-setuptools-markdown.patch
[INFO]:    -> running patch -t -d /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/eth-rlp-python3crystax/armeabi-v7a/eth-rlp -p1 -i /home/andre/workspa...(and 142 more)
Exception in thread background thread for pid 15493:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/andre/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/andre/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/andre/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_2:

  RAN: /usr/bin/patch -t -d /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/eth-rlp-python3crystax/armeabi-v7a/eth-rlp -p1 -i /home/andre/workspace/EtherollApp/.buildozer/android/
platform/python-for-android-new-toolchain/pythonforandroid/recipes/eth-rlp/disable-setuptools-markdown.patch

  STDOUT:
/usr/bin/patch: **** Can't open patch file /home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipes/eth-rlp/disable-setuptools-markdown.patch : No such file or directory


  STDERR:


[INFO]:    STDOUT:
        /usr/bin/patch: **** Can't open patch file /home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipes/eth-rlp/disable-setuptools-markdown.patch : No 
such file or directory
[INFO]:    STDERR:                                  

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 567, in build_recipes
    recipe.apply_patches(arch)
  File "pythonforandroid/recipe.py", line 486, in apply_patches
    arch.arch)
  File "pythonforandroid/recipe.py", line 194, in apply_patch
    "-i", filename, _tail=10)
  File "pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/home/andre/.local/lib/python2.7/site-packages/sh.py", line 720, in next
    self.wait()
  File "/home/andre/.local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/andre/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2:

  RAN: /usr/bin/patch -t -d /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/eth-rlp-python3crystax/armeabi-v7a/eth-rlp -p1 -i /home/andre/workspace/EtherollApp/.buildozer/android/
platform/python-for-android-new-toolchain/pythonforandroid/recipes/eth-rlp/disable-setuptools-markdown.patch

  STDOUT:
/usr/bin/patch: **** Can't open patch file /home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipes/eth-rlp/disable-setuptools-markdown.patch : No such fil
e or directory
```
Additional info, local recipe layout:
```
find src/python-for-android/recipes/eth-rlp/
src/python-for-android/recipes/eth-rlp/
src/python-for-android/recipes/eth-rlp/disable-setuptools-markdown.patch
src/python-for-android/recipes/eth-rlp/__init__.py
```
p4a.local_recipes:
```
grep local_recipes buildozer.spec 
p4a.local_recipes = %(source.dir)s/python-for-android/recipes/
```
I'm not sure the fact that @brussee found a workaround means the issue is fixed.
