### ISSUE TITLE
Missing recipes: cherrypy, libnacl, requests

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#674]
These 3 pure python packages complain about not having a recipe: cherrypy, libnacl, requests

```
[INFO]:    Loaded recipe libtribler (depends on ['apsw', 'cherrypy', 'libnacl', 'libsodium', 'libtorrent', 'm2crypto', 'netifaces', 'openssl', 'pyasn1', 'pil', 'pyleveldb', 'python2', 'requests', 'twisted'])
[INFO]:    Loaded recipe apsw (depends on ['sqlite3', 'hostpython2', 'python2', 'setuptools'])
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    Loaded recipe libsodium (depends on ['python2'])
[INFO]:    Loaded recipe libtorrent (depends on ['boost', 'python2'])
[INFO]:    Loaded recipe m2crypto (depends on ['openssl', 'hostpython2', 'python2', 'setuptools'])
[INFO]:    Loaded recipe netifaces (depends on ['python2', 'setuptools'])
[INFO]:    Loaded recipe openssl (depends on [])
[INFO]:    Loaded recipe pyasn1 (depends on ['python2'])
[INFO]:    Loaded recipe pil (depends on [('python2', 'python3'), 'png', 'jpeg'])
[INFO]:    Loaded recipe pyleveldb (depends on ['leveldb', 'hostpython2', 'python2', 'setuptools'])
[INFO]:    Loaded recipe python2 (depends on ['hostpython2'], conflicts ['python3crystax', 'python3'])
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    Loaded recipe twisted (depends on ['zope_interface', ('python2', 'python3crystax'), 'setuptools'])
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    No recipe named cherrypy; will attempt to install with pip
[INFO]:    No recipe named libnacl; will attempt to install with pip
[INFO]:    No recipe named requests; will attempt to install with pip
[INFO]:    Loaded recipe sqlite3 (depends on [])
[INFO]:    Loaded recipe hostpython2 (depends on [], conflicts ['hostpython3'])
[INFO]:    Loaded recipe setuptools (depends on ['python2'])
[INFO]:    Loaded recipe boost (depends on ['python2'])
[INFO]:    Loaded recipe png (depends on [])
[INFO]:    Loaded recipe jpeg (depends on [])
[INFO]:    Loaded recipe leveldb (depends on [])
[INFO]:    Loaded recipe zope_interface (depends on ['python2'])
Traceback (most recent call last):
  File "/home/paul/.local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.3', 'console_scripts', 'p4a')()
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 708, in main
    ToolchainCL()
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 323, in __init__
    getattr(self, args.command)(unknown)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 105, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 129, in build_dist_from_args
    = get_recipe_order_and_bootstrap(ctx, dist.recipes, bs)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/graph.py", line 169, in get_recipe_order_and_bootstrap
    graph.remove_remaining_conflicts(ctx)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/graph.py", line 78, in remove_remaining_conflicts
    recipe = Recipe.get_recipe(name, ctx)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/recipe.py", line 618, in get_recipe
    raise IOError('Recipe does not exist: {}'.format(name))
IOError: Recipe does not exist: cherrypy
```

**Comment by brussee** [comment]
Shouldn't they not need one? They did not have a recipe in the old toolchain.

**Comment by inclement** [comment]
These should indeed not need a recipe. I'm not sure what's going on here, I'll try some tests.
