### ISSUE TITLE
Python2 recipe for target 'Lib/plat-linux4' failed

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#688]
Building a debug build with openssl and python2 and sdl2 bootstrap gives: _IOError: invalid Python installation: unable to open /usr/lib/python2.7/config/Makefile (No such file or directory)_

```
/usr/bin/install -c -m 644 ./Include/objimpl.h /home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/python-install/include/python2.7
Traceback (most recent call last):
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/site.py", line 563, in <module>
  main()
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/site.py", line 545, in main
   known_paths = addusersitepackages(known_paths)
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/site.py", line 278, in addusersitepackages
    user_site = getusersitepackages()
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/site.py", line 253, in getusersitepackages
  user_base = getuserbase() # this will also set USER_BASE
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/site.py", line 243, in getuserbase
  USER_BASE = get_config_var('userbase')
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/sysconfig.py", line 520, in get_config_var
 return get_config_vars().get(name)
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/sysconfig.py", line 419, in get_config_vars
   _init_posix(_CONFIG_VARS)
File "/home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/Lib/sysconfig.py", line 287, in _init_posix
   raise IOError(msg)
IOError: invalid Python installation: unable to open /usr/lib/python2.7/config/Makefile (No such file or directory)
/usr/bin/install -c -m 644 ./Include/opcode.h /home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/python-install/include/python2.7
/usr/bin/install -c -m 644 ./Include/osdefs.h /home/paul/.local/share/python-for-android/build/other_builds/python2-openssl/armeabi/python2/python-install/include/python2.7
Makefile:972: recipe for target 'Lib/plat-linux4' failed
make: *** [Lib/plat-linux4] Error 1
```
##

**Comment by brussee** [comment]
This does not fail the build and does not cause a crash for me. However I'd like to document it.

**Comment by inclement** [comment]
Closing as not really an issue, if it even happens any more since both recipes have changed a lot since the original issue.
