### ISSUE TITLE
"NoBackendError: No backend available": Pyusb recipe for android

### ISSUE THREAD

**Issue by abhigenie92** [kivy/python-for-android#740]
My doubt is with respect to the recipe mentioned for pyusb (https://github.com/kivy/python-for-android/tree/master/pythonforandroid/recipes/kivy). I am getting this error while runnning 
`adb logcat`:

```
D/InputReader( 3351): Input event: value=1
I/InputReader( 3351): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.3142 ] when=28963589313000
D/InputReader( 3351): lastThreadEndTime = 28958059026118, currentThreadStartTime = 28958059039868
I/InputDispatcher( 3351): Delivering touch to (8952): action: 0x0, toolType: 1
D/ViewRootImpl( 8952): ViewPostImeInputStage ACTION_DOWN
D/InputReader( 3351): Input event: value=0
I/InputReader( 3351): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=28963684250000
I/InputDispatcher( 3351): Delivering touch to (8952): action: 0x1, toolType: 1
I/python  ( 8952):  Traceback (most recent call last):
I/python  ( 8952):    File "/home/abhishek/Desktop/pyusbwhiteboard/android_app/.buildozer/android/app/connected_screen.py", line 20, in start_server
I/python  ( 8952):    File "/home/abhishek/Desktop/pyusbwhiteboard/android_app/.buildozer/android/app/connected_screen.py", line 41, in grab_data
I/python  ( 8952):    File "/home/abhishek/Desktop/pyusbwhiteboard/android_app/.buildozer/android/app/_applibs/usb/core.py", line 1263, in find
I/python  ( 8952):  NoBackendError: No backend available
I/python  ( 8952): None
D/SSRM:n  ( 3351): SIOP:: AP = 320, PST = 308 (W:22), CUR = 58, LCD = 235
```

The issues(https://github.com/walac/pyusb/issues/26#issuecomment-29665057 and https://github.com/walac/pyusb/pull/29) suggests that it cannot locate the `libusb 1.0`.
##

**Comment by inclement** [comment]
This seems to be because libusb just isn't available on Android. I'm not sure what the solution is, if any, but it probably isn't actually a p4a build issue.
