### ISSUE TITLE
problem with p4a recipe for kivent

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/python-for-android#744]
Hi, 

I have trouble with new python4android, I'm trying to write recipe for kivent.

Source of recipe is here: https://github.com/mahomahomaho/python-for-android/blob/kiventrecipe/pythonforandroid/recipes/kivent_core/__init__.py

Source of modified p4a is here: (I had to modify a bit because kivent has packages in subdirectories), 
https://github.com/mahomahomaho/python-for-android/blob/kiventrecipe/pythonforandroid/recipe.py

Build command is: VERSION_kivy=1.9.2-dev0 APP_ANDROID_P4A_DIR=$PWD/p4a/ buildozer --verbose android_new debug

```
Buildozer.spec is: 
maho@dlaptop:~/workspace/khamster/try-to-write-kivent-recipe$ egrep -v '^#' buildozer.spec | egrep -v '^$'
[app]
title = My Application
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = kivy,kivent_core,python2
orientation = landscape
fullscreen = 1
[buildozer]
log_level = 2
warn_on_root = 1

```

And build error is:
```

[INFO]:    Cythonize kivent_core/rendering/batching.pyx
[INFO]:    -> running cython ./kivent_core/rendering/batching.pyx
[INFO]:    -> running python.host setup.py build_ext -v
()
                                                                                                                                                                                           [INFO]:    STDOUT:
        Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
  File "/home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/setuptools/dist.py", line 18, in <module>
    from setuptools import windows_support
  File "/home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/lib-dynload/_ctypes.so: wrong ELF class: ELFCLASS32
[INFO]:    STDERR:
[INFO]:    COMMAND:
cd /home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/other_builds/kivent-python2/armeabi-v7a/kivent/modules/core && /home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/bin/python.host setup.py build_ext -v
[WARNING]: ERROR: /home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build/build/python-installs/myapp/bin/python.host failed!
# Command failed: python -m pythonforandroid.toolchain --storage-dir=/home/maho/workspace/khamster/try-to-write-kivent-recipe/.buildozer/android/platform/build create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy,kivent_core,python2 --arch armeabi-v7a --copy-libs
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```
 
Full build log is at http://pastebin.com/uQG4r2uW

I believe it's not bug of p4a but I'm doing something wrong, but what?

**Comment by Kovak** [comment]
@mahomahomaho kived just did a pr to fix the recipes for the new toolchain, do you think you could test: https://github.com/kivy/kivent/pull/132

**Comment by kived** [comment]
https://github.com/kivy/python-for-android/pull/743

**Comment by inclement** [comment]
I'm going to close this since there hasn't been any activity and it seems that kived's PR supersedes it.
