### ISSUE TITLE
sdl2 recipe builds bootstrap jni source

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#801]
Why is the sdl2 recipe building the main <= start.c of my service_only bootstrap jni source?
Obviously that won't work?
```
[INFO]:    Building sdl2 for armeabi-v7a
ccache found, will optimize builds
('path is', '/home/paul/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/:/home/paul/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:/home/paul/android-ndk-r10e:/home/paul/android-sdk-linux/tools:~/.local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/paul/.local/bin:/opt/android-sdk-linux/platform-tools:/opt/android-ndk-r10e')
[INFO]:    -> directory context /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/jni
[DEBUG]:   -> running ndk-build V=1
[DEBUG]:   	Android NDK: WARNING:/home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/jni/src/Android.mk:main: non-system libraries in linker flags: -lpython2.7
[DEBUG]:   	Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
[DEBUG]:   	Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
[DEBUG]:   	Android NDK:     current module
[DEBUG]:   	rm -f /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/arm64-v8a/lib*.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi/lib*.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a/lib*.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a-hard/lib*.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/mips/lib*.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/mips64/lib*.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/x86/lib*.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/x86_64/lib*.so
[DEBUG]:   	rm -f /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/arm64-v8a/gdbserver /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi/gdbserver /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a/gdbserver /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a-hard/gdbserver /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/mips/gdbserver /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/mips64/gdbserver /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/x86/gdbserver /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/x86_64/gdbserver
[DEBUG]:   	rm -f /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/arm64-v8a/gdb.setup /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi/gdb.setup /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a/gdb.setup /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a-hard/gdb.setup /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/mips/gdb.setup /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/mips64/gdb.setup /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/x86/gdb.setup /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/x86_64/gdb.setup
[DEBUG]:   	[armeabi-v7a] Install        : libSDL2.so => libs/armeabi-v7a/libSDL2.so
[DEBUG]:   	install -p /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/obj/local/armeabi-v7a/libSDL2.so /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a/libSDL2.so
[DEBUG]:   	/home/paul/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --strip-unneeded  /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/libs/armeabi-v7a/libSDL2.so
[DEBUG]:   	[armeabi-v7a] Compile thumb  : main <= start.c
[DEBUG]:   	/usr/bin/ccache /home/paul/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/obj/local/armeabi-v7a/objs/main/start.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -I/home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/jni/src -DANDROID -I/home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/jni/src/../../../../other_builds/python2-openssl-sqlite3/armeabi-v7a/python2/python-install/include/python2.7 -Wa,--noexecstack -Wformat -Werror=format-security    -I/home/paul/android-ndk-r10e/platforms/android-16/arch-arm/usr/include -c  /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/jni/src/start.c -o /home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/obj/local/armeabi-v7a/objs/main/start.o
[DEBUG]:   	/home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/jni/src/start.c:3:20: fatal error: Python.h: No such file or directory
[DEBUG]:   	 #include "Python.h"
[DEBUG]:   	                    ^
[DEBUG]:   	compilation terminated.
[DEBUG]:   	/home/paul/android-ndk-r10e/build/core/build-binary.mk:464: recipe for target '/home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/obj/local/armeabi-v7a/objs/main/start.o' failed
[DEBUG]:   	make: *** [/home/paul/.local/share/python-for-android/build/bootstrap_builds/service_only-python2/obj/local/armeabi-v7a/objs/main/start.o] Error 1
Traceback (most recent call last):
  File "/home/paul/.local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 763, in main
    ToolchainCL()
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 344, in __init__
    getattr(self, command_method_name)(unknown)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/build.py", line 561, in build_recipes
    recipe.build_arch(arch)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/recipes/sdl2/__init__.py", line 29, in build_arch
    shprint(sh.ndk_build, "V=1", _env=env)
  File "/home/paul/.local/lib/python2.7/site-packages/pythonforandroid/logger.py", line 173, in shprint
    for line in output:
  File "/home/paul/.local/lib/python2.7/site-packages/sh.py", line 565, in next
    self.wait()
  File "/home/paul/.local/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/paul/.local/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/home/paul/android-ndk-r10e/ndk-build V=1'
```

**Comment by brussee** [comment]
Ah I think I need my bootstrap to depend on the new genericndkbuild recipe.
