### ISSUE TITLE
FFmpeg recipe broken

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/python-for-android#810]
p4a reports no compiler found if ffmpeg is in the requirements:

```
p4a apk --requirements=python2,sqlite3,openssl,pyopenssl,lxml,audiostream,cymunk,ffmpeg,pil,pyjnius,twisted,plyer,docutils,pygments,kivy --package=zzz.test.touchtracer --name="Z touchtracer" --version=0.5 --bootstrap=pygame --private /home/kivy/Downloads/examples/demo/touchtracer/
```

```
[INFO]:    -> running cp -Rv /home/kivy/.local/share...(and 156 more)          * many
[INFO]:    <- directory context /home/kivy                                     
[INFO]:    Unpacking hostpython2 for armeabi
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/hostpython2/desktop
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 61 more)
[INFO]:    -> running mv Python-2.7.2 /home/kivy/.lo...(and 79 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking jpeg for armeabi
[INFO]:    -> running basename git://git.linaro.org/p...(and 45 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/jpeg/armeabi
[INFO]:    -> running cp -Rv /home/kivy/.local/share...(and 141 more)          * many
[INFO]:    <- directory context /home/kivy                                     
[INFO]:    Unpacking openssl for armeabi
[INFO]:    -> running basename https://www.openssl.or...(and 30 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/openssl/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 58 more)
[INFO]:    -> running mv openssl-1.0.2g /home/kivy/....(and 73 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking png for armeabi
[INFO]:    -> running basename https://github.com/jul...(and 38 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/png/armeabi
[INFO]:    -> running mv libpng-android-1.6.15 /home...(and 72 more)
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking pygame_bootstrap_components for armeabi
[INFO]:    -> running basename https://github.com/ki...(and 53 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/bootstrap_builds/pygame/jni
[INFO]:    -> running mv p4a-pygame-bootstrap-compon...(and 109 more)
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking sqlite3 for armeabi
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/sqlite3/armeabi
[INFO]:    -> running mv sqlite-amalgamation-3120200...(and 86 more)
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking python2 for armeabi
[INFO]:    -> running basename http://python.org/ftp/...(and 33 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/python2-openssl-sqlite3/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 57 more)
[INFO]:    -> running mv Python-2.7.2 /home/kivy/.lo...(and 87 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking pil for armeabi
[INFO]:    -> running basename http://effbot.org/down...(and 26 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/pil-python2/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 53 more)
[INFO]:    -> running mv Imaging-1.1.7 /home/kivy/.l...(and 72 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking sdl for armeabi
[INFO]:    Skipping sdl unpack as no URL is set
[INFO]:    Unpacking setuptools for armeabi
[INFO]:    -> running basename https://pypi.python.o...(and 56 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/setuptools/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 64 more)
[INFO]:    -> running mv setuptools-18.3.1 /home/kiv...(and 82 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking six for armeabi
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/six-python2/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share/...(and 48 more)
[INFO]:    -> running mv six-1.9.0 /home/kivy/.local...(and 68 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking zope_interface for armeabi
[INFO]:    -> running basename https://pypi.python.o...(and 63 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/zope_interface/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 71 more)
[INFO]:    -> running mv zope.interface-4.1.3 /home/...(and 93 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking pygame for armeabi
[INFO]:    -> running basename http://pygame.org/ftp/...(and 26 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/pygame/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 62 more)
[INFO]:    -> running mv pygame-1.9.1release /home/k...(and 76 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking pyjnius for armeabi
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/pyjnius-python2-sdl/armeabi
[INFO]:    -> running mv pyjnius-master /home/kivy/....(and 85 more)
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking pyopenssl for armeabi
[INFO]:    -> running basename https://pypi.python.o...(and 52 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/pyopenssl/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 60 more)
[INFO]:    -> running mv pyOpenSSL-0.14 /home/kivy/....(and 77 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking twisted for armeabi
[INFO]:    -> running basename https://pypi.python.o...(and 51 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/twisted-python2/armeabi
[INFO]:    -> running tar tf /home/kivy/.local/share...(and 59 more)
[INFO]:    -> running mv Twisted-15.4.0 /home/kivy/....(and 81 more)           
[INFO]:    <- directory context /home/kivy
[INFO]:    -> running rm -rf /home/kivy/.local/share...(and 85 more)
[INFO]:    -> running cp -a /usr/local/lib/python2.7...(and 160 more)
[INFO]:    Unpacking audiostream for armeabi
[INFO]:    -> running basename https://github.com/kiv...(and 32 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/audiostream-python2-sdl/armeabi
[INFO]:    -> running mv audiostream-master /home/ki...(and 97 more)
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking kivy for armeabi
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/kivy-pygame-python2/armeabi
[INFO]:    -> running mv kivy-master /home/kivy/.loc...(and 79 more)
[INFO]:    <- directory context /home/kivy
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding ffmpeg for armeabi
[INFO]:    ffmpeg has no prebuild_armeabi, skipping
[INFO]:    Applying patches for ffmpeg[armeabi]
[INFO]:    Applying patch settings.patch
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 158 more)
[INFO]:    -> running touch /home/kivy/.local/share/...(and 68 more)           
[INFO]:    Prebuilding hostpython2 for armeabi
[INFO]:    -> running cp /usr/local/lib/python2.7/di...(and 162 more)
[INFO]:    Prebuilding jpeg for armeabi
[INFO]:    jpeg has no prebuild_armeabi, skipping
[INFO]:    -> running cp /usr/local/lib/python2.7/di...(and 151 more)
[INFO]:    -> running ln -s /home/kivy/.local/share/...(and 139 more)
[INFO]:    Applying patches for jpeg[armeabi]
[INFO]:    Applying patch build-static.patch
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 156 more)
[INFO]:    -> running touch /home/kivy/.local/share/...(and 64 more)           
[INFO]:    Prebuilding openssl for armeabi
[INFO]:    openssl has no prebuild_armeabi, skipping
[INFO]:    Prebuilding png for armeabi
[INFO]:    png has no prebuild_armeabi, skipping
[INFO]:    Prebuilding pygame_bootstrap_components for armeabi
[INFO]:    Unpacking pygame bootstrap JNI dir components
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/bootstrap_builds/pygame/jni
[INFO]:    -> running mv /home/kivy/.local/share/pyt...(and 102 more) * many
[INFO]:    <- directory context /home/kivy
[INFO]:    Unpacking was successful, deleting original container dir
[INFO]:    -> running rm -rf /home/kivy/.local/share...(and 74 more)
[INFO]:    Prebuilding sqlite3 for armeabi
[INFO]:    sqlite3 has no prebuild_armeabi, skipping
[INFO]:    Prebuilding python2 for armeabi
[INFO]:    python2 has no prebuild_armeabi, skipping
[INFO]:    Applying patches for python2[armeabi]
[INFO]:    Applying patch patches/Python-2.7.2-xcompile.patch
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 198 more)
[INFO]:    Applying patch patches/Python-2.7.2-ctypes-disable-wchar.patch      
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 210 more)
[INFO]:    Applying patch patches/disable-modules.patch                        
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 192 more)
[INFO]:    Applying patch patches/fix-locale.patch                             
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 187 more)
[INFO]:    Applying patch patches/fix-gethostbyaddr.patch                      
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 194 more)
[INFO]:    Applying patch patches/fix-setup-flags.patch                        
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 192 more)
[INFO]:    Applying patch patches/fix-filesystemdefaultencoding.patch          
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 206 more)
[INFO]:    Applying patch patches/fix-termios.patch                            
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 188 more)
[INFO]:    Applying patch patches/custom-loader.patch                          
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 190 more)
[INFO]:    Applying patch patches/verbose-compilation.patch                    
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 196 more)
[INFO]:    Applying patch patches/fix-remove-corefoundation.patch              
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 202 more)
[INFO]:    Applying patch patches/fix-dynamic-lookup.patch                     
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 195 more)
[INFO]:    Applying patch patches/fix-dlfcn.patch                              
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 186 more)
[INFO]:    Applying patch patches/parsetuple.patch                             
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 187 more)
[INFO]:    Applying patch patches/ctypes-find-library-updated.patch            
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 204 more)
[INFO]:    -> running touch /home/kivy/.local/share/...(and 86 more)           
[INFO]:    Prebuilding pil for armeabi
[INFO]:    pil has no prebuild_armeabi, skipping
[INFO]:    Applying patches for pil[armeabi]
[INFO]:    Applying patch disable-tk.patch
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 159 more)
[INFO]:    Applying patch fix-directories.patch                                
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 164 more)
[INFO]:    -> running touch /home/kivy/.local/share/...(and 70 more)           
[INFO]:    Prebuilding sdl for armeabi
[INFO]:    sdl has no prebuild_armeabi, skipping
[INFO]:    Prebuilding setuptools for armeabi
[INFO]:    setuptools has no prebuild_armeabi, skipping
[INFO]:    Prebuilding six for armeabi
[INFO]:    six has no prebuild_armeabi, skipping
[INFO]:    Prebuilding zope_interface for armeabi
[INFO]:    zope_interface has no prebuild_armeabi, skipping
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/zope_interface/armeabi/zope_interface
[INFO]:    <- directory context /home/kivy
[INFO]:    Applying patches for zope_interface[armeabi]
[INFO]:    Applying patch no_tests.patch
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 182 more)
[INFO]:    -> running touch /home/kivy/.local/share/...(and 84 more)           
[INFO]:    Prebuilding pygame for armeabi
[INFO]:    -> running cp /usr/local/lib/python2.7/di...(and 139 more)
[INFO]:    Applying patches for pygame[armeabi]
[INFO]:    Applying patch patches/fix-surface-access.patch
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 176 more)
[INFO]:    Applying patch patches/fix-array-surface.patch                      
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 175 more)
[INFO]:    Applying patch patches/fix-sdl-spam-log.patch                       
[INFO]:    -> running patch -t -d /home/kivy/.local/...(and 174 more)
[INFO]:    -> running touch /home/kivy/.local/share/...(and 68 more)           
[INFO]:    Prebuilding pyjnius for armeabi
[INFO]:    pyjnius has no prebuild_armeabi, skipping
[INFO]:    Applying patches for pyjnius[armeabi]
[INFO]:    -> running touch /home/kivy/.local/share/...(and 82 more)
[INFO]:    Prebuilding pyopenssl for armeabi
[INFO]:    pyopenssl has no prebuild_armeabi, skipping
[INFO]:    Prebuilding twisted for armeabi
[INFO]:    twisted has no prebuild_armeabi, skipping
Should remove twisted tests etc. here, but skipping for now
[INFO]:    Prebuilding android for armeabi
[INFO]:    android has no prebuild_armeabi, skipping
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/android-pygame-python2-python2/armeabi/android
[INFO]:    <- directory context /home/kivy
[INFO]:    Prebuilding audiostream for armeabi
[INFO]:    audiostream has no prebuild_armeabi, skipping
[INFO]:    Prebuilding kivy for armeabi
[INFO]:    kivy has no prebuild_armeabi, skipping
[INFO]:    # Building recipes
[INFO]:    Building ffmpeg for armeabi
ccache found, will optimize builds
('path is', '/home/kivy/android/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/:/home/kivy/android/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/:/home/kivy/android/android-ndk-r8c:/home/kivy/android/android-sdk-linux/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games')
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/ffmpeg/armeabi/ffmpeg
[INFO]:    -> running bash init_update_libs.sh
[INFO]:    -> running bash android_build.sh                                    
Traceback (most recent call last):                                             
  File "/usr/local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 754, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 343, in __init__
    getattr(self, command_method_name)(unknown)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 561, in build_recipes
    recipe.build_arch(arch)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipes/ffmpeg/__init__.py", line 28, in build_arch
    shprint(bash, 'android_build.sh', _env=env)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/logger.py", line 173, in shprint
    for line in output:
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 565, in next
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/bin/bash android_build.sh'

  STDOUT:
patching file fontconfig/src/fcxml.c
Hunk #1 succeeded at 1345 (offset 31 lines).
Hunk #2 succeeded at 1392 (offset 31 lines).
Invalid toolchain name: -4.6
Please use --toolchain=<name> with the name of a toolchain supported by the source NDK.
Try one of:  arm-linux-androideabi-4.4.3 arm-linux-androideabi-4.6 arm-linux-androideabi-clang3.1 llvm-3.1 mipsel-linux-android-4.4.3 mipsel-linux-android-4.6 mipsel-linux-android-clang3.1 x86-4.4.3 x86-4.6 x86-clang3.1
/home/kivy/.local/share/python-for-android/build/other_builds/ffmpeg/armeabi/ffmpeg/x264 /home/kivy/.local/share/python-for-android/build/other_builds/ffmpeg/armeabi/ffmpeg
Makefile:3: config.mak: No such file or directory
cat: config.h: No such file or directory
./configure
No working C compiler found.
make: *** [config.mak] Error 1
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all
Unknown option --disable-shared, ignored
No working C compiler found.


  STDERR:

kivy@kivy:~$
```
##

**Comment by inclement** [comment]
I can reproduce this, but not sure what's wrong.

**Comment by AndreMiras** [comment]
This is rather old, is this still an issue with the old toolchain?

**Comment by inclement** [comment]
We tested ffmpeg earlier, seems to be working well now.
