### ISSUE TITLE
Lxml, docutils need recipe

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/python-for-android#812]
When those are included in requirements, build can't be completed. As @inclement said on irc, those probably require recipes, which are [here](https://github.com/kivy/python-for-android/tree/old_toolchain/recipes).

```
[INFO]:    # Postbuilding recipes
[INFO]:    Postbuilding hostpython2 for armeabi
[INFO]:    Postbuilding jpeg for armeabi
[INFO]:    Postbuilding openssl for armeabi
[INFO]:    Postbuilding png for armeabi
[INFO]:    Postbuilding pygame_bootstrap_components for armeabi
[INFO]:    Postbuilding sqlite3 for armeabi
[INFO]:    Postbuilding python2 for armeabi
[INFO]:    Postbuilding cymunk for armeabi
[INFO]:    Postbuilding pil for armeabi
[INFO]:    Postbuilding sdl for armeabi
[INFO]:    Postbuilding setuptools for armeabi
[INFO]:    Postbuilding six for armeabi
[INFO]:    Postbuilding zope_interface for armeabi
[INFO]:    Postbuilding pygame for armeabi
[INFO]:    Postbuilding pyjnius for armeabi
[INFO]:    Copying pyjnius java class to classes build dir
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build/other_builds/pyjnius-python2-sdl/armeabi/pyjnius
[INFO]:    -> running cp -a jnius/src/org /home/kivy...(and 65 more)
[INFO]:    <- directory context /home/kivy
[INFO]:    Postbuilding pyopenssl for armeabi
[INFO]:    Postbuilding twisted for armeabi
[INFO]:    Postbuilding android for armeabi
[INFO]:    Postbuilding audiostream for armeabi
[INFO]:    Postbuilding kivy for armeabi
[INFO]:    # Installing pure Python modules
[INFO]:    The requirements (lxml, plyer, docutils, pygments) don't have recipes, attempting to install them with pip
[INFO]:    If this fails, it may mean that the module has compiled components and needs a recipe.
[INFO]:    -> directory context /home/kivy/.local/share/python-for-android/build
[INFO]:    -> running virtualenv --python=python2.7 venv
[INFO]:    Creating a requirements.txt file for the Python modules             
[INFO]:    Installing Python modules with pip
[INFO]:    If this fails with a message about /bin/false, this probably means the package cannot be installed with pip as it needs a compilation recipe.
[INFO]:    -> running bash -c source venv/bin/activa...(and 318 more)
Traceback (most recent call last):                                             
  File "/usr/local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 765, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 440, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 142, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 185, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 581, in build_recipes
    run_pymodules_install(ctx, python_modules)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 622, in run_pymodules_install
    ).format(ctx.get_site_packages_dir()))
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/logger.py", line 173, in shprint
    for line in output:
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 565, in next
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1
kivy@kivy:~$
```

**Comment by inclement** [comment]
Thanks for reporting this, but there's a generic issue for it at https://github.com/kivy/python-for-android/issues/464
