### ISSUE TITLE
touchtracer.apk not working

### ISSUE THREAD

**Issue by ciropom** [kivy/python-for-android#82]
I followed the guide in the home page of this project to build touchtracer.apk .
I managed to build the app without errors, 
but when i start it from the emulator this is what logcats report:
```
I/ActivityManager(  148): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.test.touchtracer/org.renpy.android.PythonActivity u=0} from pid 264
D/dalvikvm(  610): Not late-enabling CheckJNI (already on)
I/ActivityManager(  148): Start proc org.test.touchtracer:python for activity org.test.touchtracer/org.renpy.android.PythonActivity: pid=610 uid=10044 gids={1015, 1028}
I/dalvikvm(  610): Turning on JNI app bug workarounds for target SDK version 8...
I/InputReader(  148): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  148): Device reconfigured: id=0, name='qwerty2', surface size is now 800x1280, mode is 1
I/ActivityManager(  148): Config changed: {1.0 310mcc260mnc en_US sw600dp w961dp h528dp lrg land finger qwerty/v/v -nav/h s.7}
E/Trace   (  610): error opening trace file: No such file or directory (2)
V/python  (  610): Extracting public assets.
W/EGL_emulation(  203): eglSurfaceAttrib not implemented
D/dalvikvm(  610): GC_FOR_ALLOC freed 72K, 9% free 7267K/7939K, paused 53ms, total 75ms
W/EGL_emulation(  203): eglSurfaceAttrib not implemented
I/dalvikvm-heap(  610): Grow heap (frag case) to 8.563MB for 1048592-byte allocation
D/dalvikvm(  610): GC_FOR_ALLOC freed 1K, 9% free 8290K/9031K, paused 85ms, total 85ms
I/python  (  610): extracting android.txt
E/python  (  610): could not open /mnt/sdcard/org.test.touchtracer/android.txt
D/dalvikvm(  610): GC_CONCURRENT freed 24K, 9% free 8294K/9031K, paused 32ms+4ms, total 68ms
V/PhoneStatusBar(  203): setLightsOn(true)
I/SDLSurface(  610): surfaceCreated() is not handled :|
D/libEGL  (  610): loaded /system/lib/egl/libEGL_emulation.so
D/        (  610): HostConnection::get() New Host Connection established 0x2a116de8, tid 624
D/libEGL  (  610): loaded /system/lib/egl/libGLESv1_CM_emulation.so
D/        (  610): HostConnection::get() New Host Connection established 0x2a10dd60, tid 610
D/libEGL  (  610): loaded /system/lib/egl/libGLESv2_emulation.so
W/SDLSurface(  610): Choose egl configuration
I/SDLSurface(  610): Try to use graphics config R8G8B8A8S8
W/SDLSurface(  610): Create egl context
W/SDLSurface(  610): Create egl surface
I/Choreographer(  264): Skipped 50 frames!  The application may be doing too much work on its main thread.
W/SDLSurface(  610): Done
I/ActivityManager(  148): Displayed org.test.touchtracer/org.renpy.android.PythonActivity: +1s388ms
D/dalvikvm(  610): GC_FOR_ALLOC freed 1064K, 20% free 7309K/9031K, paused 89ms, total 90ms
I/dalvikvm-heap(  610): Grow heap (frag case) to 8.104MB for 524304-byte allocation
D/dalvikvm(  610): GC_FOR_ALLOC freed <1K, 14% free 7821K/9031K, paused 52ms, total 52ms
D/dalvikvm(  610): GC_CONCURRENT freed <1K, 14% free 7824K/9031K, paused 15ms+2ms, total 96ms
D/dalvikvm(  610): WAIT_FOR_CONCURRENT_GC blocked 25ms
D/dalvikvm(  610): GC_FOR_ALLOC freed <1K, 14% free 7823K/9031K, paused 24ms, total 24ms
I/dalvikvm-heap(  610): Grow heap (frag case) to 8.607MB for 524304-byte allocation
D/dalvikvm(  610): GC_CONCURRENT freed 0K, 8% free 8335K/9031K, paused 14ms+2ms, total 52ms
D/dalvikvm(  610): WAIT_FOR_CONCURRENT_GC blocked 25ms
D/dalvikvm(  610): WAIT_FOR_CONCURRENT_GC blocked 18ms
W/python  (  610): java.io.IOException: open failed: EACCES (Permission denied)
W/python  (  610): 	at java.io.File.createNewFile(File.java:940)
W/python  (  610): 	at org.renpy.android.PythonActivity.unpackData(PythonActivity.java:198)
W/python  (  610): 	at org.renpy.android.PythonActivity.run(PythonActivity.java:214)
W/python  (  610): 	at java.lang.Thread.run(Thread.java:856)
W/python  (  610): Caused by: libcore.io.ErrnoException: open failed: EACCES (Permission denied)
W/python  (  610): 	at libcore.io.Posix.open(Native Method)
W/python  (  610): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/python  (  610): 	at java.io.File.createNewFile(File.java:933)
W/python  (  610): 	... 3 more
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libsdl.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libsdl.so 0x41199170
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libsdl_image.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libsdl_image.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/lib/libsdl_image.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libsdl_ttf.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libsdl_ttf.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/lib/libsdl_ttf.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libsdl_mixer.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libsdl_mixer.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/lib/libsdl_mixer.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libpython2.7.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libpython2.7.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/lib/libpython2.7.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libapplication.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libapplication.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/lib/libapplication.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libsdl_main.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libsdl_main.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/lib/libsdl_main.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/_io.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/_io.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/_io.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/unicodedata.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/unicodedata.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/unicodedata.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/lib/libsqlite3.so 0x41199170
D/dalvikvm(  610): Added shared lib /data/data/org.test.touchtracer/lib/libsqlite3.so 0x41199170
D/dalvikvm(  610): No JNI_OnLoad found in /data/data/org.test.touchtracer/lib/libsqlite3.so 0x41199170, skipping init
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/_sqlite3.so 0x41199170
D/dalvikvm(  610): Trying to load lib /data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload/_imaging.so 0x41199170
I/python  (  610): starting audio thread
I/libSDL  (  610): Physical screen resolution is 1280x736
I/python  (  610): Initialize Python for Android
I/python  (  610): ['/data/data/org.test.touchtracer/files/lib/python2.7/site-packages', '/data/data/org.test.touchtracer/files/lib/site-python']
I/python  (  610): Android path ['/data/data/org.test.touchtracer/files/lib/python27.zip', '/data/data/org.test.touchtracer/files/lib/python2.7', '/data/data/org.test.touchtracer/files/lib/python2.7/lib-dynload', '/data/data/org.test.touchtracer/files/lib/python2.7/site-packages', '/mnt/sdcard/org.test.touchtracer', '/data/data/org.test.touchtracer/files/lib/python2.7/site-packages/PIL']
I/python  (  610): Android kivy bootstrap done. __name__ is __main__
I/python  (  610): Run user program, change dir and execute main.py
I/python  (  610): No main.pyo / main.py found.
I/AndroidRuntime(  610): VM exiting with result code 0, cleanup skipped.
I/WindowState(  148): WIN DEATH: Window{414ad598 org.test.touchtracer/org.renpy.android.PythonActivity paused=false}
W/WindowManager(  148): Force-removing child win Window{41377010 SurfaceView paused=false} from container Window{414ad598 org.test.touchtracer/org.renpy.android.PythonActivity paused=false}
I/ActivityManager(  148): Process org.test.touchtracer:python (pid 610) has died.
W/ActivityManager(  148): Force removing ActivityRecord{414ff2b8 org.test.touchtracer/org.renpy.android.PythonActivity}: app died, no saved state
W/InputDispatcher(  148): channel '41344010 Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  148): channel '41344010 Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
W/WindowManager(  148): Failed looking up window
W/WindowManager(  148): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@4152c0d8 does not exist
W/WindowManager(  148): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7640)
W/WindowManager(  148): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7631)
W/WindowManager(  148): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:854)
W/WindowManager(  148): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:449)
W/WindowManager(  148): 	at dalvik.system.NativeStart.run(Native Method)
I/WindowState(  148): WIN DEATH: null
I/InputReader(  148): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  148): Device reconfigured: id=0, name='qwerty2', surface size is now 800x1280, mode is 1
I/WindowState(  148): WIN DEATH: Window{41344010 Toast paused=false}
W/InputDispatcher(  148): Attempted to unregister already unregistered input channel '41344010 Toast (server)'
I/WindowManager(  148): WINDOW DIED Window{41344010 Toast paused=false}
I/ActivityManager(  148): Config changed: {1.0 310mcc260mnc en_US sw600dp w600dp h888dp lrg port finger qwerty/v/v -nav/h s.8}
W/EGL_emulation(  264): eglSurfaceAttrib not implemented
W/InputMethodManagerService(  148): Got RemoteException sending setActive(false) notification to pid 610 uid 10044
W/EGL_emulation(  203): eglSurfaceAttrib not implemented
W/EGL_emulation(  203): eglSurfaceAttrib not implemented
W/NotificationService(  148): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@414b2bb0 in package org.test.touchtracer
D/dalvikvm(  148): WAIT_FOR_CONCURRENT_GC blocked 0ms
D/dalvikvm(  148): GC_EXPLICIT freed 396K, 13% free 10486K/12039K, paused 14ms+9ms, total 91ms
D/dalvikvm(  256): GC_CONCURRENT freed 354K, 12% free 7803K/8775K, paused 8ms+4ms, total 73ms
```

I followed exactly the same procedure advised in the home of this project apart from the paths.
Can you say to me which is the problem?

Another question, is GPS support available? 
Thank you.

**Comment by aminmarashi** [comment]
I had the same problem, I had an error in my main.py which adb logcat didn't show (because the main.pyo was not created). Solved by fixing the error.
You can check if your main.py has any error that prevents kivy to compile by this command:
python -O -m compileall [your app dir containing main.py]

**Comment by bthornemail** [comment]
I had this same problem I just changed file permissions on my folder and files and was able to compile and run on my device
