### ISSUE TITLE
No such file or directory: ".../whitelist.txt"

### ISSUE THREAD

**Issue by SepehrHml** [kivy/python-for-android#821]
using ```buildozer android_new debug```
```
# Package the application
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/buildozer/__init__.py", line 1020, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/site-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/site-packages/buildozer/__init__.py", line 210, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/android.py", line 647, in build_package
    self._generate_whitelist(dist_dir)
  File "/usr/local/lib/python2.7/site-packages/buildozer/targets/android.py", line 600, in _generate_whitelist
    with open(whitelist_fn, 'w') as fd:
IOError: [Errno 2] No such file or directory: '/path/to/project/.buildozer/android/platform/build/dists/project/whitelist.txt'
```
build folder .buildozer/android/platform/build does not exist.
searched in issues and didn't find anything ...

and i don't think i missed something

**Comment by akshayaurora** [comment]
this issue crept in cause of recent changes to p4a,  bulldozer has been fixed but you need to install it from git, 
```
pip uninstall bulldozer
pip install git+http://github.com/kivy/buildozer --user
```

**Comment by SepehrHml** [comment]
i did what you said and i get similar error :( .

```
# Package the application
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/__init__.py", line 1028, in run_command
    self.target.run_commands(args)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.build()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/__init__.py", line 210, in build
    self.target.build_package()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/targets/android.py", line 647, in build_package
    self._generate_whitelist(dist_dir)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/targets/android.py", line 600, in _generate_whitelist
    with open(whitelist_fn, 'w') as fd:
IOError: [Errno 2] No such file or directory: '/Users/sepehr/Documents/Work/kivy_projects/carshoor/.buildozer/android/platform/build/dists/carshoor/whitelist.txt'
```

**Comment by inclement** [comment]
Could you try downloading the python-for-android master branch and trying again (you should be able to do this by just deleting the .buildozer dir in your build directory)? I've pushed a fix that may resolve this issue, though the problem could suggest there's a deeper problem with buildozer.

**Comment by SepehrHml** [comment]
yet same problem :
```
# Package the application
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/__init__.py", line 1028, in run_command
    self.target.run_commands(args)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.build()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/__init__.py", line 210, in build
    self.target.build_package()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/targets/android.py", line 647, in build_package
    self._generate_whitelist(dist_dir)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/targets/android.py", line 600, in _generate_whitelist
    with open(whitelist_fn, 'w') as fd:
IOError: [Errno 2] No such file or directory: '/Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/platform/build/dists/myapp/whitelist.txt'
```

**Comment by inclement** [comment]
Does the directory /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/platform/build/dists exist? If so, what folders does it contain?

**Comment by SepehrHml** [comment]
```
ls .buildozer/android/platform/
```
result :
```
python-for-android-master
```
its the only thing in there... build folder doesn't exist.

**Comment by inclement** [comment]
Okay, that's useful, thank you. Would you also be able to paste the full buildozer log, with --verbose?

**Comment by inclement** [comment]
Actually, could you first delete the .buildozer folder in your build dir, so that the log includes everything possible?

**Comment by SepehrHml** [comment]
result for  ``` buildozer --verbose android_new debug ``` :
```
# Check configuration tokens
# Ensure build layout
# Create directory /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer
# Create directory /Users/sepehr/Documents/Work/kivy_projects/test2/bin
# Create directory /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/applibs
# Create directory /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/platform
# Create directory /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/app
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/local/Cellar/git/2.4.5/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac
# Search for Java keytool (keytool)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/keytool
# Install platform
# Run 'git clone -b master --single-branch https://github.com/kivy/python-for-android.git python-for-android-master'
# Cwd /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/platform
Cloning into 'python-for-android-master'...
# Apache ANT found at /Users/sepehr/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /Users/sepehr/.buildozer/android/platform/android-sdk-20
# Android NDK found at /Users/sepehr/.buildozer/android/platform/android-ndk-r9c
# Run '/Users/sepehr/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e'
# Cwd /Users/sepehr/.buildozer/android/platform
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Packages available for installation or update: 0
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Packages available for installation or update: 0

# Run '/Users/sepehr/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e -a'
# Cwd /Users/sepehr/.buildozer/android/platform
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Packages available for installation or update: 0
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-10.xml
Packages available for installation or update: 0

# Check that aidl can be executed
# Search for Aidl
# Run '/Users/sepehr/.buildozer/android/platform/android-sdk-20/build-tools/23.0.1/aidl'
# Cwd None
# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
# Run 'python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs'
# Cwd /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/platform/python-for-android-master
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (8, 10, 15, 16, 17, 18, 19, 20, 21, 22, 23)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[WARNING]: Missing executable: autoconf is not installed
[WARNING]: Missing executable: automake is not installed
[WARNING]: Missing executable: libtoolize is not installed
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	myapp: includes recipes (hostpython2, python2, sdl2_image, sdl2_mixer, sdl2_ttf, sdl2, six, pyjnius, kivy, python-bidi), built for archs (armeabi-v7a)
[INFO]:    myapp has compatible recipes, using this one
# Build the application #1
# Copy application source from /Users/sepehr/Documents/Work/kivy_projects/test2
# Create directory /Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/app
# Copy /Users/sepehr/Documents/Work/kivy_projects/test2/main.py
# Package the application
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/__init__.py", line 1028, in run_command
    self.target.run_commands(args)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.build()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/__init__.py", line 210, in build
    self.target.build_package()
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/targets/android.py", line 647, in build_package
    self._generate_whitelist(dist_dir)
  File "/Users/sepehr/Library/Python/2.7/lib/python/site-packages/buildozer/targets/android.py", line 600, in _generate_whitelist
    with open(whitelist_fn, 'w') as fd:
IOError: [Errno 2] No such file or directory: '/Users/sepehr/Documents/Work/kivy_projects/test2/.buildozer/android/platform/build/dists/myapp/whitelist.txt'
```

**Comment by inclement** [comment]
Ah, I think the dist is being created in the wrong directory due to a missing storage-dir option. Would you be able to past the output of `ls ~/.local/share/python-for-android/dists` and `ls ~/.python-for-android/dists` (although at least one of these won't exist).

Thanks for the debug information!

**Comment by SepehrHml** [comment]
``` ~/.local/share/python-for-android ``` this folder doesnt exist at all.
out put of ``` ls ~/.python-for-android/dists ``` is :
``` carshoor	myapp ```

thanks for your fast responses 👍 .

**Comment by inclement** [comment]
Thanks, I think I understand the problem and will take another look later.

**Comment by inclement** [comment]
I've found the problem, my previous fix had a mistake. The PR at https://github.com/kivy/buildozer/pull/375 should hopefully resolve everything. If you're able to test it that would be great (you might need to delete the local .buildozer and ~/.python-for-android first), but otherwise hopefully @akshayaurora can check it tomorrow.

**Comment by SepehrHml** [comment]
it worked well ... its cythonizing right now ...
