### ISSUE TITLE
MD5sum - UnboundLocalError: current_md5 referenced before assignment

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/python-for-android#828]
With the docutils recipe I tried to use md5 too, but this error jumped out crashing whole building.

```
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 775, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 450, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 142, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 185, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 539, in build_recipes
    recipe.download_if_necessary()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipe.py", line 342, in download_if_necessary
    self.download()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipe.py", line 385, in download
    print('downloaded md5: {}'.format(current_md5))
UnboundLocalError: local variable 'current_md5' referenced before assignment
```
##

**Comment by inclement** [comment]
Yeah, md5sum isn't handled yet (although this is a bug, it's supposed to fail in a different way).

**Comment by inclement** [comment]
This should be fixed by the md5 handling commits a while ago.
