### ISSUE TITLE
Kivy builds failing

### ISSUE THREAD

**Issue by nocarryr** [kivy/python-for-android#861]
Builds against kivy's current master branch (as of [e0c77c8](https://github.com/kivy/kivy/commit/e0c77c82387bac32f796df458997aca54f1a0be0)) are failing with tracebacks similar to this:

```
08-05 09:09:00.111 32532 32577 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 16)
08-05 09:09:00.111 32532 32577 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
08-05 09:09:00.121 32532 32577 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.example.rtlsdrtest/files/app/.kivy/logs/kivy_16-08-05_0.txt
08-05 09:09:00.121 32532 32577 I python  : [INFO   ] [Kivy        ] v1.9.2-dev0
08-05 09:09:00.121 32532 32577 I python  : [INFO   ] [Python      ] v2.7.2 (default, Aug  5 2016, 09:06:28)
08-05 09:09:00.121 32532 32577 I python  : [GCC 4.9.x 20150123 (prerelease)]
08-05 09:09:00.141 32532 32577 I python  :  Traceback (most recent call last):
08-05 09:09:00.141 32532 32577 I python  :    File "main.py", line 8, in <module>
08-05 09:09:00.141 32532 32577 I python  :      from kivy.app import App
08-05 09:09:00.141 32532 32577 I python  :    File "/data/user/0/org.example.rtlsdrtest/files/app/lib/python2.7/site-packages/kivy/app.py", line 319, in <module>
08-05 09:09:00.141 32532 32577 I python  :      from kivy.base import runTouchApp, stopTouchApp
08-05 09:09:00.141 32532 32577 I python  :    File "/data/user/0/org.example.rtlsdrtest/files/app/lib/python2.7/site-packages/kivy/base.py", line 29, in <module>
08-05 09:09:00.141 32532 32577 I python  :      from kivy.clock import Clock
08-05 09:09:00.141 32532 32577 I python  :    File "/data/user/0/org.example.rtlsdrtest/files/app/lib/python2.7/site-packages/kivy/clock.py", line 364, in <module>
08-05 09:09:00.141 32532 32577 I python  :      from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
08-05 09:09:00.141 32532 32577 I python  :  ImportError: cannot import name FreeClockEvent
08-05 09:09:00.161 32532 32577 I python  : Python for android ended.
```

Since it's related to `kivy.clock`, I tried setting the version in the kivy recipe to one before [this PR](https://github.com/kivy/kivy/pull/4436) and all seemed well.

I realize this should probably be an issue opened in the kivy repo, but the `ImportError` only occurs in p4a builds (tested current master on desktop).
##

**Comment by linziwen** [comment]
i also have this issue and my logcat show as follows:
08-06 10:51:26.836  4276  4303 I python  : ('Android kivy bootstrap done. __name__ is', '__main__')
08-06 10:51:26.861  4276  4303 I python  : ['/data/user/0/org.example.mystb/files/app/lib/python2.7/site-packages', '/data/user/0/org.example.mystb/files/app/lib/site-python']
08-06 10:51:26.861  4276  4303 I python  : AND: Ran string
08-06 10:51:26.861  4276  4303 I python  : Run user program, change dir and execute entrypoint
08-06 10:51:26.861  4276  4303 I python  : main.py
08-06 10:51:26.942  4276  4303 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.example.mystb/files/app/.kivy/logs/kivy_16-08-06_1.txt
08-06 10:51:26.944  4276  4303 I python  : [INFO   ] [Kivy        ] v1.9.2-dev0
08-06 10:51:26.944  4276  4303 I python  : [INFO   ] [Python      ] v2.7.2 (default, Aug  6 2016, 10:47:53) 
08-06 10:51:26.944  4276  4303 I python  : [GCC 4.9.x 20150123 (prerelease)]
08-06 10:51:26.950  4276  4303 I python  :  Traceback (most recent call last):
08-06 10:51:26.950  4276  4303 I python  :    File "main.py", line 3, in <module>
08-06 10:51:26.951  4276  4303 I python  :      from kivy.app import App
08-06 10:51:26.951  4276  4303 I python  :    File "/data/user/0/org.example.mystb/files/app/lib/python2.7/site-packages/kivy/app.py", line 319, in <module>
08-06 10:51:26.951  4276  4303 I python  :      from kivy.base import runTouchApp, stopTouchApp
08-06 10:51:26.951  4276  4303 I python  :    File "/data/user/0/org.example.mystb/files/app/lib/python2.7/site-packages/kivy/base.py", line 29, in <module>
08-06 10:51:26.952  4276  4303 I python  :      from kivy.clock import Clock
08-06 10:51:26.952  4276  4303 I python  :    File "/data/user/0/org.example.mystb/files/app/lib/python2.7/site-packages/kivy/clock.py", line 364, in <module>
08-06 10:51:26.953  4276  4303 I python  :      from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
08-06 10:51:26.953  4276  4303 I python  :  ImportError: dlopen failed: file offset for the library "/data/user/0/org.example.mystb/files/app/lib/python2.7/site-packages/kivy/_clock.so" >= file size: 0 >= 0
08-06 10:51:26.961  4276  4303 I python  : Python for android ended.


i found that when i use this "**pip install python-for-android**" to install python-for-android it would ok, while when i use "**pip install git+https://github.com/kivy/python-for-android.git**" to install it would reproduce this issue

**Comment by inclement** [comment]
I can reproduce this now, but not sure what's causing it. Will investigate.

**Comment by inclement** [comment]
I think I've just fixed this, would either of you be able to test with the master branch?

There may still be problems with bootstraps other than SDL2, I will fix these tomorrow (but wanted to get sdl2 working ASAP).

**Comment by AndreMiras** [comment]
Closing after no activity and apparently was fixed by @inclement.
Feel free to reopen if it's still an issue on master.
