### ISSUE TITLE
p4a recipes error: missing matplotlib

### ISSUE THREAD

**Issue by hackalog** [kivy/python-for-android#865]
After a fresh pip install of python-for-android (on Ubuntu 16.04), p4a recipes gives the following error:
```
$ p4a recipes
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
android      None    
    depends: [('python2', 'python3'), ('python2', 'python3crystax'), ('pygame', 'sdl2', 'genericndkbuild')]
apsw         3.11.1-r1
    depends: ['sqlite3', 'hostpython2', 'python2', 'setuptools']
audiostream  master  
    depends: ['pyjnius', ('python2', 'python3crystax'), ('sdl', 'sdl2'), 'python2']
babel        2.1.1   
    depends: [('python2', 'python3crystax'), 'setuptools', 'pytz']
boost        1.60.0  
    depends: ['python2']
This is a broken recipe, not a real one!
brokenrecipe None    
    depends: []
cdecimal     2.3     
    depends: ['python2']
cffi         1.4.2   
    depends: [('python2', 'python3crystax'), 'setuptools', 'pycparser', 'libffi']
cherrypy     5.1.0   
    depends: ['hostpython2', 'setuptools']
cryptography 1.3.1   
    depends: [('python2', 'python3crystax'), 'cffi', 'enum34', 'openssl', 'ipaddress', 'idna']
crystaxpython3 3.4.2   
    depends: ['hostpython3']
    conflicts: ['python2', 'python3']
decorator    4.0.9   
    depends: ['hostpython2', 'setuptools']
enum34       1.1.3   
    depends: ['python2', 'setuptools']
evdev        v0.4.7  
    depends: [('python2', 'python3')]
feedparser   5.2.1   
    depends: ['hostpython2', 'setuptools']
ffmpeg       master  
    depends: []
flask        0.10.1  
    depends: [('python2', 'python3'), 'setuptools']
fontconfig   really_old
    depends: ['sdl2']
freetype     2.5.5   
    depends: ['harfbuzz']
genericndkbuild None    
    depends: [('python2', 'python3crystax')]
    conflicts: ['sdl2', 'pygame', 'sdl']
gevent       1.1.1   
    depends: [('python2', 'python3crystax'), 'greenlet']
gevent-websocket 0.9.5   
    depends: [('python2', 'python3crystax'), 'setuptools']
greenlet     0.4.9   
    depends: [('python2', 'python3crystax')]
harfbuzz     0.9.40  
    depends: []
hostpython2  2.7.2   
    depends: []
    conflicts: ['hostpython3']
hostpython3  3.5     
    depends: []
    conflicts: ['hostpython2']
hostpython3crystax 3.5     
    depends: []
    conflicts: ['hostpython2']
icu4c        57.1    
    depends: [('python2', 'python3crystax')]
idna         2.0     
    depends: [('python2', 'python3crystax'), 'setuptools']
ipaddress    1.0.16  
    depends: ['python2']
jpeg         linaro-android
    depends: []
kivy         master  
    depends: ['pyjnius', ('sdl2', 'pygame'), ('python2', 'python3crystax')]
leveldb      1.18    
    depends: []
    optional depends: ['snappy']
libffi       v3.2.1  
    depends: []
libmysqlclient master  
    depends: []
libnacl      1.4.4   
    depends: ['hostpython2', 'setuptools']
libpq        9.5.3   
    depends: [('python2', 'python3')]
libsodium    1.0.8   
    depends: ['python2']
libtorrent   1.0.9   
    depends: ['boost', 'python2']
    optional depends: ['openssl']
libtribler   devel   
    depends: ['apsw', 'cryptography', 'ffmpeg', 'libsodium', 'libtorrent', 'm2crypto', 'netifaces', 'openssl', 'pil', 'pycrypto', 'pyleveldb', 'python2', 'twisted']
libzmq       4.1.4   
    depends: ['python2']
m2crypto     0.24.0  
    depends: ['openssl', 'hostpython2', 'python2', 'setuptools']
Traceback (most recent call last):
  File "/home/hackalog/.local/bin/p4a", line 11, in <module>
    sys.exit(main())
  File "/home/hackalog/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 754, in main
    ToolchainCL()
  File "/home/hackalog/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 343, in __init__
    getattr(self, command_method_name)(unknown)
  File "/home/hackalog/.local/lib/python2.7/site-packages/pythonforandroid/toolchain.py", line 379, in recipes
    recipe = Recipe.get_recipe(name, ctx)
  File "/home/hackalog/.local/lib/python2.7/site-packages/pythonforandroid/recipe.py", line 623, in get_recipe
    raise IOError('Recipe does not exist: {}'.format(name))
IOError: Recipe does not exist: matplotlib
```

**Comment by inclement** [comment]
I was able to reproduce this at one point, but with the current master I no longer can. Does it still happen for you?

**Comment by cletrix** [comment]
I got the same error , any idea ?

**Comment by inclement** [comment]
@cletrix Are you using the master branch of p4a?

**Comment by kakkarotssj** [comment]
same errror

**Comment by tresacton** [comment]
got this after immediately after doing a pip install. this was the first time I've installed this tool. using a Mac with python 2.7.10

**Comment by inclement** [comment]
@tresacton Thanks for the report, but pip will install the stable release in which this is a known issue. I'm looking to do another stable release once this, and a couple of bigger issues, have been resolved.

**Comment by tresacton** [comment]
Ah apologies. I clearly didn't do enough googling there. I was just trying
to feed you more specs for reproducing the bug :)

**Comment by inclement** [comment]
No worries, I genuinely appreciate taking the time to do that :)

**Comment by inclement** [comment]
I've tracked this down to a simple mistake in the official distributed .tar.gz file - the main fix is not to do that next stable release! I've also made the recipes command emit a warning instead of crashing if bad recipes are present, so this should be fixed in master.
