### ISSUE TITLE
Building apk problem for android on OSX EL Capitan 10.11.5

### ISSUE THREAD

**Issue by kiok46** [kivy/python-for-android#878]
System details: OS X EL Capitan 10.11.5 (Pro, Ratina)
Using Buildozer for apk.

Use this example to reproduce: https://github.com/kivy/plyer/tree/master/examples/call
Note: Above example works perfectly when build using linux distro (Ubuntu 14.04 LTS), I have tested it myself.

On use of `buildozer android debug`
App crashes immediately after launching on Android unexpectedly with logs.

complete logs of crash: https://gist.github.com/kiok46/094de3ba9e6764f881f749a56d185b54

On use of `buildozer android_new debug` error shows.

`
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building python2 for armeabi-v7a
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 792, in <module>
    main()
  File "/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 789, in main
    ToolchainCL()
  File "/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 464, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 145, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 188, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 561, in build_recipes
    recipe.build_arch(arch)
  File "/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 44, in build_arch
    self.do_python_build(arch)
  File "/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 73, in do_python_build
    shprint(sh.cp, self.ctx.hostpython, self.get_build_dir(arch.arch))
AttributeError: 'Context' object has no attribute 'hostpython'
 
  # Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/Users/kuldeepsingh/Documents/Building_apks/plyer_call_new/.buildozer/android/platform/build create --dist_name=callexample --bootstrap=sdl2 --requirements=kivy,plyer --arch armeabi-v7a --copy-libs
 # 
 # Buildozer failed to execute the last command
 # The error might be hidden in the log above this error
 # Please read the full log, and search for it before
 # raising an issue with buildozer itself.
 # In case of a bug report, please add a full log with log_level = 2`

**Comment by inclement** [comment]
This is a known bug, you can find a workaround [in the doc](http://python-for-android.readthedocs.io/en/latest/troubleshooting/#attributeerror-context-object-has-no-attribute-hostpython).

**Comment by kiok46** [comment]
Thanks @inclement
