### ISSUE TITLE
Python3: armeabi used to copy, but armeabi-v7a choosen

### ISSUE THREAD

**Issue by thopiekar** [kivy/python-for-android#913]
```
thopiekar@home:/media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork$ LANG=C PYTHONPATH=. python -m pythonforandroid.toolchain create --dist-name sip-test --requirements sip --arch=armeabi-v7a --bootstrap empty --debug
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (2, 3, 4, 5, 6, 7, 9, 11, 12, 13, 14, 23, 24, 25)
[INFO]:    Requested API target 23 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r10e
[INFO]:    Found virtualenv at /usr/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Loaded recipe sip (depends on ['python3'])
[INFO]:    Loaded recipe python3 (depends on ['hostpython3'], conflicts ['python2'])
[INFO]:    Loaded recipe hostpython3 (depends on [], conflicts ['hostpython2'])
[INFO]:    Found a single valid recipe set (this is good)
[INFO]:    The selected bootstrap is empty
[INFO]:    # Creating dist with empty bootstrap
[INFO]:    Dist will have name sip-test and recipes (sip)
[DEBUG]:   -> running cp -r /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork/pythonforandroid/bootstraps/empty/build /home/thopiekar/.local/share/python-for-android/build/bootstrap_builds/empty
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/build/bootstrap_builds/empty
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    Recipe build order is ['hostpython3', 'python3', u'sip']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3
[DEBUG]:   -> running mkdir -p /home/thopiekar/.local/share/python-for-android/packages/hostpython3
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/packages/hostpython3
[DEBUG]:   -> running basename https://github.com/crystax/android-vendor-python-3-5/archive/master.zip
[DEBUG]:        master.zip
[INFO]:    hostpython3 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    Downloading python3
[DEBUG]:   -> running mkdir -p /home/thopiekar/.local/share/python-for-android/packages/python3
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/packages/python3
[DEBUG]:   -> running basename http://python.org/ftp/python/3.4.2/Python-3.4.2.tgz
[DEBUG]:        Python-3.4.2.tgz
[INFO]:    python3 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    Downloading sip
[DEBUG]:   -> running mkdir -p /home/thopiekar/.local/share/python-for-android/packages/sip
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/packages/sip
[DEBUG]:   -> running basename http://downloads.sourceforge.net/project/pyqt/sip/sip-4.18.1/sip-4.18.1.tar.gz
[DEBUG]:        sip-4.18.1.tar.gz
[INFO]:    sip download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3 for armeabi-v7a
[DEBUG]:   -> running basename https://github.com/crystax/android-vendor-python-3-5/archive/master.zip
[DEBUG]:        master.zip
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/build/other_builds/hostpython3/armeabi-v7a
[INFO]:    hostpython3 is already unpacked, skipping
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    Unpacking python3 for armeabi-v7a
[DEBUG]:   -> running basename http://python.org/ftp/python/3.4.2/Python-3.4.2.tgz
[DEBUG]:        Python-3.4.2.tgz
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a
[INFO]:    python3 is already unpacked, skipping
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    Unpacking sip for armeabi-v7a
[DEBUG]:   -> running basename http://downloads.sourceforge.net/project/pyqt/sip/sip-4.18.1/sip-4.18.1.tar.gz
[DEBUG]:        sip-4.18.1.tar.gz
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/build/other_builds/sip/armeabi-v7a
[INFO]:    sip is already unpacked, skipping
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3 for armeabi-v7a
Python3 already patched, skipping.
[INFO]:    Prebuilding sip for armeabi-v7a
[INFO]:    sip has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[WARNING]: Running hostpython build. Arch is armeabi! This is naughty, need to fix the Arch system!
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/build/other_builds/hostpython3/armeabi-v7a/hostpython3
[INFO]:    hostpython already exists, skipping build
[INFO]:    <- directory context /media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork
[INFO]:    Building python3 for armeabi-v7a
[DEBUG]:   -> running cp /home/thopiekar/.local/share/python-for-android/build/other_builds/hostpython3/armeabi/hostpython3/hostpython /home/thopiekar/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a/python3
[DEBUG]:        /bin/cp: cannot stat '/home/thopiekar/.local/share/python-for-android/build/other_builds/hostpython3/armeabi/hostpython3/hostpython': No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork/pythonforandroid/toolchain.py", line 837, in <module>
    main()
  File "/media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork/pythonforandroid/toolchain.py", line 834, in main
    ToolchainCL()
  File "/media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork/pythonforandroid/toolchain.py", line 489, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 562, in build_recipes
    recipe.build_arch(arch)
  File "/media/hdd/home/thopiekar/Projekte/GIT/thopiekar/python-for-android_fork/pythonforandroid/recipes/python3/__init__.py", line 58, in build_arch
    shprint(sh.cp, self.ctx.hostpython, self.get_build_dir(arch.arch))
  File "pythonforandroid/logger.py", line 173, in shprint
    for line in output:
  File "/usr/lib/python2.7/dist-packages/sh.py", line 565, in next
    self.wait()
  File "/usr/lib/python2.7/dist-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/bin/cp /home/thopiekar/.local/share/python-for-android/build/other_builds/hostpython3/armeabi/hostpython3/hostpython /home/thopiekar/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a/python3'

  STDOUT:
/bin/cp: cannot stat '/home/thopiekar/.local/share/python-for-android/build/other_builds/hostpython3/armeabi/hostpython3/hostpython': No such file or directory


  STDERR:

```

The correct location is:
/home/thopiekar/.local/share/python-for-android/build/other_builds/hostpython3/armeabi-v7a/hostpython3/

**Comment by inclement** [comment]
I missed this before, but I think the main issue here is actually that the sip recipe (one of yours own, I guess?) requires python3. python-for-android's python3 and hostpython3 don't actually work, you need to use python3crystax at the moment.

**Comment by thopiekar** [comment]
Thanks will give it a try. Whenever there is a problem with it I'll open a new issue, since it will be unrelated to this one here. If you think my PR is useless, feel free to close it :wink:
