### ISSUE TITLE
ERROR: /usr/bin/ant failed!

### ISSUE THREAD

**Issue by nesergen** [kivy/python-for-android#918]
When I try to compile apk with p4a an error occure:

script:
`p4a apk --private /home/sergen/PythonExp/kivy_exp/TRADE_sql/ --package=org.example.trade --name "Trade" --version 0.1 --bootstrap=sdl2 --requirements=sqlite3,python2,plyer,kivy  --debug --sdk_dir /home/TERRA/Android/SDK_Android/ --android_api=17 --ndk_dir /home/TERRA/Android/android-ndk-r13 --ndk_version=r13`

error:

```
[DEBUG]:        at org.apache.tools.ant.Main.startAnt(Main.java:235)
[DEBUG]:        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
[DEBUG]:        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
[DEBUG]:    Caused by: java.util.zip.ZipException: invalid entry CRC (expected 0x71ae1731 but got 0xee521c36)
[DEBUG]:        at java.util.zip.ZipInputStream.read(ZipInputStream.java:221)
[DEBUG]:        at java.io.FilterInputStream.read(FilterInputStream.java:107)
[DEBUG]:        at com.android.sdklib.internal.build.SignedJarBuilder.writeEntry(SignedJarBuilder.java:311)
[DEBUG]:        at com.android.sdklib.internal.build.SignedJarBuilder.writeZip(SignedJarBuilder.java:244)
[DEBUG]:        at com.android.sdklib.build.ApkBuilder.addZipFile(ApkBuilder.java:540)
[DEBUG]:        ... 63 more
[DEBUG]:    
[DEBUG]:    Total time: 3 minutes 3 seconds
[INFO]:    STDOUT (last 20 lines of 177):
        at org.apache.tools.ant.Task.perform(Task.java:348) 
    at org.apache.tools.ant.Target.execute(Target.java:435) 
    at org.apache.tools.ant.Target.performTasks(Target.java:456)    
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)    
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)  
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)   
    at org.apache.tools.ant.Main.runBuild(Main.java:853)    
    at org.apache.tools.ant.Main.startAnt(Main.java:235)    
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)  
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112) 
Caused by: java.util.zip.ZipException: invalid entry CRC (expected 0x71ae1731 but got 0xee521c36)   
    at java.util.zip.ZipInputStream.read(ZipInputStream.java:221)   
    at java.io.FilterInputStream.read(FilterInputStream.java:107)   
    at com.android.sdklib.internal.build.SignedJarBuilder.writeEntry(SignedJarBuilder.java:311) 
    at com.android.sdklib.internal.build.SignedJarBuilder.writeZip(SignedJarBuilder.java:244)   
    at com.android.sdklib.build.ApkBuilder.addZipFile(ApkBuilder.java:540)  
    ... 63 more 

Total time: 3 minutes 3 seconds
[INFO]:    STDERR:

[INFO]:    COMMAND:
cd /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1 && /usr/bin/ant debug

[WARNING]: ERROR: /usr/bin/ant failed!
```

But ANT installed on my PC.

Besides I got some strange strings during compile. What it means?:

```
[INFO]:    Stripping libraries in private dir
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/core/text/_text_sdl2.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/core/text/text_layout.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/core/audio/audio_sdl2.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/core/window/_window_sdl2.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/core/image/_img_sdl2.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/core/clipboard/_clipboard_sdl2.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/_event.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/weakproxy.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/compiler.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/context_instructions.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/tesselator.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/shader.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/c_opengl_debug.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/fbo.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/scissor_instructions.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/texture.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/vertex.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/vertex_instructions.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/c_opengl_mock.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/context.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/instructions.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/buffer.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/transformation.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/opengl_utils.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/stencil_instructions.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/vbo.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/gl_instructions.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/opengl.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/graphics/svg.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/_clock.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivy/properties.so
[DEBUG]:   Failed to strip /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/jnius/jnius.so
[DEBUG]:   Failed to strip 
[INFO]:    Frying eggs in /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages
[INFO]:    -> directory context /home/sergen/.local/share/python-for-android/dists/unnamed_dist_1

```

**Comment by inclement** [comment]
Not sure what's wrong here, but for what it's worth the 'Failed to strip' messages are probably not a problem.

**Comment by KeyWeeUsr** [comment]
@inclement judging from `Caused by: java.util.zip.ZipException` probably corrupted `private.mp3`, maybe even locked so the tar wasn't rewritten?

**Comment by nesergen** [comment]
It was an error in the " ~/.bashrc " in the ndk and sdk paths.

SOLVED !
