### ISSUE TITLE
command not found exception.

### ISSUE THREAD

**Issue by atarjoe** [kivy/python-for-android#921]
Hi there,

I've try to run the command: "p4a apk --sdk-dir /root/android-studio" but the command failed with the following transcript:
```
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
[INFO]:    Will compile for the following archs: armeabi
[INFO]:    Android API target was not set manually, using the default of 15
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 754, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 343, in __init__
    getattr(self, command_method_name)(unknown)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 87, in wrapper_func
    user_ndk_ver=self.ndk_version)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 226, in prepare_build_environment
    android = sh.Command(join(sdk_dir, 'tools', 'android'))
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 788, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: /root/android-studio/tools/android
```

It appears that p4a try to access the folder tools/android inside the android-studio folder but this folder isn't exist...

Regards,

Ataro.

**Comment by inclement** [comment]
I think your path is just not the right one, you need to point to the Android SDK dir, not the Android Studio dir.

If these are supposed to be the same thing, feel free to reopen this issue.
