### ISSUE TITLE
p4a erroring on SSL connection

### ISSUE THREAD

**Issue by hackalog** [kivy/python-for-android#939]
Not sure what is happening here. This is on a fresh Lubuntu 16.04.1, p4a from git
(full output here: https://gist.github.com/hackalog/64ce647a644487224fc5af45d51fb26a)

```
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/acw/.local/share...(and 39 more)
[INFO]:    -> directory context /home/acw/.local/share/python-for-android/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> running rm SDL2_image-2.0.1.tar.gz
[WARNING]: Should check headers here! Skipping for now.
Downloading sdl2_image from https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    -> running rm -f .mark-SDL2_image-2.0.1.tar.gz
[INFO]:    Downloading sdl2_image from https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 836, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 489, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/build.py", line 540, in build_recipes
    recipe.download_if_necessary()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipe.py", line 342, in download_if_necessary
    self.download()
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipe.py", line 381, in download
    self.download_file(url, filename)
  File "/usr/local/lib/python2.7/dist-packages/pythonforandroid/recipe.py", line 148, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python2.7/urllib.py", line 273, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
```

**Comment by hackalog** [comment]
Oh, wow. Turns out this is a VirtualBox error. https://github.com/mitchellh/vagrant/issues/7946

Short answer OSX + VirtualBox 5.1.8 + certain libraries = failed SSL. Downgrading to 5.0.26 fixes..

Sorry for the noise.
