### ISSUE TITLE
Compling pyo with sdl is breaking ply / enaml

### ISSUE THREAD

**Issue by frmdstryr** [kivy/python-for-android#947]
Not sure why, but for some reason the current master is causing my app to crash on startup. 

Traceback looks like something is breaking `ply.yacc`.

```
12-04 07:22:53.445  3487  3586 I python  : [INFO   ] [GL          ] NPOT texture support is available
12-04 07:22:53.718  3487  3586 I python  :  Traceback (most recent call last):
12-04 07:22:53.718  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/app/main.py", line 64, in <module>
12-04 07:22:53.719  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/platform/build/dists/Thermostat/private/lib/python2.7/site-packages/enamlkv/kv/kv_application.py", line 58, in start
12-04 07:22:53.719  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/platform/build/dists/Thermostat/private/lib/python2.7/site-packages/kivy/app.py", line 802, in run
12-04 07:22:53.720  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/app/main.py", line 29, in build
12-04 07:22:53.720  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/platform/build/dists/Thermostat/private/lib/python2.7/site-packages/enaml/__init__.py", line 61, in imports
12-04 07:22:53.720  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/platform/build/dists/Thermostat/private/lib/python2.7/site-packages/enaml/core/import_hooks.py", line 18, in <module>
12-04 07:22:53.721  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/platform/build/dists/Thermostat/private/lib/python2.7/site-packages/enaml/core/parser.py", line 3986, in <module>
12-04 07:22:53.721  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/platform/build/dists/Thermostat/private/lib/python2.7/site-packages/ply/yacc.py", line 3342, in yacc
12-04 07:22:53.722  3487  3586 I python  :    File "/home/jrm/workspace/thermostat/.buildozer/android/platform/build/dists/Thermostat/private/lib/python2.7/site-packages/ply/yacc.py", line 1635, in set_start
12-04 07:22:53.722  3487  3586 I python  :  IndexError: list index out of range
12-04 07:22:53.769  3487  3586 I python  : Python for android ended.
```

If I switch to the commit  https://github.com/kivy/python-for-android/tree/df84ca554713b9b839615e5b933024765fceec82 from 3 days ago,  do a `buildozer android_new clean` and then build again, it works.

Changes are here:
https://github.com/kivy/python-for-android/compare/df84ca554713b9b839615e5b933024765fceec82...master

**Comment by inclement** [comment]
Thanks for the report. If it's specifically yacc that has the problem, are you able to provide a simple example and p4a configuration to reproduce it with?

**Comment by frmdstryr** [comment]
Will try to make something, although i'm not too familiar with yacc, it's just used by enaml.

**Comment by inclement** [comment]
If it's being used automatically, just the setup that pulls these dependencies and does whatever it takes to trigger the issue should be fine.

**Comment by frmdstryr** [comment]
Hello world example...
[hello_world.zip](https://github.com/kivy/python-for-android/files/629511/hello_world.zip)
