### ISSUE TITLE
Using pyjnius leads to crash (sometimes?) if app built by new toolchain

### ISSUE THREAD

**Issue by germn** [kivy/python-for-android#959]
There's no crash message in logs, but we'll see this lines while app initialization:

```
[ERROR ] Input: AndroidJoystick is not supported by your version of linux

Traceback (most recent call last):

File "/home/kivy/test/.buildozer/android/platform/build/dists/test/private/lib/python2.7/site-packages/kivy/input/providers/__init__.py", line 57, in <module>

File "/home/kivy/test/.buildozer/android/platform/build/dists/test/private/lib/python2.7/site-packages/kivy/input/providers/androidjoystick.py", line 20, in <module>

Exception: android lib not found.
```

and

```
[WARNING] Base: Unknown <android> provider
```

Here's [full typical log](http://pastebin.com/aAi2ntMX). 

<del>Problem was originally discovered [here](https://github.com/kivy/python-for-android/issues/658#issuecomment-203633277), but affects also Python 2.7 builds with Android NDK. </del>

There's no such problem with old toolchain.

**Comment by germn** [comment]
I got it working!

Based on [discussion here](https://github.com/kivy/python-for-android/issues/686#issuecomment-197005106) I created ugly patch that replaces `org.renpy.android.PythonActivity` with `org.kivy.android.PythonActivity` inside pyjnius:

```
def autoclass(clsname):
+    if clsname == 'org.renpy.android.PythonActivity':
+        clsname = 'org.kivy.android.PythonActivity'
```

And after that pyjnius works without crashes. You can test it here:
https://github.com/germn/python-for-android/tree/ugly_pyjnius_fix 

I don't know how pyjnius/Java work, so it's hard for me to create normal fix. 
May be information above will help someone who'll try to fix it.

**Comment by germn** [comment]
These are three separate issues, two of them affects log, one of them about pyjinus:

https://github.com/kivy/python-for-android/issues/962
https://github.com/kivy/python-for-android/issues/963
https://github.com/kivy/pyjnius/issues/249
