### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by khertan** [kivy/python-for-android#984]
While selecting text on a large editable TextInput i often got this error on android.

```
01-17 06:45:32.441  1317  1387 I python  :  Traceback (most recent call last):
01-17 06:45:32.441  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/app/main.py", line 326, in <module>
01-17 06:45:32.441  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/app.py", line 828, in run
01-17 06:45:32.441  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
01-17 06:45:32.441  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 640, in mainloop
01-17 06:45:32.441  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 392, in _mainloop
01-17 06:45:32.451  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/base.py", line 348, in idle
01-17 06:45:32.451  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/clock.py", line 588, in tick_draw
01-17 06:45:32.451  1317  1387 I python  :    File "kivy/_clock.pyx", line 406, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8421)
01-17 06:45:32.451  1317  1387 I python  :    File "kivy/_clock.pyx", line 446, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8295)
01-17 06:45:32.451  1317  1387 I python  :    File "kivy/_clock.pyx", line 444, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8216)
01-17 06:45:32.461  1317  1387 I python  :    File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3530)
01-17 06:45:32.461  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/uix/textinput.py", line 2009, in _update_graphics
01-17 06:45:32.461  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/uix/textinput.py", line 2051, in _update_graphics_selection
01-17 06:45:32.461  1317  1387 I python  :    File "/home/khertan/Projects/gitNotes/.buildozer/android/platform/build/dists/gitnotes/private/lib/python2.7/site-packages/kivy/uix/textinput.py", line 2069, in _draw_selection
01-17 06:45:32.461  1317  1387 I python  :  TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by khertan** [comment]
Oups wrong project.
Sorry
